### PR TITLE
modifications to generateFeatureGrid

### PR DESCRIPTION
**Pull request by zmjones**

### CODE REVIEW

**Comment by larskotthoff** [comment]
Looks like some tests are failing again...

**Comment by zmjones** [comment]
yep sorry! other stuff that doesn't fail interactively for some reason... fixing now

**Comment by zmjones** [comment]
pinging @larskotthoff

**Comment by larskotthoff** [comment]
Thanks, looks good. What's the purpose of the modifications, i.e. should this be mentioned in NEWS?

**Comment by zmjones** [comment]
no i don't think so. there are no user facing changes. it is just a small code efficiency gain.

**Comment by larskotthoff** [comment]
Ok thanks. Merging.

**Pull request merged**
