### PR TITLE
Update variance estimation methods for RF learners

### PR DESCRIPTION
**Pull request by ja-thomas**
- Extratrees is now an available splitting method for classification and regression

- Add se estimation method for `regr.ranger`. (This is mostly copy paste code from `regr.randomForest`) and only one of the three alternatives there.

### CODE REVIEW

**Comment by berndbischl** [comment]
isnt it a bit inconsitent to add only 1 se method from rf...?

yes, it is a clear improvement. can you easily convince me that we should not copy the other 2 methods?

**Comment by ja-thomas** [comment]
yup you're right, all three methods would make sense. 

But I just needed one for now to test some stuff for MBO. But in general it would make sense if the se estimations for random forest would work for all supported RFs, but thats more work.

So the short answer is I was too lazy to copy all three methods... And this is mostly a PR so that the code/branch does not get lost

**Comment by jakob-r** [comment]
We should really have extra methods for se calculation for bagged learners...

**Comment by Stevo15025** [comment]
What else needs done here? May have time next week to help if you need any

**Comment by jakob-r** [comment]
@berndbischl We should merge and be okay with this double code because calculating the SE for bagged learners in general would be a seperate issue. This should not hold back such important progress for the usage of ranger.

**Comment by berndbischl** [comment]
i really dont want the package to become inconsistent here. 
if people want to have this so urgently, please help making this better.

it is really not that hard here.

**Comment by jakob-r** [comment]
Okay. I added generalized functions for sd and jackknife. We might want to put them in a separate file. For a better diff i will do that later (after suggestions for names).

**Comment by jakob-r** [comment]
@berndbischl your opinion would be much appreciated :wink:

**Comment by larskotthoff** [comment]
I've tried to sort out the merge conflicts. Could someone please have a look whether this still makes sense? @jakob-r

**Comment by jakob-r** [comment]
I solved the conflict. If travis passes this can be merged.

**Comment by larskotthoff** [comment]
Ok, I've fixed some obvious stuff, but Travis is still failing and have no idea why. Can't reproduce locally.

**Comment by pat-s** [comment]
@ja-thomas 	just FYI, I merged the master branch. Let's see if the build passes. Do you still think that this is ready to merge then? 

(+ an entry to NEWS.md)

**Comment by pat-s** [comment]
@jakob-r 
For some reason the `par.vals` list in 

https://github.com/mlr-org/mlr/blob/c89a3c2a61786ae86b93cd13ccdd4f9590680add/tests/testthat/test_regr_ranger.R#L31

is not present during the `train()` call in

https://github.com/mlr-org/mlr/blob/c89a3c2a61786ae86b93cd13ccdd4f9590680add/R/RLearner_regr_ranger.R#L41

That is what causes Travis to fail. 

Do you know if this is a general problem of `par.vals` not being forwarded?

**Comment by jakob-r** [comment]
ranger now uses only its own se methods (jacknife and infjacknife (default)). 
Normal rf should work again.
all necessary parameters are set automatically if predict.type = "se" is demanded.

**Comment by pat-s** [comment]
Cool :+1:
The doc still needs to be transformed to markdown and we a NEWS entry, then we're good to go here.

**Pull request merged**
