### PR TITLE
add dbscan clusterer

### PR DESCRIPTION
**Pull request by larskotthoff**

### CODE REVIEW

**Comment by larskotthoff** [comment]
This fixes #511.

**Comment by jakob-r** [comment]
looks good. maybe add another param setting to the test or is it too slow?

**Comment by berndbischl** [comment]
Lars, here you potentially return NA logicals and not integers. Can you please fix that?

Also do we really allow this in the API? 
What happens with all subsequent stuff if some predictions are NA?
Is this anywhere defined?

**Comment by larskotthoff** [comment]
Will have a look at this later.

**Comment by larskotthoff** [comment]
Don't see where this is potentially returning something other than integers -- the return value from the clusterer is wrapped in `as.integer()`. It's not defined what happens when the predictions are NA.

**Comment by berndbischl** [comment]
To be really type safe you should really write NA_integer_.

That returning the NAs is kinda undefined is the problem, isnt it? Maybe we should discuss this orally.

**Comment by larskotthoff** [comment]
I don't know what you mean when you say that I should write NA_integer_. I'm not generating these predictions.

What happens when any of the other learners return NA?

**Comment by larskotthoff** [comment]
Argh, I was looking at the wrong old dbscan cluster branch. Fixed the logical NA thing now.

**Comment by berndbischl** [comment]
status here?

**Comment by larskotthoff** [comment]
Ready to be merged. NEWS may have to be fixed manually after the merge.

**Comment by berndbischl** [comment]
I had to fix NEWS manually, done.

Still, we should define better what happens with 'NAs in the predictions

**Pull request merged**
