### PR TITLE
convert newdata data.table to data.frame with warning in predict

### LINKED ISSUE #1306: predict fails when using a data.table instead of a data.frame
This should work imo

```
library(mlr)
library(data.table)
irisdt = data.table(iris)
mod = train("classif.qda", iris.task)
predict(mod, newdata = irisdt)

> Error in predict(mod, newdata = irisdt) : 
  Assertion on '.newdata' failed: Must be of type 'data.frame', not 'integer'.
```

### PR DESCRIPTION
**Pull request by ja-thomas**
Should fix #1306 

Base change so review thoroughly.

This is basically the same check we do for tasks. We could also create a helper function for that, especially when this is required at more points

### CODE REVIEW

**Comment by larskotthoff** [comment]
I would change the check to include data tables instead of coercing any data into a data frame. This seems overly permissive to me.

**Comment by ja-thomas** [comment]
Well right before the coercing we do an `assertDataFrame`, so most stuff that is not coerable to a data.frame should be catched before.

That way we also remove a warning if we have a `tbl_df` (that works currently but gives an warning).

Not sure what/if other data.frame like objects exist

**Comment by larskotthoff** [comment]
Ok, I changed your check a bit so it works if `data.frame` isn't the first class. I'll merge once Travis is done.

**Comment by larskotthoff** [comment]
Argh, I broke it. I'm not really comfortable with this very general check that catches a specific case. I would prefer a specific check and conversion for a data table. Does that sound ok?

**Comment by ja-thomas** [comment]
so basically this is the exact same we are doing when converting a data.frame (or data.table, tbl_df) to a task.

But we can also do it like that

`"data.frame" %in% class(newdata) && class(newdata)[1] != "data.frame"`

Then we will only convert objects that have the class `data.frame` but also some additional.

**Comment by larskotthoff** [comment]
Ok, fair enough. You've convinced me :)

Merging.

**Pull request merged**
