### PR TITLE
fix bug in ModelMultiplexer predict, where hyperpars were not passed on

### PR DESCRIPTION
**Pull request by berndbischl**
Fixes issue #647 

Please review

### CODE REVIEW

**Comment by schiffner** [comment]
Looks good to me.
* Maybe mention in NEWS that the bug was fixed.
* In the tests (l. 129) there is a copy-paste remnant (comment about threshold tuning that does not apply here)

**Comment by larskotthoff** [comment]
Agreed with Julia.

**Comment by berndbischl** [comment]
ok, in can do both. NEWS i left out because it is really particular, but i can do it

**Comment by berndbischl** [comment]
done.
I decided to remove the later part of the test completely. It has nothing to do with bug, and just wastes time.

review and then merge pls

**Comment by larskotthoff** [comment]
Thanks, merged.

**Pull request merged**
