### PR TITLE
replace expression with quote in parameter requirements (fixes #369)

### LINKED ISSUE #369: Irace tuning doesn't work with dependencies
Tuning with irace gives an error when the parameter sets have dependencies as defined in the learners, e.g.

    library(mlr)

    rdesc = makeResampleDesc("Holdout")
    ctrl = makeTuneControlIrace(maxExperiments = 40, nbIterations = 2, minNbSurvival = 1)
    ps = makeParamSet(
      makeDiscreteLearnerParam(id = "type", default = "C-svc", values = c("C-svc", "nu-svc", "C-bsvc", "spoc-svc", "kbb-svc")),
      makeNumericLearnerParam(id = "C", lower = 0, default = 1, upper = 1e6, requires = expression(type %in% c("C-svc", "C-bsvc", "spoc-svc", "kbb-svc")))
    )
    res = tuneParams("classif.ksvm", task = iris.task, resampling = rdesc, par.set = ps, control = ctrl)

gives me

    Error in !is.na(v) && v : invalid 'y' type in 'x && y'
    In addition: Warning message:
    In is.na(v) : is.na() applied to non-(list or vector) of type 'expression'

Looking at the unit tests for Irace, dependencies are specified with `quote()` instead of `expression()` -- only `expression()` is used in the definition of the learners.

### PR DESCRIPTION
**Pull request by larskotthoff**

### CODE REVIEW

**Comment by berndbischl** [comment]
a unit test is missing here. I will do this now and merge it into the brancg

**Comment by berndbischl** [comment]
see this issue #369

**Comment by schiffner** [comment]
Shouldn't we doc this in the following places, too?  
https://github.com/mlr-org/mlr/blob/master/R/tuneParamsMultiCrit.R  
https://github.com/mlr-org/mlr/blob/master/R/RLearner.R

**Comment by berndbischl** [comment]
Yes, good idea. Would you do that quickly?

Note that I already have opened a related issue for the tutorial.

Cool that you watch these things like a hawk. Or hawkess?

**Comment by schiffner** [comment]
Sorry, saw your comment just now. Will do.

**Comment by aydindemircioglu** [comment]
Yo! 

At long last my prayers were answered and they have published my  book, you can find more info abou it here <http://indicator.mohakars.com/e6pjjhfd>

Pardon my monkey thumbs, myspace

**Pull request merged**
