### PR TITLE
use geom_raster because its more performant

### PR DESCRIPTION
**Pull request by jakob-r**
geom_raster does the same but is more performant and reduces the output file size of the figures.
It does not allow a border for each tile (color aesthetic) but this should be okay for us.

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks -- can you adjust the tests as well please?

**Comment by jakob-r** [comment]
Wasn't aware that there is a test for it. Hopefully it's fixed now.

**Comment by pat-s** [comment]
Restarting the tutorial build, a weird error occured. Let's see. Could you add an entry to `NEWS.md`?

**Comment by jakob-r** [comment]
> Could you add an entry to NEWS.md?
Is it that important?

**Comment by pat-s** [comment]
> Is it that important?

Ok yeah, probably no one cares on the user side.

**Pull request merged**
