### PR TITLE
xgboost_latest fixes for predict and early stopping

### PR DESCRIPTION
**Pull request by khotilov**
xgboost_latest fixes for #935, #1264, https://github.com/dmlc/xgboost/issues/1777

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks for taking care of this! Does this rely on the development version of xgboost? It looks like the tests are failing...

**Comment by khotilov** [comment]
Yes, it's for the xgboost_latest branch which, as I understand, is for keeping up with the development version of xgboost while it's not in CRAN yet.

**Comment by larskotthoff** [comment]
Ok, thanks for the clarification. We'll keep this open for now then and merge once that version is on CRAN.

**Comment by ja-thomas** [comment]
xgboost is updated on CRAN.

I'll merge this PR into the xgboost_latest branch, fix it there and make a new PR

**Pull request merged**
