### PR TITLE
#447 resampleDescs

### PR DESCRIPTION
**Pull request by florianfendt**
@berndbischl 
Put the objects in the zzz.R file like you suggested.
Should I change the docType (roxygen set docType to data)?
What would be a reasonable type here though? 
Class of the Objects or simply (helper)-object?

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks. Could you mention this in NEWS as well please? And you'll have to rebase on master once #531 has been merged unfortunately because caret broke mlr.

**Comment by berndbischl** [comment]
1)
please fix the spelling, and watch this yourself.
Object --> object
Cross-Validation --> Crossvalidation.

2) We dont use "seealso" too much, use family, probably with "family resampling"

3) In this case I would really doc this on one page, in this case the ResampleDesc page.
Do you now how to do this?

4) cv2 is also useful, and "holdout"
What about the nameclash then? is there a way around this?

**Comment by florianfendt** [comment]
So, I put a new section to the ResampleDesc page. Or should this rather go to details? I wasn't so sure.
And sorry for the spelling mistakes. I left the dash for cross-validation though, since it is used this way throughout the help page.

**Comment by florianfendt** [comment]
ok @berndbischl, added everything we just discussed

**Comment by berndbischl** [comment]
Looks good will merge now

**Pull request merged**
