### PR TITLE
add learner cluster.Cobweb

### PR DESCRIPTION
**Pull request by larskotthoff**

### CODE REVIEW

**Comment by berndbischl** [comment]
Seems correct, we can merge in 2.6, not now. Pls check whether params are correct and answer here.
Otherwise looks good

**Comment by larskotthoff** [comment]
Parameters are correct.

**Comment by berndbischl** [comment]
Can you pls update the NEWS without a conflict. Shall I put I template "new version" up there so we dont have these problems anymore?

**Comment by larskotthoff** [comment]
Fixed.

**Pull request merged**
