### PR TITLE
#582 BMR getter for models

### PR DESCRIPTION
**Pull request by florianfendt**

### CODE REVIEW

**Comment by berndbischl** [comment]
Seems good to me.
Lets merge this when the other PR is merged for the bench plot.

Other comments?

**Comment by berndbischl** [comment]
Please document here what happens if "models = FALSE" in benchmark.
This is also unit tested correct?

You could check the same questions for the other getters!
Then we can merge.

**Comment by berndbischl** [comment]
ping @florianfendt

**Comment by florianfendt** [comment]
@berndbischl 
Ok, I documented that for   ````getBMRModels()````and ````getBMRPredictions()````.

I also put a note in ````getBMRPerformances()````and ````getBMRAggrPerformances()````,
the return value can't be ````NULL```` there but the data frames could consist of ````NA```` values
if the measures were calculated on the training sets.

**Comment by berndbischl** [comment]
Ok I will merge this now, it looks good. I will then have one final look at it in master branch

**Comment by berndbischl** [comment]
final remark. I checked it briefly some more but cannot see anything for now which is bad

**Pull request merged**
