### PR TITLE
Convert data if necessary (Fixes Issue #714, #253, #273)

### PR DESCRIPTION
**Pull request by jakob-r**

### CODE REVIEW

**Comment by berndbischl** [comment]
just so you dont do it again, please add a space after "if" and before "("
sorry :)

**Comment by berndbischl** [comment]
also we had a bug here. but you added no unit test. can you please do that?

**Comment by jakob-r** [comment]
I am not so sure whether we had a bug or if dplyr is to blame for giving us a `data.frame` class which does not implement all the necessary methods.

However: We neither have `dplyr` in depends, imports nor suggests. So what is a reasonable way to test it?

**Comment by berndbischl** [comment]
Ah, damn. I guess it does not hurt if we add it to suggests. We might use it anyway soon.

**Comment by jakob-r** [comment]
cleanup and test added, your turn again

**Pull request merged**
