### PR TITLE
#487 tests for measures

### PR DESCRIPTION
**Pull request by florianfendt**
@berndbischl 
So I wrote the tests as discussed:
1) with manual calculations, where I tried to write the code as "raw" as possible, like you suggested. The corresponding objects are called ``` nameofthemeasure.test  ```
2) check if ```performance()```calculates the measures correctly, too. These objects are called ```nameofthemeasure.perf```

As you can see I put both tests in one place to safe some typing, or should I rather put part 2) in a separate file, like ```test_base_performance_measures.R``` ?

### CODE REVIEW

**Comment by berndbischl** [comment]
Hi, thanks a lot.

IMHO the tests can stay where you put them. Are we done here?
Does anybody else have comments?

**Comment by larskotthoff** [comment]
I would put the helper objects into `helper_objects.R`.

**Comment by berndbischl** [comment]
Which helper objects exactly? Stuff should only go into helper_objects, if it is of general use and used in multiple places. If it is used only locally, it should only be defined locally.

**Comment by larskotthoff** [comment]
Well at least the smaller datasets can be used in other contexts as well, especially for more in-depth testing of the learners where we check the individual predictions.

**Comment by berndbischl** [comment]
ok no problem.

**Comment by florianfendt** [comment]
Moved them to helper_objects.
Thanks for the input.

**Comment by florianfendt** [comment]
@berndbischl 
Are we done here, so we can merge?

**Comment by berndbischl** [comment]
Only merging this now, as it is only tests and no API or code change

**Pull request closed without merging**
