### PR TITLE
Modifications to setHyperPars.R

### PR DESCRIPTION
**Pull request by jklanger**

### CODE REVIEW

**Comment by larskotthoff** [comment]
What's the purpose of this change? It seems to break some examples/tests.

**Comment by berndbischl** [comment]
@jklanger 
Please always adds some text that explains your PR. And link to the issue. In most cases the issue link is sufficient to explain what you did, but think about whether you want to add some further comments in the issue description.

the idea is here to deal with issue #759

**Comment by berndbischl** [comment]
@jklanger 
another style thing: please configure your editor that the indentation is 2 spaces. 

and don't do this

```
 expect_identical(getHyperPars(makeLearner("classif.rpart")),
                           getHyperPars(removeHyperPars(lrn, c("minsplit", "xval"))))
```

do this 		  
```
expect_identical(getHyperPars(makeLearner("classif.rpart")),
<2SPACES>getHyperPars(removeHyperPars(lrn, c("minsplit", "xval"))))
```

**Comment by berndbischl** [comment]
@jklanger 
I am not sure whether this is the most simple issue.....
but i guess it is a good "training" for what comes later.

in this case you are touching a pretty important functions of the inner "guts" of mlr. in these cases you should run all unit tests in the "base" group, locally before you push.
do you know how to do that? have you read our contributor guidelines in the wiki?
do you know how to run certain testthat tests interactively? and with mllg's rt tool?

**Comment by berndbischl** [comment]
> @jklanger 
> another style thing: please configure your editor that the indentation is 2 spaces.
> 
> and don't do this
> 
>  expect_identical(getHyperPars(makeLearner("classif.rpart")),
>                    getHyperPars(removeHyperPars(lrn, c("minsplit", "xval"))))
> do this
> 
> expect_identical(getHyperPars(makeLearner("classif.rpart")),
> <2SPACES>getHyperPars(removeHyperPars(lrn, c("minsplit", "xval"))))

in rstudio the setting is called "vertically align args in auto indent" (or so). switch this off, pls.

**Comment by jklanger** [comment]
@Bernd
yes I ran the tests and was naive enough to think the errors were not related to my changes. Won’t commit and try PRs with errors again, sorry. Style things are updated.

**Comment by berndbischl** [comment]
> yes I ran the tests and was naive enough to think the errors were not related to my changes.

the master branch should ALWAYS be free of errors. so you can do exactly what we are discussing here, i.e., check your stuff whether it works. while it can (at least theoretically and hopefully rarely) happen that the master contains errors, alarm bells must go off in this case, and you must inform us about these problems in a separate issue independent of your PR and code, immediately. 

> Won’t commit and try PRs with errors again

it can actually (sometimes!) be good (especially as an mlr devel "beginner")  to push PRs with errors, or unfinished ones. in the cases where you are stuck, and want us to help you with review and hints. or when you just want to see whether travis REALLY runs on your changes. but please communicate with us in the PR description and TELL us if that is the case.

**Comment by berndbischl** [comment]
hi @jklanger 

1) pls check for style again. you still use assign arrows.

2) please rebase this on master

**Comment by berndbischl** [comment]
> 3) also add a comment in the code why you set "empty" names

grr you did not do this. i will do this now in "master". please dont "skip" over these comments from us.

**Comment by jklanger** [comment]
Sorry this comment was not in the mail I received. I first saw it know as I checked the github page…
Won’t happen again.

**Comment by berndbischl** [comment]
> Sorry this comment was not in the mail I received. I first saw it know as I checked the github page…
> Won’t happen again.

yeah ok. then maybe more importantly: 
maybe the problem is that you are using emails for github? 

its much better if you use your browser. i mean, the mails are kinda there to remind you that something happened, but you should go to the thread with the browser, read there and also answer there. works much better.

**Pull request merged**
