### PR TITLE
Refactor resample messages #1332 #1380

### PR DESCRIPTION
**Pull request by florianfendt**
In the above mentioned Issues we discussed how we could improve the output for resample messages and also have a new option for ``configureMlr()`` so the user can set the significant digits shown in console output.
Here's an example output how it looks at the moment:
```
> configureMlr(show.info = TRUE, mlr.digits = 4)
> lrn = makeLearner("regr.lm")
> rin = resample(lrn, bh.task, cv10, list(mape, medae, mse))

Resampling: cross-validation
Measures:             mape   medae  mse    
[Resample] iter 1:    0.1388 1.9538 21.6356
[Resample] iter 2:    0.1917 3.0068 26.8634
[Resample] iter 3:    0.1826 2.2526 12.0277
[Resample] iter 4:    0.2042 2.5565 29.4113
[Resample] iter 5:    0.1816 2.7968 18.0780
[Resample] iter 6:    0.2049 3.4683 20.6871
[Resample] iter 7:    0.1420 2.3513 27.8475
[Resample] iter 8:    0.1451 1.9976 32.1925
[Resample] iter 9:    0.1560 2.7303 20.6107
[Resample] iter 10:   0.1646 2.8376 27.1934

Aggr. Result:         0.1712 2.5951 23.6547
```
Code is far from finished, but open for review and suggestions for improvement are very welcome.

### CODE REVIEW

**Comment by berndbischl** [comment]
@mllg @larskotthoff 
can help to look at this, this is a base change

**Comment by berndbischl** [comment]
first of all, i dont like the name of the new option, but lets review behavior first

**Comment by berndbischl** [comment]
i have given florian quite some feedback, review when he pings us here later

**Comment by florianfendt** [comment]
@berndbischl @larskotthoff @mllg 
I refactored the code according to Bernd's suggestions from this morning.
Here's another example output:
```
> configureMlr(show.info = TRUE, mlr.digits = 4) 
> lrn = makeLearner("regr.ksvm")
> meas = listMeasures(bh.task, create = TRUE)
> meas.sel = meas[7:10]
> rin = resample(lrn, bh.task, cv10, meas.sel)
Resampling: cross-validation
Measures:             mse        sae        rsq        timetrain  
[Resample] iter 1:    16.2848    115.1017   0.8216     0.0320     
[Resample] iter 2:    12.3128    108.3924   0.8244     0.0400     
[Resample] iter 3:    5.3860     87.1230    0.9122     0.0400     
[Resample] iter 4:    19.4855    118.2541   0.7579     0.0410     
[Resample] iter 5:    26.2994    132.6321   0.7644     0.0260     
[Resample] iter 6:    5.8603     92.4116    0.9413     0.0270     
[Resample] iter 7:    6.0248     91.5154    0.9179     0.0230     
[Resample] iter 8:    8.9081     116.1782   0.8780     0.0240     
[Resample] iter 9:    6.1117     91.5896    0.9404     0.0300     
[Resample] iter 10:   19.3548    128.8923   0.7357     0.0210     

Aggregated Result:    12.6028    108.2090   0.8494     0.0304     
```
Open issue is the name for ``mlr.digits``. Any suggestions?

**Comment by larskotthoff** [comment]
Looks good to me in general.

Why is there a magic 22 width prefix? Will this always be 22? Where does the 22 come from?

You shouldn't add the testfile.

Do we need a separate digits option? Could we just use the R one?

And the tests are failing...

**Comment by berndbischl** [comment]
> Why is there a magic 22 width prefix? Will this always be 22? Where does the 22 come from?
please doc this in comments

> You shouldn't add the testfile.
pls remove

> Do we need a separate digits option? Could we just use the R one?
hmm. unsure. @mllg? 

more from my side:
pls in roxygen document what the option actually affects

**Comment by larskotthoff** [comment]
Re magic 22: If there's a programmatic way of getting this number, please use that instead.

**Comment by mllg** [comment]
You should re-use this one here, no need to duplicate options:
```
 ‘digits’: controls the number of digits to print when printing
          numeric values.  It is a suggestion only.  Valid values are
          1...22 with default 7.  See the note in ‘print.default’ about
          values greater than 15.
```

It is a bit embarrassing that after all the years of programming R, I still don't know a good and reliable way to pretty print numbers. For instance, I don't know if `formatC` is the best choice. See this discussion here: https://stackoverflow.com/questions/3245862/format-numbers-to-significant-figures-nicely-in-r

In the end, the most important is that you can easily access the information afterwards. This is just a printer, and you probably cannot get this right for all possible numbers and terminal widths.

**Comment by berndbischl** [comment]
@mllg 
thx! i was not sure whether we should add an extra option so we can control the R digits and mlr's perf digits separately. but lets not introduce "feature creep". we already make stuff better and flexible simply by using R's "digits"

@mllg @larskotthoff 
agreed?

**Comment by berndbischl** [comment]
> In the end, the most important is that you can easily access the information afterwards. This is just a printer, and you probably cannot get this right for all possible numbers and terminal widths.

thats given, we have clean S3 objects, the optpath, etc, bla, bla

**Comment by larskotthoff** [comment]
Fine by me.

**Comment by florianfendt** [comment]
@larskotthoff @berndbischl @mllg 

* **magic 22:** I didn't really like to hardcode this, but it just sets the width for the first column where we put our prefixes for the logging line (e.g: ``Measures:``, ``[Resample] iter: 1``). So to get this number in a programmatic way I would have to do: ``max(stri_width(prefixes))`` and then I still have to add 2 to gain the spaces for the next column. 
I thought it might be a bit too much to do all this only to get the column width needed for the prefixes, which don't change (well, until we decide to change the logging output again)

* **digits:** So I can go ahead removing ``mlr.digits`` again and just use ``options()$digits``?

**Comment by berndbischl** [comment]
> magic 22: I didn't really like to hardcode this, but it just sets the width for the first column where we put our prefixes for the logging line (e.g: Measures:, [Resample] iter: 1). So to get this number in a programmatic way I would have to do: max(stri_width(prefixes)) and then I still have to add 2 to gain the spaces for the next column.
> I thought it might be a bit too much to do all this only to get the column width needed for the prefixes, which don't change (well, until we decide to change the logging output again)

ok, keep it like it is. its ok. just add a comment to say what the 22 means.


> digits: So I can go ahead removing mlr.digits again and just use options()$digits?

yes

**Comment by larskotthoff** [comment]
There's a comment that starts `# Flo` which should probably be removed. Looks good apart from that.

**Comment by berndbischl** [comment]
- mlr.digits is STILL in there. please remove and use options$digits
- printResampleFormatLine: please in doc header add example how printout looks

```
  measure.lognames = extractSubList(measures, "id")
 +  # when predict on both some measure might be in there twice,
 +  # depending on aggregation fun 
 +  if (rin$desc$predict == "both") {
 +    id.train = which(vlapply(measures, function(x) "req.train" %in% x$aggr$properties))
 +    id.test = which(vlapply(measures, function(x) "req.test" %in% x$aggr$properties))
 +    measure.lognames = c(measure.lognames[id.train], measure.lognames[id.test])
 +  }
 +  printResampleFormatLine("Measures:", measure.lognames)

```

I really dont like this code, and I dont understand it. please tell me what happens here

**Comment by berndbischl** [comment]
- you are using cat in one place, but we log with message

**Comment by berndbischl** [comment]
- you also have not documented in printResampleFormatLine what data type y is and apparantly different stuff happens depending on what it is

**Comment by florianfendt** [comment]
>   measure.lognames = extractSubList(measures, "id")
 >  # when predict on both some measure might be in there twice,
 >  # depending on aggregation fun 
 >  if (rin$desc$predict == "both") {
 >    id.train = which(vlapply(measures, function(x) "req.train" %in% x$aggr$properties))
 >    id.test = which(vlapply(measures, function(x) "req.test" %in% x$aggr$properties))
 >    measure.lognames = c(measure.lognames[id.train], measure.lognames[id.test])
 >  }
 >  printResampleFormatLine("Measures:", measure.lognames)

> I really dont like this code, and I dont understand it. please tell me what happens here


What happens is this: When we set the predict type on both, and have an aggregation function that aggregates over test and train the performance needs to be computed for both sets.
Example 
```

lrn = makeLearner("classif.randomForest")
rdesc = makeResampleDesc("Bootstrap", iters = 3L, predict = "both")
m = setAggregation(mmce, b632)
res = resample(lrn, iris.task, rdesc, list(m, acc), show.info = TRUE)

Resampling: OOB bootstrapping
Measures:             mmce      mmce      acc       
[Resample] iter 1:    0.0000000 0.0370370 0.9629630 
[Resample] iter 2:    0.0000000 0.0384615 0.9615385 
[Resample] iter 3:    0.0000000 0.0500000 0.9500000 


Aggregated Result:    0.0264384 0.9581671 
```

Maybe we should then name with mmce.test / mmce.train?

**Comment by larskotthoff** [comment]
@florianfendt Yes, please add `.test`/`.train` suffixes where appropriate.

**Comment by florianfendt** [comment]
@larskotthoff thx, done
I configured the printer for the aggregated results a bit as well.
Here are some example outputs:

```
lrn = makeLearner("classif.randomForest")
rdesc = makeResampleDesc("Bootstrap", iters = 3L, predict = "both")
m = setAggregation(mmce, b632)
res = resample(lrn, iris.task, rdesc, list(m, acc), show.info = TRUE)
> Resampling: OOB bootstrapping
> Measures:             mmce.train   mmce.test    acc.test     
> [Resample] iter 1:    0.0000000    0.0370370    0.9629630    
> [Resample] iter 2:    0.0000000    0.0384615    0.9615385    
> [Resample] iter 3:    0.0000000    0.0500000    0.9500000    
>
>
> Aggregated Result: mmce.b632=0.0264384,acc.test.mean=0.9581671


res = resample(lrn, iris.task, cv2, list(acc, mmce, ber), show.info = TRUE)
> Resampling: cross-validation
> Measures:             acc       mmce      ber       
> [Resample] iter 1:    0.9600000 0.0400000 0.0361552 
> [Resample] iter 2:    0.9600000 0.0400000 0.0441370 
>
>
> Aggregated Result: acc.test.mean=0.9600000,mmce.test.mean=0.0400000,ber.test.mean=0.0401461


benchmark(makeLearners(c("classif.randomForest",  "classif.rpart")), iris.task, show.info = TRUE)

> Task: iris-example, Learner: classif.randomForest
> Resampling: cross-validation
> Measures:             mmce      
> [Resample] iter 1:    0.0333333 
> [Resample] iter 2:    0.0666667 
> [Resample] iter 3:    0.1000000 
> [Resample] iter 4:    0.0666667 
> [Resample] iter 5:    0.0000000 
>
>
> Aggregated Result: mmce.test.mean=0.0533333
>
>
> Task: iris-example, Learner: classif.rpart
> Resampling: cross-validation
> Measures:             mmce      
> [Resample] iter 1:    0.0666667 
> [Resample] iter 2:    0.1333333 
> [Resample] iter 3:    0.0666667 
> [Resample] iter 4:    0.1000000 
> [Resample] iter 5:    0.0333333 
>
>
> Aggregated Result: mmce.test.mean=0.0800000
>
>
>        task.id           learner.id mmce.test.mean
> 1 iris-example classif.randomForest     0.05333333
> 2 iris-example        classif.rpart     0.08000000
```

**Comment by larskotthoff** [comment]
This is ready and nobody has commented in a while. Merging now.

Please direct your abuse my way.

**Pull request merged**
