### PR TITLE
#744 Use stringi internally

### PR DESCRIPTION
**Pull request by MasonGallo**
- [x] base test passed
- [x] add stringi to required packages in description

Addressing #744 - this converts all string functions from base R to use stringi internally. No significant changes were made to internal logic / coding structure.

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks, but it looks like some tests are failing. Could you have a look at that please?

**Comment by MasonGallo** [comment]
Of course it's the test I didn't run locally :) 

This looks like an inconsistency with how base R and stringi handle NAs - I'll look into it.

**Comment by berndbischl** [comment]
hi,

some minor things.

1) 
```
   catf("Task: %s", x$task$task.desc$id)
catf("Measures: %s", stri_paste(sapply(x$measures, function(z) z$name), 
                                  collapse = ", ", sep = " "))
```

In that code, why do you actually set the sep = " " here? Also we have BBmisc::collapse for this. You could even call it in its defaults, then the collapse string is just a comma. More readable.
Also for sapply(x$measures, function(x) x$name) write extractSubList(x$measures, "name")

**Comment by MasonGallo** [comment]
I use the sep argument in the snippet above and several other places because of the (annoyingly) different defaults in base R vs stringi. Base R paste defaults to `sep = " "` while stringi defaults to `sep = ""`.

You bring up a good point with some of the wrappers in the BBmisc I did not know about. I think that should be a separate pull request though? I suspect there are other places in the mlr codebase too.

**Comment by berndbischl** [comment]
> I use the sep argument in the snippet above and several other places because of the (annoyingly) different defaults in base R vs stringi. Base R paste defaults to sep = " " while stringi defaults to sep = "".

ok. i guess its simply best to always use "BBmsic::collapse" here.


> You bring up a good point with some of the wrappers in the BBmisc I did not know about. I think that should be a separate pull request though? I suspect there are other places in the mlr codebase too

please repair the code in THIS PR trough further commits, so we move forward. finding this in all the rest of mlr is probably not that simple. I have mentioned this, so you and others know about this. And so we dont "purposefully" disregard this when we see this here.

But I am also happy to accept other code clean ups later from you if you see stuff someplace else

**Comment by MasonGallo** [comment]
> ok. i guess its simply best to always use "BBmsic::collapse" here.

Looking at the source code for BBmisc::collapse, we still need to use the `sep` argument here to get proper spacing when printing multiple measures.

> But I am also happy to accept other code clean ups later from you if you see stuff someplace else

I misunderstood you and thought you meant clean up everywhere also within this PR 👍 

I'll commit shortly-

**Comment by berndbischl** [comment]
> Looking at the source code for BBmisc::collapse, we still need to use the sep argument here to get proper spacing when printing multiple measures.

no, i would suggest just to live with a,b,c,d ?
who cares, its readable and the code is better?

**Comment by MasonGallo** [comment]
I prefer proper printing to make a better "experience" for the user of the API in exchange for slightly more verbose code. But I can change back if you'd prefer lmk :)

**Comment by berndbischl** [comment]
> But I can change back if you'd prefer lmk :)

the thing is that we use the BBmisc::collapse function as a standard for this (concat strings to print with comma), so I rather see this used.

I guess we could change its default at some point (to ", "), but I dont want to do that now.

**Comment by MasonGallo** [comment]
Understood. I'll revert shortly.

**Comment by MasonGallo** [comment]
ping @larskotthoff @berndbischl 

should we table this for later and close for now?

**Comment by berndbischl** [comment]
i think all is done. i think this is a hopefully clear and internal code improvement.

@larskotthoff @mllg 

can you also look 10 min?

from my side i think we should merge then, if you dont spot bad stuff.

**Comment by berndbischl** [comment]
ah i will just do it now.

**Comment by berndbischl** [comment]
@MasonGallo @zmjones 
I had to rebase this on master. I REMOVED this file 

 R/generatePartialPrediction.R

as this was a conflict and I think Zach renamed these files in a previously merged PR.

Can you please BOTH carefully check whether the diff here in this PR now still looks OK?

Then we can finally merge, hopefully

**Comment by larskotthoff** [comment]
Looks good to me.

**Comment by MasonGallo** [comment]
Looks good - looks like @zmjones deleted generatePartialPrediction.R at #912

**Comment by zmjones** [comment]
@MasonGallo yes all those functions have been renamed and are in generatePartialDependence.R

**Comment by larskotthoff** [comment]
Ok, seems that everybody is fine with this. I'll merge this tonight unless anybody objects.

...or did you want to release a new version of mlr first @berndbischl :innocent:

**Pull request merged**
