### PR TITLE
New Learner and Wrapper

### PR DESCRIPTION
**Pull request by dalpozz**

### CODE REVIEW

**Comment by berndbischl** [comment]
This should be reviewed for 2.6 and merged in 2 different PRs.

**Comment by berndbischl** [comment]
Maybe 2.7. Some stuff seems missing here.

**Comment by larskotthoff** [comment]
@dalpozz Thanks and sorry for taking ages with this. It looks like Travis failed, but it doesn't look like the errors are related to what you did. Could you please added a unit test and mention in NEWS though?

**Comment by dalpozz** [comment]
I plan to add the uni test later in the month, I have no much time now

**Comment by larskotthoff** [comment]
Thanks, there's no rush. We're aiming for the 2.6 release in about a month (so probably early November).

**Comment by larskotthoff** [comment]
@dalpozz Are you still interested in this? Otherwise we'll close here.

**Comment by berndbischl** [comment]
no response, closing here

**Pull request closed without merging**
