### PR TITLE
allow to override all parameters for cforest (fixes #556)

### LINKED ISSUE #556: Error when setting argument "replace" with classif.cforest
**Error:**
When I try to set the argument `replace` of learner `classif.cforest`, I get the following error when the tuning starts:

    Error in cforest_control(teststat = "quad", testtype = "Univ", mincriterion = 0,  : 
    formal argument "replace" matched by multiple actual arguments

**Minimal example:**

    library("mlr")
       
    lrn <- makeLearner("classif.cforest", predict.type = "prob",
                       par.vals = list(ntree = 1000, mtry = 5, minbucket = 10, maxdepth = 0, replace = FALSE))

    ps <- makeParamSet(
        makeDiscreteParam(id = "ntree", values = c(100, 200)),
        makeDiscreteParam(id = "mtry", values = c(5, 10)))
    ctrl <- makeTuneControlGrid()
    rdesc.inner <- makeResampleDesc("Subsample", iters = 5)
    rdesc.outer <- makeResampleDesc("CV", iters = 5)
    lrn.tuned <- makeTuneWrapper(learner = lrn, resampling = rdesc.inner, par.set = ps, control = ctrl)
   
    ## learning
    res <- resample(learner = lrn.tuned, task = pid.task, resampling = rdesc.outer)

However `getParamSet("classif.cforest")` tells me that `replace` is an argument of `classif.cforest`.

**Settings:**
R version: 3.2.2
mlr version: 2.5 (Github version)

### PR DESCRIPTION
**Pull request by larskotthoff**
The code to set defaults is a bit ugly -- I guess what we really need is a function that merges parameter sets, or replaces missing things in parameter sets. I didn't see anything that does it in ParamHelpers, but I could be mistaken.

### CODE REVIEW

**Comment by schiffner** [comment]
Just a question, because that would have been my first approach:
Wouldn't it be easier to put the defaults (at least if not data-dependent) in `par.vals` in `makeRLearner` (like for example in https://github.com/mlr-org/mlr/blob/master/R/RLearner_classif_mda.R)? Then you wouldn't need all the `if(missing(...))`s?

**Comment by larskotthoff** [comment]
Not sure what you mean. Specifying a default value in a parameter set doesn't mean that this parameter gets automatically set to this value if it's not specified. Without the `if(missing(...))`s you'll get errors about missing arguments later on.

**Comment by schiffner** [comment]
I mean `par.vals`, not the `par.set`. In most learner definitions `par.vas` is an empty `list`, but we often use it to set defaults (as e.g. in mda). These settings can be of course overwritten by the user. And all `par.vals` are passed on to training, so there should not be problems with missing arguments.

**Comment by larskotthoff** [comment]
Ah you're right, I hadn't even thought of that. I guess that would require having the defaults in two places though, in `par.set` and `par.vals`. Not sure if this is a better solution here.

**Comment by schiffner** [comment]
Yep. That's the downside. :)

**Comment by larskotthoff** [comment]
Travis failure seems to be unrelated (probably because I didn't regenerate all the documentation?). This is ready to be merged.

**Comment by berndbischl** [comment]
Another comment, for completeness sake:
One option to drastically shorten Lars' code is to simply put the default values into the signature of the trainLearner method. But that has again the downside of having the values in 2 places. 

Actually, we might take this a perfect option to deal with this here now:
#225 
@schiffner 

Right?

**Comment by larskotthoff** [comment]
This is ready to be merged.

**Comment by berndbischl** [comment]
thx merging now

**Pull request merged**
