### PR TITLE
add learners gausspr

### PR DESCRIPTION
**Pull request by Coorsaa**
suggestion for NEWS:

````
new learners
-- classif.gausspr
-- regr.gausspr
````

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks. I see that there are quite a few FIXMEs in the code -- is this something that should be done before merging?

**Comment by berndbischl** [comment]
these look like copy-paste FIXMEs from other kernlab code. please remove this

**Comment by catastrophic-failure** [comment]
At least the `"stringdot"` one should remain, it's the same among every `kernlab` learner.

**Comment by berndbischl** [comment]
@Coorsaa 
delete the other copy-pasta stuff so we can be done here please, the stringkernel stuff FIXME stuff can remain

**Comment by Coorsaa** [comment]
@berndbischl and @larskotthoff: Thanks for the input, wasn't sure about the FIXMEs so I left them in in first place. Should be fine now.

**Comment by larskotthoff** [comment]
Thanks, looks good. Can be merged as far as I'm concerned. @berndbischl ?

**Pull request merged**
