### PR TITLE
adds filter documentation for permutation importance

### PR DESCRIPTION
**Pull request by zmjones**
this is not ready for merging yet. is this the preferred doc structure for the filter constructors? if so i will go back and fill in some more of them. and travis generates the docs now right? so i should not generate/commit them?

### CODE REVIEW

**Comment by berndbischl** [comment]
Talked to Zach on hangout. The docs look basically OK, but I dont know if @param works here.

**Comment by zmjones** [comment]
I generated the docs last night. I can't see how to get each of the constructors to appear as its own section. The params just appear as if there was a "filter" function.

**Comment by berndbischl** [comment]
That is what I thought would happen. 
Can you try to doc them "customly" in a reasonable way please?

**Comment by zmjones** [comment]
ok so i think the best alternative is to put everything in the `makeFilter` doc page. In the description field we can have a list and for each item we describe the filter method and what additional arguments it takes. thoughts?

**Comment by berndbischl** [comment]
Sound good.

**Comment by zmjones** [comment]
Ok I've changed the docs in the manner I suggested. If you like it then I can do some more and put that in a separate PR. I added a test for the issue as well.

**Comment by larskotthoff** [comment]
Is this ready to be merged?

**Comment by zmjones** [comment]
what do you think about the way that i documented the permutation importance filter?

**Comment by larskotthoff** [comment]
Reads fine to me.

**Comment by zmjones** [comment]
then yep it can be merged

**Comment by larskotthoff** [comment]
Great, thanks.

**Comment by berndbischl** [comment]
thx a lot for doing this!
are you going to add more docs for the other filters? 
or do you need support here?

(we also should not accept stuff anymore in master without proper docs...)

**Comment by zmjones** [comment]
i will issue another pr in the next day or two for some of the other filters. probably not all of them though.

**Comment by berndbischl** [comment]
very nice, thx

**Pull request merged**
