### PR TITLE
#898 facet_wrap for plotBMRBoxplots

### PR DESCRIPTION
**Pull request by florianfendt**
I don't know if we want parameter checks and/or mention that logicals are also possible,
since ggplot is already taking care of it?

Possible update for NEWS
````
- The function "plotBMRBoxplots" got two new arguments "facet.wrap.nrow" and
  "facet.wrap.ncol" which enable arrangement of facets in rows and columns.
````

### CODE REVIEW

**Comment by larskotthoff** [comment]
Hmm, we should probably consistently do this for all plots that do facetting. Could you have a look at the other plots as well please?

**Comment by florianfendt** [comment]
Ok, did it.
Why exactly did roxygen delete that line in NAMESPACE? I updated the package but the diff remains...

**Comment by berndbischl** [comment]
Pls remove those lines and doc what the default does

```

+    if (is.null(facet.wrap.nrow) && is.null(facet.wrap.ncol))
 +      facet.wrap.nrow = 1L

```

**Comment by florianfendt** [comment]
@berndbischl 
did what you asked for. I think we can merge.

**Comment by larskotthoff** [comment]
Thanks, merging.

**Comment by berndbischl** [comment]
@larskotthoff 
you requested that this API change to be performed for *multiple* functions. but now the entry you just added to NEWS is wrong. please fix!

**Comment by larskotthoff** [comment]
Done.

**Comment by berndbischl** [comment]
> Done.

thx. lets be careful here pls.

**Pull request merged**
