### PR TITLE
Deactivate test small values

### PR DESCRIPTION
**Pull request by ja-thomas**
We should reactivate the test as soon as Param Helpers is updated to 1.9

but otherwise we can not release mlr 2.10

### CODE REVIEW

**Comment by larskotthoff** [comment]
Can you give some more context please? What breaks and why? Why are you commenting the tests? We use the github version of PH for Travis and Jenkins.

**Comment by ja-thomas** [comment]
Sure

was written a bit confusing, but @berndbischl was in the same room so he knew what this is about. Essentially the mentioned test does **only** work with PH 1.9, not with the current CRAN release. So our tests are working on travis and jenkins, but since we planned to release mlr 2.10 today or tomorrow we need to deactivate this test, otherwise rcheck will fail

**Comment by larskotthoff** [comment]
Ugh, this is terrible. I've created a new Jenkins job that uses the CRAN version of PH now. But this test won't be run by CRAN, will it? Do we actually need to disable this?

**Comment by larskotthoff** [comment]
I'm getting more errors with the CRAN version of PH:

```
1. Error: downsample wrapper works with xgboost, we had issue #492 (@test_base_downsample.R#36) 
2. Error: getHyperPars (@test_base_getHyperPars.R#26) 
3. Error: tuning does not break with small discrete values, see bug in #1115 (@test_base_tuning.R#162) 
```

**Comment by ja-thomas** [comment]
arent all base tests run by CRAN? at least R CMD CHECK failed because of this.

3. is the error of the test I disable in this PR

The other two errors didn't occured when I tested with the CRAN PH version

**Comment by larskotthoff** [comment]
I can reproduce all errors locally when running `R CMD check --as-cran`.

**Comment by ja-thomas** [comment]
So the Plan is now to update PH on CRAN first, so this PR should be obselete, but I'll keep this open until the update is actually done

**Comment by larskotthoff** [comment]
Ok, sounds good. Can we please please please avoid such situations in the future or at least make PH releases *immediately* after such a change?

**Comment by berndbischl** [comment]
> Ok, sounds good. Can we please please please avoid such situations in the future or at least make PH releases immediately after such a change?

we are really trying our best here....
actually we invested lots of time to figure out the best option....

IMHO this is now: release PH first.

**Comment by ja-thomas** [comment]
PH is now 1.9 on CRAN

**Pull request closed without merging**
