### PR TITLE
fixes #922

### LINKED ISSUE #922: 2d partial prediction plots
Instead of plotting a graph for each value one could plot a ggplot with colors @zmjones.
Just as idea. 

Example code of @RaphaelCouronne: 
```

library(mlr)
library(ggplot2)
library(gridExtra)

## Datas

# Data
data(iris)
lrn.classif = makeLearner("classif.ksvm", predict.type = "prob")
fit.classif = train(lrn.classif, iris.task)

# Partial Dependance Plot
pd.int = generatePartialPredictionData(fit.classif, iris.task, c("Sepal.Width", "Petal.Length"), TRUE)
df=pd.int$data


## Plots 2D

# Virginica
df1=df[which(df=="virginica"),]
maxProba=max(df1$Probability)

ggplot(data = df1, aes(x=Sepal.Width, y=Petal.Length, fill=Probability)) + 
  geom_tile()+
  scale_fill_gradient2(low = "blue", high = "red",
                       midpoint = maxProba/2, limit = c(0,maxProba), space = "Lab",
                       name="Probability")+ ggtitle("virginica")

# Setosa
df2=df[which(df=="setosa"),]
maxProba=max(df2$Probability)

ggplot(data = df2, aes(x=Sepal.Width, y=Petal.Length, fill=Probability)) + 
  geom_tile()+
  scale_fill_gradient2(low = "blue", high = "red",
                       midpoint = maxProba/2, limit = c(0,maxProba), space = "Lab",
                       name="Probability")+ ggtitle("setosa")

# versicolor
df3=df[which(df=="versicolor"),]
maxProba=max(df3$Probability)

ggplot(data = df3, aes(x=Sepal.Width, y=Petal.Length, fill=Probability)) + 
  geom_tile()+
  scale_fill_gradient2(low = "blue", high = "red",
                       midpoint = maxProba/2, limit = c(0,maxProba), space = "Lab",
                       name="Probability")+ ggtitle("versicolor")


```

### PR DESCRIPTION
**Pull request by zmjones**
adds support for classification tile plots in plotPartialDependence

apparently i fixed this some time ago (#923) and then it was somehow overwritten (probably by me).

### CODE REVIEW

**Comment by larskotthoff** [comment]
Wait, what exactly is this PR? The diff doesn't look like a subset of #923.

**Comment by zmjones** [comment]
how so? it implements the same functionality, albeit in a somewhat more terse fashion. you can now plot bivariate partial dependence for classification tasks by faceting by target classes

**Comment by zmjones** [comment]
in the meantime i removed the contouring option because i didn't think it added anything and could fail in some circumstances, but otherwise this is the same.

**Comment by larskotthoff** [comment]
So this is not a new feature? The code where you're setting stuff depending on the tasks type seems new.

**Comment by zmjones** [comment]
that is the more terse part relative to the older version which got overwritten. otherwise it is the same. it is new relative to master but this feature should be there. i think i must have accidentally removed it during a rebase or something. or maybe someone else did.

**Comment by larskotthoff** [comment]
Ok thanks, merging.

**Comment by berndbischl** [comment]
@zmjones 
can you please configure your emacs for the correct intendation?
you are still aligning vertically under parentheses

**Comment by zmjones** [comment]
yea sorry. they hardcoded this variable into ESS (the stats mode) and i have to dig around to find it and recompile everything.

**Pull request merged**
