### PR TITLE
regr.nnet: remove unneeded params

### PR DESCRIPTION
**Pull request by berndbischl**
see issue #2257

### CODE REVIEW

**Comment by larskotthoff** [comment]
Could you move the comment to the learner note please?

**Comment by berndbischl** [comment]
> Could you move the comment to the learner note please?

no, we are not adding notes about stuff we didnt do because they dont make sense?

**Comment by larskotthoff** [comment]
That `linout = TRUE` seems to be useful to know for users.

**Comment by berndbischl** [comment]
> That linout = TRUE seems to be useful to know for users.

ah. that i agree with. will do.

**Comment by berndbischl** [comment]
done

**Comment by larskotthoff** [comment]
Thanks, merging.

**Pull request merged**
