### PR TITLE
move travis r_packages and r_github_packages to Remotes field of Description

### PR DESCRIPTION
**Pull request by pat-s**
as suggested in https://github.com/travis-ci/travis-ci/issues/8107#issuecomment-316369135

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks, merging.

**Comment by berndbischl** [comment]
> The remotes field has to be removed prior to CRAN release though: https://github.com/hadley/devtools/blob/master/vignettes/dependencies.Rmd#cran-submission

arg shit. @mllg can we do this in rt ?

**Comment by mllg** [comment]
Do we need the Remotes? Everything except quickcheck is on CRAN. 

We could just skip the respective tests if quickcheck is not installed, and drop the Remotes.

**Comment by berndbischl** [comment]
well the link to the travis thread explains that this will enable the cache. so there is an advantage.
i just dont want to manually remember and remove those lines before a release

regarding quickcheck: we dont use that anyway.

**Comment by berndbischl** [comment]
but we need a decision here: either drop the field now from DESC or rt supports removal with "rbuild"

**Comment by mb706** [comment]
reminder that CRAN `lintr` doesn't work.

**Comment by pat-s** [comment]
also just right now saw the [verification](https://github.com/travis-ci/travis-ci/issues/8107#issuecomment-316480737) that it has to be reverted before a CRAN release

**Comment by mllg** [comment]
> reminder that CRAN lintr doesn't work.

You can still explicitly install it via `r_github_packages`. If it is not compatible with CRAN, we should not use it IMHO.

**Comment by larskotthoff** [comment]
Ok, so revert this?

**Comment by berndbischl** [comment]
> Ok, so revert this?

i think that is the best option

**Pull request merged**
