### PR TITLE
Failing learners in todo files

### PR DESCRIPTION
**Pull request by florianfendt**
To clean up the PR list , i added the failing learners to the todo files for now. The errors seem to be travis related but I will look into this again once the Issue tracker isn't so busy anymore

### CODE REVIEW

**Comment by jakob-r** [comment]
I thin that is not the way we want to go. Leave the failing learners as Pull requests. Here we see why it fails and once we tackle the problem on Travis we can simply edit the PR or simply restart the check.

**Comment by larskotthoff** [comment]
Agreed with @jakob-r -- please leave the pull requests open.

Bernd suggested that you could make a Wiki page for issue #257 and close the issue itself -- something where we can see immediately what the status of the new learners is.

**Comment by larskotthoff** [comment]
@florianfendt It would also be great if you could look through todo-files and move all the learners into branches.

**Comment by berndbischl** [comment]
i agree. we will try to get rid off "todofiles" now.
lets all clean it up.
lars and I will start now. 



@all

**Comment by berndbischl** [comment]
for the learners leave the PRs and create more.

BUT BUT BUT

If somebody does a NEW PR he ENSURES that he did not do that "automatically", but that the code to his BEST knowledge is as good as it should be.

**Comment by berndbischl** [comment]
I just merge this now, it just puts some files in todo

**Pull request merged**
