### PR TITLE
PR to fix MAX_NUM_DLL error

### PR DESCRIPTION
**Pull request by Stevo15025**
See #1318 and #1535 

@larskotthoff should this be broken up at the `test_that()` level?

### CODE REVIEW

**Comment by Stevo15025** [comment]
Also a new argument was added to `listLearners()` called subset which lets you select the `1:10` or `20:35` elements of the set of learners.

**Comment by larskotthoff** [comment]
Thanks for looking at this. I'm not sure if the additional argument is needed though -- you can simply listLearners with `create = FALSE` and then subset. The general way of splitting up the tests is fine, but please pull out the common things into a function to reduce the code duplication. Please also have a look at the run-* files in tests/ to see if similar things need to be one there.

**Comment by Stevo15025** [comment]
> Thanks for looking at this.

No problem!

> I'm not sure if the additional argument is needed though -- you can simply listLearners with create = FALSE and then subset.

Yes I did not see exactly what you meant by that before, but now mylist is called with `create = FALSE` and then a subset and lapply are used to create the learners.

> The general way of splitting up the tests is fine, but please pull out the common things into a function to reduce the code duplication. 

Added [here](https://github.com/mlr-org/mlr/pull/1560/files#diff-f6ed7c01d90bb7b026a3f16aa690a747R242)

> Please also have a look at the run-* files in tests/ to see if similar things need to be one there.

Sure, though I think we should try to do this as little as possible. In the end of the day this does make the tests a lot more convoluted. And when R 3.4 comes out we can set the MAX_NUM_DLLs so this won't be an error anymore.

**Comment by Stevo15025** [comment]
Also testing mboost is causing my computer to crash? Very odd

**Comment by larskotthoff** [comment]
Tests fail with

```
Running the tests in ‘tests/run-learners-classif.R’ failed.
Last 13 lines of output:
  2: lapply(lrns$class[subset], makeLearner) at /usr/local/jenkins/jobs/mlr-PRbuilder/workspace/mlr.Rcheck/tests/testthat/helper_learners_all.R:249
  3: FUN(X[[i]], ...)
  4: assertString(cl)
  5: makeAssertion(x, res, .var.name, add)
  6: mstop("Assertion on '%s' failed: %s.", var.name, res, attach = x)
  7: assertion_error(sprintf(msg, ...), call = sys.call(1L), attach = attach)
  
  testthat results ================================================================
  OK: 1186 SKIPPED: 0 FAILED: 1
  1. Error: learners work: classif 61:87 (@test_learners_all_classif.R#20) 
```

**Comment by Stevo15025** [comment]
Can you check if 

```
 testThatDefaultClassifAllLearners(1:20)
```

causes your desktop version of R to crash? Everything is running besides that and the check for probability. both of those tests call mboost and after calling it crash.

**Comment by larskotthoff** [comment]
Works for me. Have you tried updating to the latest version of mboost?

**Comment by Stevo15025** [comment]
Just did and still failing. You are on mboost version 2.7? Maybe this is just my computer

**Comment by larskotthoff** [comment]
Yep, just updated.

**Comment by Stevo15025** [comment]
Yay! Success! I guess it is my machine that has a problem with mboost 

Does this all look okay?

**Comment by larskotthoff** [comment]
Thanks, just a few style things:
- space after function parentheses and opening brace
- no need for `BBmisc::` in front of functions
- don't assign something to a variable and then not do anything with it (in the function to get the hyperparameters)

For the hyperparameters, you can even just declare them globally in the file; no need for a function.

Now remind me, this is only needed for the forecasting branch, isn't it? Is that branch ready to be merged? Otherwise I would hold off merging this.

**Comment by Stevo15025** [comment]
Sounds good I'll make these fixes when I get home.

Has anyone reviewed the forecasting branch? I probably need to go and make these style changes in the forecasting branch. Also there are some places I would like people to look over. createLagDiff is pretty messy, but it was the only way I could find to perform one step ahead forecasts with machine learning models. Though I may rewrite it this weekend so that it uses data.table instead of xts. 

This is for the forecasting branch, however the MAX_NUM_DLL error is probably going to arise for the next branch to include a new numeric learner.

**Comment by Stevo15025** [comment]
I also need to make the tutorial fit the mlr tutorial style

**Comment by Stevo15025** [comment]
I'm not sure why, but placing the hyperpars in the test file does not let the hyperpars pass to the test. Which is odd because the global environment should pass to the test (for example `binaryclass.task` does pass through)

**Comment by larskotthoff** [comment]
Ah, you may have to put them into one of the helper files which are always sourced.

**Comment by Stevo15025** [comment]
> Ah, you may have to put them into one of the helper files which are always sourced.

I tried placing hyperpars outside of a function in 88e2d51 but it failed (?!). While not ideal, throwing the hyperpars into a function inside of `helper_learners_all` is not too bad

**Comment by Stevo15025** [comment]
This is all good to go, after review. This is just to break up the classifer tests that were failing in the forecast package until R 3.4 comes out. Then we can set the maximum number of DLLs in jenkins and travis

**Comment by larskotthoff** [comment]
Hmm, we talked about this a bit and are actually tempted to just wait until 3.4 comes out. This avoids merging something now and then reverting it later.

Do you need the forecasting stuff merged before then? That would be the only reason to pull this in.

**Comment by Stevo15025** [comment]
Ehhhh

Would I _like_ forecasting to be merged before 3.4? Ya. 

Will I keel over if it doesn't happen in the next month? I think I'll live.

 that's reasonable, it can wait

**Comment by larskotthoff** [comment]
Ok, let's see when we can review the PR first.

**Pull request closed without merging**
