### PR TITLE
Remove unnecessary ggplot2:: calls

### PR DESCRIPTION
**Pull request by MasonGallo**
I noticed some `ggplot2::` calls which shouldn't be necessary since it's already imported.

- [x] check passed
- [x] base tests passed

### CODE REVIEW

**Comment by catastrophic-failure** [comment]
Is it good practice though? Genuinely asking.

**Comment by zmjones** [comment]
I mean R's namespace management is just not great generally. I think we are avoiding this by only importing a few packages. I agree that using `::` isn't necessarily bad, but for ggplot2 it gets very tedious.

**Comment by MasonGallo** [comment]
Agreed with @zmjones. 

@catastrophic-failure I'm not sure what you mean in the edit? I don't think that should be an issue for ggplot2. In this case we have already imported ggplot and shouldn't have any namespace issues (not to mention we call just ggplot elsewhere in the codebase).

**Comment by larskotthoff** [comment]
I think @catastrophic-failure means that there could be issues if another package has functions of the same name as the ggplot functions. Yes, this is possible, but unlikely as it would break things for pretty much everybody else as well.

Merging, thanks.

**Pull request merged**
