### PR TITLE
fix bug in irace with unnamed discrete values, fixes #627

### LINKED ISSUE #627: tuneParams using IRace fails with discrete parameters that are not character
`tuneIrace()` calls `ParamHelpers::convertParamSetToIrace()` which converts discrete parameters into discrete *character* parameters using the *names()* of the parameter `$values`. However, the fitness function (`hookRun` in tuneIrace.R) makes no effort translating from names back to parameter values (it *does* translate logical parameters though).

This works fine, as long as the discrete parameter `values` vector is of mode character for which names equal values (default when created using `makeDiscreteParam()`); in other cases it causes errors:
```R
> lrn = makeLearner("classif.randomForest")
> ctrl = makeTuneControlIrace(maxExperiments = 200L)
> ps = makeParamSet(makeDiscreteParam("ntree", c(100, 200))) # !! create discrete numeric param
> tuneParams(lrn, iris.task, rdesc, par.set = ps, control = ctrl)
[Tune] Started tuning learner classif.randomForest for parameter set:
          Type len Def  Constr Req Tunable Trafo
ntree discrete   -   - 100,200   -    TRUE     -
With control class: TuneControlIrace
Imputation value: 1
[Tune-x] Setting hyperpars failed: Error in setHyperPars2.Learner(learner, insert(par.vals, args)) :
  100 is not feasible for parameter 'ntree'!

Error in getIndex(par$values, x) : Value not found!
```
(The error message is a bit misleading: the parameter value that IRace tries to set for ntree is the **character** "100", it should be the **numeric** 100. Consider:
```R
> lrn = makeLearner("classif.randomForest")
> ctrl = makeTuneControlIrace(maxExperiments = 200L)
> ps = makeParamSet(makeDiscreteParam("ntree", c(name100=100, name200=200)))
> tuneParams(lrn, iris.task, rdesc, par.set = ps, control = ctrl)
[Tune] Started tuning learner classif.randomForest for parameter set:
          Type len Def          Constr Req Tunable Trafo
ntree discrete   -   - name100,name200   -    TRUE     -
With control class: TuneControlIrace
Imputation value: 1
[Tune-x] Setting hyperpars failed: Error in setHyperPars2.Learner(learner, insert(par.vals, args)) :
  name100 is not feasible for parameter 'ntree'!

Error in getIndex(par$values, x) : Value not found!
```
)

### PR DESCRIPTION
**Pull request by berndbischl**
I did the following:

- I improved the conversion code for irace. 
- I added a new option in ParamHelpers so, we now rely on version 1.7 for this
- I removed a convertX function, which was only there for irace and is not needed now

### CODE REVIEW

**Comment by berndbischl** [comment]
no idea why we have a conflict now. but please review first. maybe we have to rebase on master

**Comment by larskotthoff** [comment]
Looks good, happy to merge when the conflicts are fixed.

**Comment by berndbischl** [comment]
Hey, to Zach you said if it would be in a branch you would do it....!

**Comment by larskotthoff** [comment]
But he doesn't bombard us with 10 PRs at once ;)

**Pull request merged**
