### PR TITLE
fixes parallelization bug in generatePartialPredictionData

### PR DESCRIPTION
**Pull request by zmjones**
- adds test

### CODE REVIEW

**Comment by berndbischl** [comment]
Thx.
parallelMap is in mlr IMPORTS. do not state parallelMap:: in these cases, pls. Just makes code longer without necessity.

**Comment by berndbischl** [comment]
This is always a matter of confusion.
For only SUGGESTED packages, on must use ::.

Should we note this in the contributor guidelines?

**Comment by zmjones** [comment]
Yes I will do that.

**Comment by larskotthoff** [comment]
Thanks, merging.

**Pull request merged**
