### PR TITLE
Fix tests for R 3.6.0

### PR DESCRIPTION
**Pull request by pat-s**
# Test related changes

- `testthat::expect_vector()` replaced by `checkmate::expect_atomic_vector() ` since `testthat::expect_vector()` now depends on `vctrs`
- for `tests/testthat/test_base_spcv.R` I changed the learner
- `expect_true()` checks throwed a correct "coercion > 1" error (I think there is an automated checking now in R 3.6.0) -> split them into two lines and wrapped them in `all()`
- All tests are now using the old R < 3.6.0 seed (set in the `run_*.R` files in the `testthat` directory`

    ```r
  if (getRversion() > "3.5.3") {
    # set old seed
    suppressWarnings(RNGversion("3.5.0"))
    # restore standard seed when done (so that we are back to defaults for the next tests)
    on.exit(suppressWarnings(RNGversion("3.6.0")))
  }
    ```

# General

- We are now building for 3 R versions in parallel to catch such issues in advance in the future
   - devel
   - release
   - oldrel
- RWeka warning caused by Java 9+ has been silenced using `_Java_options` env var

### CODE REVIEW

**Comment by larskotthoff** [comment]
Travis is still failing unfortunately...

**Comment by pat-s** [comment]
Well, strange Travis. [This](https://travis-ci.org/mlr-org/mlr/builds/530750487) build passed. Have to make some changes anyway, we'll see.

**Comment by pat-s** [comment]
> Well, strange Travis. This build passed. Have to make some changes anyway, we'll see.

Ah in the linked build I still installed Weka via the old approach. Let's see if installing in the "script" stage helps.

**Comment by larskotthoff** [comment]
Thanks @pat-s !

**Pull request merged**
