### PR TITLE
BMR hypothesis tests and plots from pfistfl

### PR DESCRIPTION
**Pull request by zmjones**
this is a rebased and cleaned version of #343

it is not ready to be merged, though all the tests/check are passing.

when it is ready to be merged i'd like to change the author of the commit back to @pfistfl

@pfistfl please check that all the plots still do what the are supposed to, the structure still makes sense to you, etc.

if you already know how to do this sorry. create a new local branch, and then pull from this branch (zmjones/bmr-hypo). then you can play around with it. if you then push to your fork you can issue a pr for my pr.

### CODE REVIEW

**Comment by zmjones** [comment]
also if anyone has git advice about how i should have done this easier let me know. 

i created a local branch based of a current version of master. then i pulled in the branch from the old pr, and cleaned and modified it until i could merge it cleanly. this doesn't give the original author any credit though which bothered me a bit.

**Comment by larskotthoff** [comment]
I would have cloned the repo the PR came from (i.e. @pfistfl's) and submitted a PR for that.

**Comment by zmjones** [comment]
Ok so I started to do that but I either had to work off of his master, which was 150 commits behind, or issue a PR with 150 commits in it.

**Comment by larskotthoff** [comment]
I would have done the latter :)

**Comment by zmjones** [comment]
I guess there is no reason I couldn't do the latter. In this case would you clone his repo/branch, rebase of mlr-org/master, make changes, and then send a PR to him. Would this follow with him merging it? And then when it gets merged into master someone else squashes everything?

**Comment by larskotthoff** [comment]
Ideally he would then squash everything into a single commit that adds all the stuff to be merged into master.

**Comment by zmjones** [comment]
Right, but I think the purpose of me reviewing this, other than being the "plot" guy, was to make the git side of things easier for him. Could be wrong on that though.

Would you prefer I redo-things your way? I think I'll wait to see what he says about what I did either way. I think I'd like to expand the plot/generate functions a bit, and add ggvis versions. Specifically they are set up now to only handle one measure, when you can pass an arbitrary number to create the BenchmarkResult object.

**Comment by larskotthoff** [comment]
No, it's fine as it is. As you say, the only problem is the attribution -- up to the original author to decide what he wants to do. But please wait until this has found its way into the main repo before expanding.

**Comment by zmjones** [comment]
Ok. I found [this](http://stackoverflow.com/questions/3042437/change-commit-author-at-one-specific-commit) which is what I was going to do.

**Comment by pfistfl** [comment]
Hey, 
I just installed your repo's branch via install_github and ran a few tests on this.

I found a few bugs / suboptimal plots. Shall I fix them and issue a PR or just tell you here ?

**Comment by pfistfl** [comment]
Gonna post it here, anyway:
# plotCritDifferences for test = nemenyi: IF $cd.info$nemenyi.data is empty do not fail!, this 
# just means there are no groups of NOT significantly different ones, or no bars to plot.
# plotBenchmarkSummary -> Alpha legend does not make sense!
# plotBenchmarkResult -> Option to remove facet_wrap(), or is there an elegant way in ggplot?
#                        Maybe: Mention such a method in help
#                        Or: Option to subset measures
# plotBenchmarkResult typo in help @param style  "]" too much.
# plotBenchmarkResult @param [measures] still in help but not used anymore.
# plotBenchmarkResult style violin -> what's with the weird medians, seem to be bugged by facet_wrap

**Comment by zmjones** [comment]
I will just fix them here. Just woke up and will start in a little bit.

**Comment by pfistfl** [comment]
I tried to include the critical differences plot into my thesis today and found that the learner.id labels are way to small event at super high dpi.
Do you have an idea how we could either dynamically scale them or give an option?

They are often too long aswell, but that is something that can be changed in the plot data.

**Comment by zmjones** [comment]
Ok I just removed the facetting in `plotBenchmarkResult`. I will go back and mess with that after this is merged.

For `plotBenchmarkSummary` should there be an alpha legend? Before you had mapped the alpha aesthetic to alpha in the plot data, but there was no legend for it in the plot.

Ok for `plotCritDifferences` with `test = "nemenyi"` where is the problem induced? I didn't change any of that code, just formatting and so on.

For `plotCritDifferences`, you are talking about this line I assume. 

```  p = p + geom_text(aes_string("xtext", "yend", label = "learner.id", color = "learner.id"), vjust = -1)```

On my local machine it is pretty large. Can you show me an example where it is a problem?

**Comment by zmjones** [comment]
I went back to the lack of an alpha scale for `plotBenchmarkSummary`. Can you explain to me why that makes sense though?

I renamed some files (the ones with generation functions) which I forgot to do before.

I wrapped the block of code in plotCritDifferences with test = "nemenyi" to just skip if that part of the object is empty. Is that what you wanted?

Let me know if this solves all your issues except for the latest one with `plotCritDifferences`.

**Comment by pfistfl** [comment]
>I went back to the lack of an alpha scale for plotBenchmarkSummary. Can you explain to me why that makes sense though? 
>> It indicates a fill, the alpha = 0.4 just fills up the bars to whole again, so the user can distinguish.
     So for this it would make sense to keep the plot as is and just remove the legend.

> wrapped the block of code in plotCritDifferences with test = "nemenyi" to just skip if that part of the object is empty. Is that what you wanted?
>>>Perfect, this problem just did not turn up before.

> Ok I just removed the facetting in plotBenchmarkResult. I will go back and mess with that after this is merged.
>> I really liked the faceting, its just if your BenchmarkResults get bigger (8+ tasks / learners) it           becomes really messy I guess....
>> Maybe we could add an option to select a measure... and then no faceting is done.

> For plotCritDifferences, you are talking about this line I assume.
  p = p + geom_text(aes_string("xtext", "yend", label = "learner.id", color = "learner.id"), vjust = -1)
  On my local machine it is pretty large. Can you show me an example where it is a problem?
>>  See example here:
critdiffs

>> The idea for this plot was that it could easily be put into any form of publication ,
    as it should be  very space friendly. 
     I just never realized that it does not scale very well when putting it onto A4 size.

**Comment by zmjones** [comment]
Ok cool. Lets not expand `plotBenchmarkResult` yet. I think the next thing you should do is add this to the tutorial. Then you or I can go about adding functionality. 

So for the `plotCritDifferences` font size issue I am not sure I see the problem with the actual plot, just with the resolution you are outputting it at. You should try smaller dimensions.

@berndbischl is it cool if I go ahead and merge this?

**Comment by berndbischl** [comment]
> is it cool if I go ahead and merge this?

Yes. Sure. We can improve later.
Just do me this favor: See if you can add 1-2 unit tests (only if they really make sense and have been forgotten, no artificial bloat because if my post here).
And check 1-2 example by hand and see if the plots make sense.

**Comment by berndbischl** [comment]
And you could also do this after the merge.

**Comment by zmjones** [comment]
@pfistfl has some unit tests in there, and we both have done some examples interactively. if he can double check this though that would be nice. then i will give him ownership of the commit and merge.

**Comment by berndbischl** [comment]
@both:
Ok do that please. Merge and check a bit more if you think this helps.

**Comment by berndbischl** [comment]
@pfistfl 
finished with the checks? can we merge?

**Comment by zmjones** [comment]
I haven't talked with him yet.

**Comment by pfistfl** [comment]
@both
Hey, I have not gotten around to test, but I tested @zmjones original branch extensively. 
If the issues I brought up are fixed, I'm fine. 
I guess I will not get around to test for the next days, as I am not at home currently.

So for me it's fine.

**Pull request merged**
