### PR TITLE
test for issue 279 (closes #279)

### LINKED ISSUE #279: Error in hyperparameter tuning with scientific notation for lower/upper boundaries
Within hyperparameter tuning I ran into several errors when using scientific notation for lower (or upper) tuning boundaries. Probably the error occurs because of a rounding error!?

example 1:
```R
library(mlr)
lrn = makeLearner("classif.gbm", predict.type = "prob")

ps = makeParamSet(makeNumericParam("shrinkage", lower = 1e-5, upper = 1e-4))
ctrl = makeTuneControlIrace(maxExperiments = 300L)
rdesc = makeResampleDesc(method = "Holdout")
lrn.tune = makeTuneWrapper(lrn, resampling = rdesc, par.set = ps, 
  control = ctrl, measure = list(mmce))

set.seed(123)
res = resample(lrn.tune, task = sonar.task, rdesc, measures = list(mmce))
```

throws error:
```R
Trying to add infeasible x values to opt path: shrinkage=0
```

---
example 2: 
```R
library(mlr)
lrn = makeLearner("classif.logreg")
lrn2 = makeUndersampleWrapper(lrn, usw.rate = 1)

ps = makeParamSet(makeNumericParam("usw.rate", lower = 2.91e-3, upper = 0.003))
ctrl = makeTuneControlIrace(maxExperiments = 100L)
rdesc = makeResampleDesc(method = "Holdout")
lrn.tune = makeTuneWrapper(lrn2, resampling = rdesc, par.set = ps, 
  control = ctrl, measure = list(mmce))

set.seed(123)
res = resample(lrn.tune, task = sonar.task, rdesc, measures = list(mmce))
```

throws error: 
```
Trying to add infeasible x values to opt path: usw.rate=0.0029
```

I'm currently using mlr version 2.3.

### PR DESCRIPTION
**Pull request by larskotthoff**

### CODE REVIEW

**Comment by berndbischl** [comment]
looks good thx

**Comment by jakob-r** [comment]
Is that really a good name for a test?

**Comment by berndbischl** [comment]
@jakob-r 
No it isnt, we will change now

**Comment by berndbischl** [comment]
through yout review i have now noticed that we already seem to have a similar test in the same file, further above?
we need to watch out for this, so we dont duplicate. lars is checking now.

**Pull request merged**
