### PR TITLE
fixes plotting issues in #699 and #700

### PR DESCRIPTION
**Pull request by zmjones**

### CODE REVIEW

**Comment by schiffner** [comment]
Thank you very, very much for the quick fixes!!!
I installed this branch and all the tutorial examples run fine now.

Regarding #699 I noticed 2 mini things:

The axis labels in the case `pretty.names = FALSE` are not ok.
I guess the `obj$` in this line has to be removed, too:
https://github.com/zmjones/mlr/commit/82170df59302cb8bee14912c5265e47adba6d404#diff-51ee01993c76107746e819bd80050f89R371

In the docs of `plotROCCurves` there is a bracket missing:
https://github.com/zmjones/mlr/commit/82170df59302cb8bee14912c5265e47adba6d404#diff-51ee01993c76107746e819bd80050f89R329

Regarding #700 everything works fine.

**Comment by zmjones** [comment]
thanks for checking it again, should be fixed now. i removed the bracket, unless you think the link to Measure should be bracketed. that did look consistent with how it is documented in arg_measures.R.

**Comment by schiffner** [comment]
Thank you very much again and sorry that it took me a while to respond.

> i removed the bracket, unless you think the link to Measure should be bracketed. that did look consistent with how it is documented in arg_measures.R.

Really sorry to bother you with this, but the style guide is in favor of brackets. As far as I see
[arg_measures.R](https://github.com/mlr-org/mlr/blob/master/man-roxygen/arg_measures.R) has them, too. How about something like `[\code{list(2)} of \code{\link{Measure}}]\cr  all further explanations ...` ?

The only things open in my opinion are:
* The NA problem (https://github.com/mlr-org/mlr/issues/699#issuecomment-181937951), but there is no rush.
* Probably tests, but that does't seem to be easy and can also be done later.

@berndbischl: Is it ok if I merge once this is ready? Or does it interfere with the release?

**Comment by zmjones** [comment]
No worries of course and it is no bother! I agree with you on the docs and I just pushed that change.

Further testing is on my list. The SVG tests would have caught this. I don't remember if you were on the hangout when we discussed it but @larskotthoff and I thought that the best thing to do would be to extract the default colors from the ggplot default theme, turn those into html color codes, and then insert those into the tests, rather than the hard-coded html color codes that are in there now (and broke with the latest ggplot2 release). However it is probably the case that they won't change again, so maybe this is much ado about nothing.

I forgot about the NA thing and will look into that now.

**Comment by zmjones** [comment]
That is fixed now too,

**Comment by berndbischl** [comment]
I will merge this in now.

- Can you close some of the issues that were dealt with here? If mini-points remain open, open up new precise ones. 

- Zach, can you please get together with Lars so we have tests again? this seems to become a problem,

**Comment by schiffner** [comment]
@zmjones : Very cool, thank you so much.

@berndbischl : Both 699 and 700 are fixed completely, I will close them.

**Pull request merged**
