### PR TITLE
provide defaults for additional arguments for univariate filter

### LINKED ISSUE #516: Using univariate filter in makeFilterWrapper() or filterFeature() results in checkLearner(perf.learner) error
I get this error when using the `univariate` filter in `makeFilterWrapper()` or `filterFeature()`:
```{r}
Error in checkLearner(perf.learner) :
  argument "perf.learner" is missing, with no default
```

**Input:**
```{r}
library(mlr)
sessionInfo()
set.seed(16)

dat <- data.frame(replicate(2500, sample(0:1, 500, rep=TRUE)))
classif.task <- makeClassifTask(id="test", data=dat, target="X1")
lrn <- makeLearner("classif.svm")
lrn <- makeFilterWrapper(lrn, fw.method="univariate", fw.perc=0.1)
mod1 <- train(lrn, classif.task)
```

**Output:**
```{r}
$ R --vanilla

R version 3.2.2 (2015-08-14) -- "Fire Safety"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> source("mlr-test.R", echo=TRUE)

> library(mlr)
Loading required package: BBmisc
Loading required package: ggplot2
Need help? Try the ggplot2 mailing list: http://groups.google.com/group/ggplot2.
Loading required package: ParamHelpers

> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.6 (Santiago)

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=C
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=C
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] mlr_2.4          ParamHelpers_1.5 ggplot2_1.0.1    BBmisc_1.9

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.1      digest_0.6.8     MASS_7.3-43      grid_3.2.2
 [5] plyr_1.8.3       gtable_0.1.2     magrittr_1.5     scales_0.3.0
 [9] stringi_0.5-5    reshape2_1.4.1   parallelMap_1.3  checkmate_1.6.2
[13] splines_3.2.2    proto_0.3-10     tools_3.2.2      stringr_1.0.0
[17] munsell_0.4.2    survival_2.38-3  parallel_3.2.2   colorspace_1.2-6

> set.seed(16)

> dat <- data.frame(replicate(2500, sample(0:1, 500, rep=TRUE)))

> classif.task <- makeClassifTask(id="test", data=dat, target="X1")

> lrn <- makeLearner("classif.svm")

> lrn <- makeFilterWrapper(lrn, fw.method="univariate", fw.perc=0.1)

> mod1 <- train(lrn, classif.task)
Error in checkLearner(perf.learner) :
  argument "perf.learner" is missing, with no default
Timing stopped at: 0.129 0 0.129
```

Thank you!

### PR DESCRIPTION
**Pull request by larskotthoff**
Fixes #516.

### CODE REVIEW

**Comment by berndbischl** [comment]
see my response in the issue thread

**Comment by berndbischl** [comment]
sorry....
- you missed to remove a print there
- the documentation note is still not long enough. nobody will understand. 
- i dislike your use of the base learner. it is undocumented, also not that intuitive to me. IMHO: rpart as a default, the rest is the users choice. also: how can that setting be empty, now that you HAVE rpart as a default?

**Comment by larskotthoff** [comment]
Sorry about the print. Where should I document this? In the description? That will get very long.

I don't see your concern about the filter wrapper -- if I wrap a learner with a feature selection that uses a learner, I would expect the two learners to be the same. E.g. it doesn't really make sense to have an SVM and do the feature selection with rpart.

**Comment by berndbischl** [comment]
1) We should probably have a true R doc page for details. But for the desc: Who cares if its 2-3 lines. I would write: "Resamples an mlr learner for each input feature individually, so on 1dim input data. The resampling performance is used as filter score. (rpart is default learner).

**Comment by berndbischl** [comment]
2) I heavily disagree what you write about both learners having to be same. The learners are used in VERY different ways. I would have no problems of mixing 2 different ones. Technically, I dislike that this is done behind the users back. If you want to doc it (min requirement), it only further complicates things. 
If you really want to align the two learners, you can always do this by choice.

**Comment by larskotthoff** [comment]
Ok, I've fixed those things.

**Comment by berndbischl** [comment]
I could merge this now, for 2.5. Shall I?

**Comment by larskotthoff** [comment]
Fine with me. I only saw that you had labelled the issue with 2.6, so I did the same for the PR.

**Comment by berndbischl** [comment]
I will merge this now and update news

**Pull request merged**
