### PR TITLE
fixes related to #713

### PR DESCRIPTION
**Pull request by zmjones**
one additional bug I discovered in testing #713, one cleanup commit, and one for the actual issue

`rcheck` failed locally due to a Caret error I couldn't figure out.

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks. Looks good, but could you also please add unit tests for this stuff?

**Comment by zmjones** [comment]
All the bugs were in the ggvis functions.

**Comment by berndbischl** [comment]
I dont want to nitpick:

1) I am guessing this fixes everything in the issue (except for the shinyapp demos)?

2) This we could indeed unit test now. 
```
+  if (!obj$interaction & !is.null(interact))
 +    stop("generatePartialPredictionData was called with interaction = FALSE!")
```
3) Can you squash at the end pls?

4) thx!

**Comment by zmjones** [comment]
yea sure i can. i just thought it made sense to have 3 since each was sort of a separate thing. only the part you mention was really related to the issue.

**Comment by berndbischl** [comment]
you dont have to squash in that case, but in general I would like to have not so many commits per single "thing". can you also add the test please, then we can close

**Comment by larskotthoff** [comment]
Ping @zmjones

**Comment by zmjones** [comment]
sorry have been crazy busy! rebased off master and squashed into one commit now.

**Comment by larskotthoff** [comment]
Thanks! Could you add a test as well please?

**Comment by zmjones** [comment]
All the bugs were in the ggvis functions

**Comment by larskotthoff** [comment]
Ok, thanks. I'll go ahead and merge this then as soon as the Jenkins tests for the previous merge are done.

**Pull request merged**
