### PR TITLE
fix for #1141

### PR DESCRIPTION
**Pull request by zmjones**
use significant digits for numeric type facet variables in plotPartialDependence

### CODE REVIEW

**Comment by larskotthoff** [comment]
Sorry, master with families was broken. I've rebased the branch.

**Comment by zmjones** [comment]
ah thanks

**Comment by larskotthoff** [comment]
Hmm, you're assuming that it's a number in the else branch. Could you check this explicitly please, or are there disadvantages to doing so?

**Comment by zmjones** [comment]
No disadvantages other than a little bloat but I don't see why it is necessary really. If it isn't a factor or character type then it is a numeric. i think this is enforced by either the task creation or by the assertdataframe in this generationPartialDependenceData when either a task or a dataframe is passed as input.

**Comment by larskotthoff** [comment]
You could create a task without checking, then it wouldn't be checked in `generatePartialDependenceData` either. I know that the chances of this happening are every small, but if it does happen it'll lead to hard-to-debug bugs.

**Comment by zmjones** [comment]
ok i'll change that then.

i apparently have lost my jenkins login. so i can't see what that build failed.

**Comment by larskotthoff** [comment]
That's something unrelated (fixed in #1162). Don't worry about that.

If you can't find your Jenkins password, email me and I'll reset it :)

**Comment by larskotthoff** [comment]
It looks like you didn't pull my master rebase. Could you rebase on master again please?

**Comment by zmjones** [comment]
yep.

**Comment by larskotthoff** [comment]
Ok thanks, I'll merge this. I'll open an issue for making this configurable for plots in general.

**Pull request merged**
