### PR TITLE
fix compatibility for caret_6.0-57

### PR DESCRIPTION
**Pull request by larskotthoff**

### CODE REVIEW

**Comment by berndbischl** [comment]
if you do stuff like this you need to increase the required version in DESCRIPTION

**Comment by berndbischl** [comment]
i will do this after the merge

**Comment by schiffner** [comment]
Are you really sure that caret changed the defaults of `preProcess` in version 6.0-57? As far as I can see centering and scaling have been the default for at least a year. So we don't need to change the required version because of the defaults.

Anyhow, increasing the required version might be a good idea because the improved handling of non-numeric variables in `preProcess`. (See https://github.com/mlr-org/mlr/issues/408)

**Comment by berndbischl** [comment]
Ok, I am not sure and did not double check this. Maybe Lars should comment on this and I will wait

**Comment by larskotthoff** [comment]
So caret doesn't have any kind of useful changelog or NEWS or even commit messages. With the current implementation, no methods get selected by default and that fails with an error message. I don't know what they actually changed or why, but adding the defaults listed in the man page fixes the problem.

**Comment by berndbischl** [comment]
after talking to lars I will merge this now

**Pull request merged**
