### PR TITLE
Feature importance for h2o learners

### PR DESCRIPTION
**Pull request by markusdumke**
Relates to #2433

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks, looks good! Could you add a test for this please?

**Comment by pat-s** [comment]
@markusdumke Could you add a test please? Then we can merge this. Or at least allow edits from maintainers so we have a chance to do so :)

**Comment by markusdumke** [comment]
@pat-s I have added a test, so I think it can be merged now.

**Comment by larskotthoff** [comment]
Thanks, looks good -- merging.

**Pull request merged**
