### PR TITLE
Test that all learner can handle only one feature!

### PR DESCRIPTION
**Pull request by jakob-r**
Spotted a bug in GPfit. Added general tests for regr and classif

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks. Looks like we should have tests for the SE -- do you think it would be feasible to add tests for this to this PR?

**Comment by jakob-r** [comment]
How to test it? What are acceptable boundaries for SE values? Or do I calculate the SE for all supported learners on a test dataset and then throw an error for outliers?

**Comment by larskotthoff** [comment]
I would construct a small dataset and make sure that the SE predictions are numbers and not unreasonably large (e.g. larger than the range of values).

**Comment by jakob-r** [comment]
@larskotthoff What do you say to the added test?

**Comment by larskotthoff** [comment]
Looks good, thanks!

**Pull request merged**
