### PR TITLE
run all examples in travis

### PR DESCRIPTION
**Pull request by larskotthoff**

### CODE REVIEW

**Comment by larskotthoff** [comment]
Ok, this fails because Travis doesn't get enough output. Closing.

**Comment by berndbischl** [comment]
lars what are you doing here? we should run "dont run"?

**Comment by larskotthoff** [comment]
That doesn't work in Travis (and was disabled). I tried enabling it, but it doesn't produce enough output for Travis.

**Comment by berndbischl** [comment]
we discussed this, the result was this issue #989 
we are done here

**Pull request closed without merging**
