### PR TITLE
#1450: Fix glmnet.control

### PR DESCRIPTION
**Pull request by MariaErdmann**
PR for issue #1450.
set `glmnet::glmnet.control(factory = TRUE)` before setting control params of mlr and set it back on.exit.
Deleted param `factory` from param set.
Adapted the tests accordingly.

### CODE REVIEW

**Comment by MariaErdmann** [comment]
Resovles also bugs listed in #1370.

**Comment by larskotthoff** [comment]
Thanks, looks good. Could you document the parameter reset in the learner notes please?

**Comment by MariaErdmann** [comment]
Something like: "All control parameters are set to glmnet's factory default before and after training, change of control parameters by setting the learner's parameters"?
Or only the firest part (but that might sound like, that the user cannot set the control parameters)

**Comment by larskotthoff** [comment]
I would phrase it like this:

"glmnet uses a global control object for its parameters. mlr resets all parameters to their defaults before setting the specified parameters and after training. If you are setting glmnet parameters through glmnet.control, you need to save and re-set them after running the a glmnet learner."

**Comment by MariaErdmann** [comment]
Do we have any conventions on how the note should look like? (Couldn't find anything in the wiki) The note part in the glmet learners got quite lengthy and it does not look very nice.
````
makeLearner("regr.glmnet")$note
````
Or is there another way of getting the note (e.g. a getter function? i couldn't find any...)

**Comment by MariaErdmann** [comment]
I don't know why the tests are failing... locally the test test_learners_all_surv runs without throwing error messages.

**Comment by larskotthoff** [comment]
Note looks good to me.

I see these failures in the logs:

```
1. Failure: learners work: surv  (@test_learners_all_surv.R#15) ----------------
!is.na(performance(pred = p, task = task)) isn't true.
surv.penalized.fusedlasso

2. Failure: learners work: surv  (@test_learners_all_surv.R#15) ----------------
!is.na(performance(pred = p, task = task)) isn't true.
surv.penalized.lasso

3. Failure: learners work: surv  (@test_learners_all_surv.R#15) ----------------
!is.na(performance(pred = p, task = task)) isn't true.
surv.penalized.ridge

4. Failure: learners work: surv  (@test_learners_all_surv.R#19) ----------------
!is.na(performance(pred = p, task = task)) isn't true.
surv.penalized.fusedlasso

5. Failure: learners work: surv  (@test_learners_all_surv.R#19) ----------------
!is.na(performance(pred = p, task = task)) isn't true.
surv.penalized.lasso

6. Failure: learners work: surv  (@test_learners_all_surv.R#19) ----------------
!is.na(performance(pred = p, task = task)) isn't true.
surv.penalized.ridge

7. Failure: learners work: surv  (@test_learners_all_surv.R#23) ----------------
!is.na(performance(pred = p, task = task)) isn't true.
surv.penalized.fusedlasso

8. Failure: learners work: surv  (@test_learners_all_surv.R#23) ----------------
!is.na(performance(pred = p, task = task)) isn't true.
surv.penalized.lasso

9. Failure: learners work: surv  (@test_learners_all_surv.R#23) ----------------
!is.na(performance(pred = p, task = task)) isn't true.
surv.penalized.ridge
```

Do you have the latest version of all packages locally?

**Comment by berndbischl** [comment]
> Or is there another way of getting the note (e.g. a getter function? i couldn't find any...)

please open an issue for this, a getter is a  good idea

> Do we have any conventions on how the note should look like? (Couldn't find anything in the wiki) The note part in the glmet learners got quite lengthy and it does not look very nice.

please also lets have an issue and define this a bit better. i agree that currently your note looks ok.
what should be in the note: 
a) if we change stuff from the "default behavior" of the learner
b) if mlr adds new options to the learner
c) if we know of really severe problems

what should not be in the learner:
- normal, lengthy explaining documentation. an example is regr.randomForest. for that we have our own se-estimators. the note should possible say that, very briefly, but then should refer to ?regr.randomForest, which documents all the background on this separate page.

@larskotthoff @mllg 
makes sense?

**Comment by larskotthoff** [comment]
Agreed.

**Comment by MariaErdmann** [comment]
Failure related to #1461.

**Comment by larskotthoff** [comment]
I'll hold off merging until the survival learners are fixed.

**Comment by mllg** [comment]
> who codes this stuff?

HTF ... :smile:

**Comment by berndbischl** [comment]
happy tree friends? (yeah i know)

**Pull request merged**
