### PR TITLE
Add faster filter functions using Rfast #1279

### PR DESCRIPTION
**Pull request by studerus**

### CODE REVIEW

**Comment by larskotthoff** [comment]
Hmm, looks like Travis is failing because gsl isn't installed and it won't allow it to be installed! @mllg do you have any ideas about this?

**Comment by mllg** [comment]
According to https://github.com/r-hub/sysreqsdb/blob/master/sysreqs/libgsl.json, you need to install libgsl0-dev. Should be whitelisted in https://github.com/travis-ci/apt-package-whitelist.

**Comment by larskotthoff** [comment]
Thanks @mllg. Now quickcheck doesn't install properly and fails the tests. I'll kick this off in a bit again to see if it's fixed.

**Comment by larskotthoff** [comment]
All good now, merging, Thanks.

**Pull request merged**
