### PR TITLE
Error in UseMethod("generateThreshVsPerfData") :    no applicable method for 'generateThreshVsPerfData' applied to an object of class "c('FeatSelModel', 'BaseWrapperModel', 'WrappedModel')"

### PR DESCRIPTION
**Pull request by vrgaliano**
I am trying to apply a ROC analysis from a learner of class FeatSelWrapper:

rdesc = makeResampleDesc("Bootstrap", iters = 100, predict = "both")
b632plus.mse = setAggregation(mse, b632plus)
lrn.rf = makeLearner("regr.randomForest",  ntree = 2500)
ctrl = makeFeatSelControlSequential(method = "sfs", alpha = 0.001)
lrn = makeFeatSelWrapper(lrn.rf, resampling = rdesc, measures = b632plus.mse, control = ctrl, show.info = TRUE)
rpart.sfs = train(lrn, task = regr.task)
df = generateThreshVsPerfData(rpart.sfs, measures = list(fpr, tpr, mmce))

### CODE REVIEW

**Comment by berndbischl** [comment]
hi, what goes on here? 
is this an issue or a PR?

and why do you talk about FeatSel / ROC in your post, but the committed files have something with multilabel in them?

**Comment by vrgaliano** [comment]
Hi, I am not sure about having understood your comments. It is an issue
when trying to apply a ROC analysis for a model built with feature
selection wrapper. I do not know what a PR is, sorry. I am working with
regression.

2017-07-26 13:05 GMT+02:00 Bernd Bischl <notifications@github.com>:

**Comment by berndbischl** [comment]
you have opened a pull request, which is a suggested change of the package

including code

**Comment by ja-thomas** [comment]
Hi,

we're closing here.

If you want to create a PR for multilable ROCcurves please do so with a correct name and description
If you have an issue as indicated in the title please open an Issue

**Pull request closed without merging**
