### PR TITLE
Add fregre learner and test file

### PR DESCRIPTION
**Pull request by NvNorsinski**
Here I added the fregre.glm learner from package fda.usc and the corresponding test script.

### CODE REVIEW

**Comment by pat-s** [comment]
#2716 

@pfistfl Appreciated if you could take a quite look if you find some time.

**Comment by pfistfl** [comment]
Hi, 

some thoughts on your problem: 
Do you aim to add this is to **mlr** or just as a script that you source before running your experiments?
In the former case, please move the tests to the `tests/testthat` folder.

1) I tested your code, and it seems to work fine if you do not parallelize.
    I would assume that it works fine if you add your new learner to mlr, install that package and source 
    it.
    Alternatively, try to `parallelSource` your learner.

2) You might want to add #' @export tags

If there is anything else, feel free to @ me again.

**Comment by NvNorsinski** [comment]
It should be a test. I rewrote it. The Problem is that the test fails. It looks to me like a numerical issue, because results of the original learner und mlr output differ at 6th place after decimal point.

**Comment by pat-s** [comment]
@NvNorsinski Do you want to finish this up here and maybe also add the classification pendant?

**Comment by NvNorsinski** [comment]
@pat-s I would like to finish the started work, but at the moment I have to organize my time. I think at the latest after finishing my thesis in march, I will try to finish this.

**Comment by pat-s** [comment]
@NvNorsinski Any updates?

**Pull request closed without merging**
