### PR TITLE
Rename expect_vector, name clash with new testthat

### PR DESCRIPTION
**Pull request by mllg**

### CODE REVIEW

**Comment by larskotthoff** [comment]
For some reason Travis keeps failing with errors that seem unrelated. Any idea what's going on?

**Comment by mllg** [comment]
The master branch also seems to fail, and I have no idea why.

**Comment by pat-s** [comment]
Could this be related to the recent `testthat` 2.1 release? 4 tests are failing, haven't taken a closer look yet.

**Comment by pat-s** [comment]
This change is already in master (c13c2b0f704a32d00800b01d297c0bd195a0e1d2), closing here.

**Pull request closed without merging**
