### PR TITLE
adding a getter for converting caret param set defaults to mlr

### PR DESCRIPTION
**Pull request by kerschke**
added a getter for the default param sets of caret, cf. issue #207 and PR #403

### CODE REVIEW

**Comment by larskotthoff** [comment]
So wait, why is this a separate PR? Shouldn't this be a part of #403?

**Comment by kerschke** [comment]
Just wanted to make sure that all changes are within the same commit - @berndbischl once mentioned that he prefers it this way, because it's easier to read. And if I would have changed something now afterwards and added it to the PR than there would be 2 commits, right?
Now, we can just close #403 and hopefully merge #404.

**Comment by berndbischl** [comment]
Ok, but then in general close the older PR when you make a new one. So we dont get confused.

**Comment by berndbischl** [comment]
I would like to give some feedback on stuff in the code, I can better do this on hangout

**Comment by kerschke** [comment]
So you would like to hangout now?

**Comment by berndbischl** [comment]
yup so i dont forget

**Comment by berndbischl** [comment]
and NEVER forget to update NEWS!

**Comment by kerschke** [comment]
Arghh.. that rebase and squash stuff is horrible.. apparently it's still considering the several commits. So I don't see the advantage. But probably I did something wrong..
Do you want a clean, single commit (then I would just put everything into a new PR) or can you live with it for this time?

**Pull request closed without merging**
