### PR TITLE
improve brier scaled doc and tests (fixes #1006)

### LINKED ISSUE #1006: clean up measure brier.sc code
see my comments in this PR #861

### PR DESCRIPTION
**Pull request by larskotthoff**
Rename, add documentation, improve tests as discussed.

### CODE REVIEW

**Comment by berndbischl** [comment]
measureBrier.scaled 

wrong naming convention. must be measureBrierScaled. Note that you just introduced an S3 function....

**Comment by larskotthoff** [comment]
Fixed.

**Comment by berndbischl** [comment]
i think my latest PH code change broke a test in mlr. i will try to fix this and then rebase this here.

**Comment by berndbischl** [comment]
*restart travis

**Comment by berndbischl** [comment]
actually a PH seems ok, a unit test in mlr was broken. i fixed this in master and rebased this here.

**Comment by berndbischl** [comment]
now you have given a wrong name to the object..... 

brierScaled ---> brier.scaled

one final try after that i give up and simply delete this branch ;-)

**Pull request merged**
