### PR TITLE
Repair ibrier wrapped model

### PR DESCRIPTION
**Pull request by PhilippPro**
Repair Issue #2265.

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks, merging.

**Comment by wzucl** [comment]
Hi, 

I tried to use ibrier measure in survival modelling in the mlr framework, I received the following errors. Here are my codes:

library(mlr)
library(survival)
library(data.table)
library(dplyr)
library(gbm)

data(lung, package = "survival")
lung$status = (lung$status == 2) ## convert to logical
nomissing_lung=lung[complete.cases(lung),]
surv.task = makeSurvTask(data = nomissing_lung, target = c("time", "status"))
n = nrow(nomissing_lung)
train.set = sample(n, size = 2/3*n)
test.set = setdiff(1:n, train.set)

model2 = train(lrn2, task = surv.task, subset = train.set)
pred2 = predict(model2, task = surv.task, subset = test.set)
result2=performance(pred2, measures = ibrier,task = surv.task, model=model2)

performance->iBrier (in measuers,R of MLR)
pec::predictSurvProb->riskRegression::predictCox, throw error
"Error in coxModelFrame.coxph(object) : invalid object 
set x=TRUE in the call to coxph "

To call riskRegression::predictCox it is mandatory to set X = True and Y = True

How do you set X=True and Y = True in the performance call? Do we need to change the interface of performance?

Best Regards

Wilbur Zhu

**Comment by PhilippPro** [comment]
The current version of ibrier is technically flawed at the moment, but we are working on it. 

But you can fix your error by setting the hyperparameter `x=TRUE`, when creating the lrn2 learner.

For example:
`lrn2 = makeLearner("surv.coxph", x = TRUE)`

**Comment by wzucl** [comment]
Thanks for your response.

I change to 
lrn2 = makeLearner("surv.coxph",x=TRUE,y=TRUE)

performance function throws the error:
Error in names(name.vars) <- names(formula)[-1] : 
  'names' attribute [3] must be the same length as the vector [2]
at at I:/src/riskRegression-master/riskRegression-master/R/getCoxInfo.R#844: names(name.vars) <- names(formula)[-1]

Regards

Wilbur

**Pull request merged**
