### PR TITLE
New measures squared log error and root squared log error

### PR DESCRIPTION
**Pull request by florianfendt**
Update for NEWS:

````
## measures - new
* msle
* rmsle
````

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks. Where did you get the definition for this? Given that the mean is taken, that should be reflected somewhere in the name (otherwise it's very similar to `sse`, but a different quantity).

**Comment by florianfendt** [comment]
@larskotthoff 
Here's where I found the definition for the measures:
https://www.kaggle.com/wiki/RootMeanSquaredLogarithmicError

I renamed measures to msle and rmsle and also adjusted the test according to your comment on Monday. Hope everything's ok now and thanks for your support!

**Comment by larskotthoff** [comment]
Thanks, looks good. Could you please add the link to the definition to the note please? And it looks like your tests are failing.

**Comment by florianfendt** [comment]
@larskotthoff 
I think we are done here now.
Thanks for your help!

**Comment by larskotthoff** [comment]
Thanks, merging.

**Pull request merged**
