### PR TITLE
Replace auc measure with a faster version

### PR DESCRIPTION
**Pull request by studerus**
A faster version of the auc measure with code borrowed from auc function of the MKmisc package

### CODE REVIEW

**Comment by larskotthoff** [comment]
Looks like this broke the multilabel tests.

**Comment by larskotthoff** [comment]
Is this ready to be merged now? And, just for the record, could you post a performance comparison between the current implementation and the one in this PR please?

**Comment by studerus** [comment]
Ok, here is a comparison on Windows 10, 32bit
```
library(mlr)
library(microbenchmark)
library(data.table)

pred = predict(train(makeLearner('classif.logreg', predict.type = 'prob'), pid.task), pid.task)
prob = getPredictionProbabilities(pred)
truth = getPredictionTruth(pred)

myAUC <- function(probabilities, truth, negative, positive) {
  if (is.factor(truth)) {
  	i = as.integer(truth) == which(levels(truth) == positive)
  } else {
	  i = truth == positive
  }
	if (length(unique(i)) < 2L) {
		stop("truth vector must have at least two classes")
	}
  y = probabilities[i]
  x = probabilities[!i]
  nx = as.numeric(length(x))
  ny = as.numeric(length(y))
  #Use fast ranking function from data.table for larger vectors
  if (length(i) > 10000L) {
  	r = frankv(c(x, y))
  } else {
  	r = rank(c(sort.int(x), sort.int(y)))
  }
  (nx * ny + nx * (nx + 1)/2 - sum(r[1:nx]))/(nx * ny)
}

for (i in 0:3) {
	prob.rep = rep(prob, 10^i)
	truth.rep = rep(truth, 10^i)
	cat('\n', 10^i, 'times the original size\n')
	print(microbenchmark(
        myAUC = myAUC(prob.rep, truth.rep, negative = 'neg', positive = 'pos'),
        mlr = measureAUC(prob.rep, truth.rep, negative = 'neg', positive = 'pos'),
        times = 10^(4 - i)))
}
```

```
 1 times the original size
Unit: microseconds
  expr     min      lq     mean  median      uq       max neval cld
 myAUC 134.596 146.032 157.8789 150.430 156.002  5247.175 10000  a 
   mlr 697.023 737.784 778.8259 750.979 770.626 13053.132 10000   b

 10 times the original size
Unit: milliseconds
  expr      min       lq     mean   median       uq       max neval cld
 myAUC 1.186728 1.248308 1.415155 1.270888 1.296985 78.089775  1000  a 
   mlr 4.122027 4.301633 4.513572 4.371131 4.468193  7.934395  1000   b

 100 times the original size
Unit: milliseconds
  expr       min        lq      mean    median       uq       max neval cld
 myAUC  6.046538  6.253857  7.961983  6.367779  8.69945  84.23572   100  a 
   mlr 44.740568 47.871895 50.501913 48.137860 48.68313 125.67855   100   b

 1000 times the original size
Unit: milliseconds
  expr       min        lq     mean    median       uq      max neval cld
 myAUC  84.62954  85.75439 110.3203  88.89965 160.6907 168.1580    10  a 
   mlr 630.50991 710.44532 752.5393 721.77320 783.2765 951.7605    10   b
```

**Comment by studerus** [comment]
You can merge it in my opinion.

**Comment by studerus** [comment]
Another speed comparison with the latest version
```
 1 times the original size
Unit: microseconds
  expr     min      lq     mean  median       uq       max neval cld
 myAUC 103.513 114.069 132.5902 117.881 121.4000 85459.103 10000  a 
   mlr 692.918 727.520 769.4275 741.889 761.5355  4346.353 10000   b

 10 times the original size
Unit: microseconds
  expr      min        lq      mean    median       uq       max neval cld
 myAUC  872.966  932.7855  986.7685  960.4965 1010.200  2946.148  1000  a 
   mlr 4128.771 4328.3185 4636.4259 4399.5745 4476.256 88569.757  1000   b

 100 times the original size
Unit: milliseconds
  expr       min        lq      mean    median        uq       max neval cld
 myAUC  5.589969  5.809603  8.195015  5.914582  6.224972  91.74873   100  a 
   mlr 47.252139 50.684179 53.167612 51.179749 52.805160 135.73744   100   b

 1000 times the original size
Unit: milliseconds
  expr       min       lq     mean    median        uq      max neval cld
 myAUC  76.43328  77.2042  88.2062  80.85016  81.81798 164.7485    10  a 
   mlr 642.81383 727.1375 756.7203 730.66427 735.45752 985.7968    10   b
```

**Comment by larskotthoff** [comment]
Thanks, merging.

**Pull request merged**
