### PR TITLE
update tests for soon-to-be-released ggplot2 version

### PR DESCRIPTION
**Pull request by larskotthoff**
This will fail at the moment, should be merged after the new ggplot2 version has been released.

### CODE REVIEW

**Comment by zmjones** [comment]
What is the "ns" bit?

**Comment by larskotthoff** [comment]
I was getting warnings about no namespace being specified for the query. This is what that does (i.e. map "svg" to the URL of the namespace if I understand correctly).

**Comment by berndbischl** [comment]
does anybody know the release date of ggplot2?

**Comment by larskotthoff** [comment]
Hadley and God, although I'm not sure about God.

**Comment by larskotthoff** [comment]
@zmjones Apparently ggplot doesn't support `vjust` in `annotation` anymore. I've removed this from `generateCritDifferences` to make the build pass again, but could you please check whether everything is still being shown correctly (and what to use instead of `vjust`)?

**Comment by berndbischl** [comment]
Yo, I saw this on travis too. I guess we should check it out at least briefly and document the results here.

**Comment by berndbischl** [comment]
As this is merged I will put this info in the ggplot2 issue in the tracker. We also really need to be able to run on rdevel.

**Pull request merged**
