### PR TITLE
#1144 better doc for measures

### PR DESCRIPTION
**Pull request by florianfendt**

### CODE REVIEW

**Comment by berndbischl** [comment]
@florianfendt 
if i have no further comments can this merged from your side?

**Comment by berndbischl** [comment]
medse and others with median: note does not do much, use simple formula, you can use "median" in the formula

acc, mmce: try to produce formula, like mean(response != truth)

ppv and other: why dont you use mlr's abbreviations in the formula to make it shorter. like not "number of false positives" but fp

**Comment by florianfendt** [comment]
@berndbischl
Adapted PR. Should be ok to merge from my side.
Don't really get why Travis fails, though. Error seems to be related to xgboost learner.

**Comment by larskotthoff** [comment]
@florianfendt Rebase on master and Travis should work again.

**Comment by florianfendt** [comment]
@berndbischl 
ping you here. Should be ready to merge

**Pull request merged**
