### PR TITLE
Add new learners from SwarmSVM

### PR DESCRIPTION
**Pull request by hetong007**
I figured out the previous error in travis is because I haven't set values to some parameters, and taht triggered a warning.

Is it true that the parameter `default` in `makeIntegerLearnerParam` is only for documentation, other than setting a default value and do pass to the training function?

### CODE REVIEW

**Comment by larskotthoff** [comment]
Ok great. Not sure what you mean with your question -- the default parameter tells mlr what the default value of that particular parameter is.

**Comment by hetong007** [comment]
If I set 
```r
makeIntegerLearnerParam(id = "m", default = 3, lower = 2)
```
I don't have `m=3` passing to my training function if I don't pass it explicitly, do I?

**Comment by larskotthoff** [comment]
Yes, the default parameters aren't set automatically.

**Comment by hetong007** [comment]
Although there's actually an ERROR from other functions, now the learners i add have passed the travis check.

**Comment by larskotthoff** [comment]
But travis passed?

**Comment by hetong007** [comment]
Yes. The existing ERROR is introduced in the master branch of mlr: https://travis-ci.org/mlr-org/mlr#L3100

**Comment by larskotthoff** [comment]
Hmm ok, this works for me locally and travis passes despite the error. I'll have a look.

**Comment by larskotthoff** [comment]
Ok, I've just fixed the error in travis. Could you rebase please? Sorry about the hassle.

**Comment by hetong007** [comment]
It seems good now. Do I still need to squash all the commits? I am afraid the commits from other authors will also be squashed.

**Comment by larskotthoff** [comment]
Thanks, I'll merge this.

**Pull request merged**
