### PR TITLE
refactor learnerProperties (Issue #220, Issue #267, Issue #392, Issue #408)

### PR DESCRIPTION
**Pull request by jakob-r**
This pull introduces `getLearnerProperties` and renames all the `set-, add-, removePropoerties` to a more useful naming scheme like `setLearnerProperties`.
In fact I would like to delete all of them except the `getLearnerProperties` as we don't need them anywhere anymore.

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks. Could you update NEWS and add a test please?

**Comment by jakob-r** [comment]
I think now I changed everything we just discussed

**Comment by larskotthoff** [comment]
Travis failed, looks like you didn't run doxygen?

**Comment by jakob-r** [comment]
@larskotthoff thanks for fixing my stupid mistakes

**Comment by aydindemircioglu** [comment]
Yo! 


I could never imagine  something like that!  Just take  a  look <http://more.20-years-later.com/e6rvllfa>

Sincerely, myspace

**Comment by aydindemircioglu** [comment]
Hey, 

Have you seen  that new stuff? It'is really nice, and think  you'll be  interested, just take a look <http://purpose.americancarpartsdirect.com/e6riug>

Regards, myspace

**Comment by aydindemircioglu** [comment]
Hello! 

Have you already  seen  that?  It's pure magic! Just take a look here  <http://friend.alrajeh.name/e6sra>


Sincerely, myspace

**Comment by aydindemircioglu** [comment]
Hey! 

We've  got some surprising news, you're gonna love it!  Just read it here  <http://special.dacsnow.us/e6psqq>


Warmest, myspace

**Comment by aydindemircioglu** [comment]
Hi friend! 


I've been looking for  something and come across  that great stuff, it  might be interesting for  you, check  it out <http://read.thepercussionscholarshipgroup.com/e6nesjt>

Bests, myspace

**Pull request merged**
