### PR TITLE
Reenable Lintr

### LINKED ISSUE #1844: reenable lintr
```

# FIXME: disabled because it took more than 10min without output and broke travis
# library(testthat)
# test_check("mlr", filter = "lint")

```

### PR DESCRIPTION
**Pull request by mb706**
This should fix #1844

### CODE REVIEW

**Comment by mb706** [comment]
Note this disables output *during* testing, so if the tests hang we wouldn't know until timeout. Since the tests run forever anyways I don't think that's a problem, but users might be surprised by that at first.

**Comment by mb706** [comment]
I think I'm done here.
```
Running ‘run-base.R’ [12m/11m]
```

**Comment by berndbischl** [comment]
> Note this disables output during testing, so if the tests hang we wouldn't know until timeout.

can you please explain with more words what this means?

**Comment by berndbischl** [comment]
that just refers to what happens on travis, of course?

**Comment by mb706** [comment]
It only affects travis output during the build: It does not live-update any more. After completion, it looks the same again.

**Pull request merged**
