### PR TITLE
Ranger: Do not use the formula interface

### PR DESCRIPTION
**Pull request by mllg**
Other interfaces are usually faster and work well with high dimensional data.

### CODE REVIEW

**Comment by larskotthoff** [comment]
Code looks good, but could you please squash the commits into one?

**Comment by mllg** [comment]
Not really. If I rebase interactively, everything breaks. Any hints?

**Comment by berndbischl** [comment]
Have you rebased on master? 
I have not really looked it, but the problem seems to be that you merged the Benchmark Operator commit from Lars?

**Comment by berndbischl** [comment]
Should one in that case "cherry pick" the relevant commits from your side?

**Comment by berndbischl** [comment]
If it does not work, and the change seems so simple, just copy the files and open up a new PR if you cannot figure this out and want to resolve it quickly. 

also pls update NEWS

**Comment by zmjones** [comment]
https://xkcd.com/1597/

**Comment by berndbischl** [comment]
@zmjones 
well.... yeah

**Comment by mllg** [comment]
It is not perfect, but still helpful:
```{bash}
git checkout -b new_branch
git merge --squash old_branch
git commit -m "commit summary"
git push --set-upstream origin new_branch
```

**Comment by mllg** [comment]
Closing this one, I've create a new PR.

**Pull request closed without merging**
