### PR TITLE
new function getFeatureImportance

### PR DESCRIPTION
**Pull request by florianfendt**
What I did:
1. I cloned PR #395, ended up changing quite a lot in there, though.
2. Added the regression and survival counterparts for the learners in #395.
3. Added methods for ranger and randomForestSRC.

There was some documentation in #395 that explained how to implement new methods. I put it in an own section and left it in there for now, although I think this should go to the tutorial, right?

Possible update for NEWS:
````
- Added a new function getFeatureImportance to extract feature importance measures for
  certain learners. So far the following learners are supported:
  boosting, cforest, gbm, randomForest, randomForestSRC, ranger, rpart 

- new functions
-- getFeatureImportance
````

### CODE REVIEW

**Comment by berndbischl** [comment]
try to see if you can add rknn as well, to solve #424

**Comment by florianfendt** [comment]
It had a reason I didn't implement it. I can't remember why exactly right now, though. Will look into it again and report back here.

**Comment by berndbischl** [comment]
> It had a reason I didn't implement it. I can't remember why exactly right now, though. Will look into it again and report back here.

well ok: try to make this PR good  in *general*. rknn is really not that important. if it does not (easily) work to integrate it, simply state the reason here, leave it out and focus on the other stuff and the general structure. that much more important.

**Comment by ja-thomas** [comment]
resolved the merge conflict in #995 and moved the whole thing to a branch.

**Pull request closed without merging**
