### PR TITLE
cleaning up the budget tests

### PR DESCRIPTION
**Pull request by kerschke**
Cleaned up the multicrit budget tests - as requested by @berndbischl in a comment within PR #389.
Once merged, we can finally close issues #336 and #111 .

### CODE REVIEW

**Comment by kerschke** [comment]
@berndbischl - now, I can ping back ;-)

By the way, as far as it looks, Travis fails due to a warning - which is not related to my commits:

```
* checking Rd contents ... WARNING

Argument items with no description in Rd object 'getHomogeneousEnsembleModels':

  ‘model’ ‘learner.models’
```

**Comment by larskotthoff** [comment]
This is fixed in master. Please rebase.

**Comment by kerschke** [comment]
It ran already again ;-) So everything's fine and could be merged. But thanks for the hint :-)

**Comment by larskotthoff** [comment]
Thanks, merging.

**Pull request merged**
