### PR TITLE
Ensembles parallel

### PR DESCRIPTION
**Pull request by zmjones**
this is a clone of #615 in a branch in this repo so that @PhilippPro can help me fix the multilabel breakage

### CODE REVIEW

**Comment by zmjones** [comment]
thanks for the help @PhilippPro

**Comment by berndbischl** [comment]
1) please remove the stacking stuff. we have that completely refactored in another PR. this will create too many problems. store the diff, keep the branch. and doc for now that it is not parallel

2) make sure that users understand what the current par level now does. in the tutorial. list the ensemble learners there.

3) remove the partial dep stuff. but do a new PR for this. seems nearly finished.

4) remove the ens prediction stuff. we will do general parallel prediction.

**Comment by zmjones** [comment]
all that should be done now

**Comment by zmjones** [comment]
@PhilippPro looks like the remaining errors are related to the multilabel stuff. help?

**Comment by PhilippPro** [comment]
ok. first have to look on my own stuff but will try it later.

Am 12.08.2016 um 12:48 schrieb Zachary M. Jones:

**Comment by zmjones** [comment]
thank you!

**Comment by zmjones** [comment]
if someone else wants to finish this up i would be grateful. i don't know the multilabel stuff (which is what i think is broken).

**Comment by PhilippPro** [comment]
I think there are more things that do not work. As you can see in the current travis build, the actual error occurs also in generatePartialDependence and MulticlassWrapper (and DBRWrapper). I just solved the problem with the multilabel example in the push before.

**Comment by zmjones** [comment]
ah ok i will take a look at it again then. thanks

**Comment by PhilippPro** [comment]
I can look at the multilabel part if everything else is ok. It's just disgusting to look at these errors, because you have to step deeply into the infrastructure of predictLearner, predictLearner2, etc. to find the problems and it takes a long time.

**Comment by jakob-r** [comment]
I fixed many variable missnamings and other stuff. But I can not get behind why the "MultilabelDBRWrapper" fails if it wasn't even touched!

**Comment by PhilippPro** [comment]
It depends on MultilabelBinaryRelevanceWrapper and this was touched.

**Comment by jakob-r** [comment]
Oh I indeed oversaw this. I guess I know the issue then

**Comment by jakob-r** [comment]
It just surprised me that the models only have to be named for MultilabelBinaryRelevanceWrapper and the other Multilabel methods worked well without named models.

**Comment by jakob-r** [comment]
I kind of reviewed / recoded it but someone else might have a look over it. @berndbischl @mllg @zmjones ?

**Comment by jakob-r** [comment]
We might want ToDo:

- [ ] parallelize predictions 

?

**Comment by jakob-r** [comment]
We have now a lot more parallelization going on which is pretty cool and already something big (for the low effort).
Please review fast so this get's in mlr 2.11!

**Comment by berndbischl** [comment]
we did a review today. comments:

1) the predict parallelization should be done in general. we should open another issue for this now. 
it should be simply done by chunking over "newdata" in mlr::predict. this works then for everything. 
so the custom predict stuff here needs to be removed. 

2) there is a fault parallel level in zzz.R: partialPredictions. remove it

3) we need to document properly what the new level does. with reference to the implemented ensembles.

**Comment by zmjones** [comment]
I am interviewing for a job early next week and so am occupied until then.
When I get back I can help with this though!

I also have a way to speed up partial dependence by a good bit.

Zachary M. Jones
zmjones.com

**Comment by jakob-r** [comment]
Ready to merge, removed parallizing predictions. Waiting for Bernd to click the button.

**Comment by jakob-r** [comment]
@berndbischl *ping*

**Comment by jakob-r** [comment]
Will automerge in 24 hours.

**Comment by berndbischl** [comment]
the indentation is wrong in several places.

more importantly:
where are the docs what is parallelolized now?

**Comment by jakob-r** [comment]
True, documentation is totally missing. Any hint of where it would make sense to add it? Just add a note for each wrapper that it can be parallelized with the specific tag?

**Comment by berndbischl** [comment]
> True, documentation is totally missing. Any hint of where it would make sense to add it? Just add a note for each wrapper that it can be parallelized with the specific tag?

well, i think it needs to go here:
https://mlr-org.github.io/mlr-tutorial/release/html/parallelization/index.html

BUT:

I think we should also have this in R. makes it much easier to review stuff like this, whether it is "complete". and complete documentation about behavior of options should always be available in R. 

but we dont want to copy-paste docs to 2 places. I would suggest:
we create a mini doc page ?mlrParallel, copy the tutorial LEVEL definition info there, and you add your stuff.

for completeness we can add a sentence and a link to the wrapper that is affected by your change here.

what do you think?

**Comment by jakob-r** [comment]
So. Documentations is done, tests are running. Should be merged soon.

**Comment by jakob-r** [comment]
@berndbischl ping

**Comment by jakob-r** [comment]
We agreed that we do not need to check the result of the predictions as the `parallelMap` code is also run in the normal tests of the ensembles.
Actually it can be argued, that the parallel test can bee seen as superfluous as it just tests the `parallelMap` behavior.

**Comment by berndbischl** [comment]
> Actually it can be argued, that the parallel test can bee seen as superfluous as it just tests the parallelMap behavior.

not really. i detected many bugs with this test, that were not pm bugs. but problems in mlr.
most problematic thing: exporting options to slave and so on.

**Pull request merged**
