### PR TITLE
Added Plotting and Hypothesis Tests for BMR

### PR DESCRIPTION
**Pull request by pfistfl**
New files: 
Data Transformation:
convertBMRToRankMatrix.R

Tests:
friedmanTestBMR.R
posthocNemenyiTestBMR.R

Sorting in Plots: (Helpers)
BenchmarkResultOrderLevels

Plots: (contain getXYZData fcts)
plotRankMatrixAsBar.R
plotBenchmarkSummary.R
plotBenchmarkResult.R
plotCritDifferences.R

### CODE REVIEW

**Comment by zmjones** [comment]
Hello, have a few comments. A little nitpicky, sorry!

Could you go back through your code and compare it with the [style guide](https://github.com/tudo-r/PackagesInfo/wiki/R-Style-Guide)? There are places I noticed where you didn't have spaces between operators, curly braces around things on a single line, etc. Also remove the comment lines at the top of some of the files.

Is there a reason you are explicitly referencing some mlr functions (e.g., `mlr::getBMRAggrPerformances`). There shouldn't be any namespace conflicts, so that is unnecessary. I do it for other packages where there could be namespace conflicts or things that we currently depend on but may later only import, but you don't have to do this (others may not want you to at all, idk). 

I think it might also be good to rename/move some of the functions you wrote to be more coherent with the other plotting/generation functions. So for example when you are generating data (i.e., doing any sort of computation) use the "generate" prefix instead of "get". I've been creating one file for each plot that has the generation function, any helper functions, and the plotting functions. I've also been giving the output from the generation function an S3 class (maybe BenchmarkSummaryData for your case). Then you can have the data as an element in this list, and can pass other information like the task (and later add even more without changing the interface at all). This also allows you to check the object's class when you go to plot it.

For the docs you should check that you are wrapping things in code and link tags appropriately. You can also add families to each function. I have a family for plots (just `@family plot`), one for generation functions (generate_plot_data), and there is probably one to do with BMR.

Don't feel obliged to take all of this advice (other than the style and namespace stuff) if you have objections.

**Comment by berndbischl** [comment]
> Could you go back through your code and compare it with the style guide?

+1

> Is there a reason you are explicitly referencing some mlr functions 

The :: must me removed

**Comment by berndbischl** [comment]
> Don't feel obliged to take all of this advice

Actually feel obliged for most of it :)

Regarding the names:
Can we compile a list here and discuss it here?

@zmjones 
IMHO: Is @pfistfl really generating any data? All the data is already generated in the BMR object? Isnt he mainly doing trivial transformations of it?

**Comment by berndbischl** [comment]
> Can we compile a list here and discuss it here?

Man, I am too busy. Yes, I see we have a list. @zmjones 
If you hate some names, can you please give concrete examples with suggestions?

**Comment by pfistfl** [comment]
Hey Zachary,

Thanks for the review.

Will Do!
I was Not satisfied with the naming of my functions / params, but usually
did Not have a better idea.
Input in regards to naming would bei welcome.

I'll change the Rest accordingly.

Florian

Hello, have a few comments. A little nitpicky, sorry!

Could you go back through your code and compare it with the style guide
<https://github.com/tudo-r/PackagesInfo/wiki/R-Style-Guide>? There are
places I noticed where you didn't have spaces between operators, curly
braces around things on a single line, etc. Also remove the comment lines
at the top of some of the files.

Is there a reason you are explicitly referencing some mlr functions (e.g.,
mlr::getBMRAggrPerformances). There shouldn't be any namespace conflicts,
so that is unnecessary. I do it for other packages where there could be
namespace conflicts or things that we currently depend on but may later
only import, but you don't have to do this (others may not want you to at
all, idk).

I think it might also be good to rename/move some of the functions you
wrote to be more coherent with the other plotting/generation functions. So
for example when you are generating data (i.e., doing any sort of
computation) use the "generate" prefix instead of "get". I've been creating
one file for each plot that has the generation function, any helper
functions, and the plotting functions. I've also been giving the output
from the generation function an S3 class (maybe BenchmarkSummaryData for
your case). Then you can have the data as an element in this list, and can
pass other information like the task (and later add even more without
changing the interface at all). This also allows you to check the object's
class when you go to plot it.

For the docs you should check that you are wrapping things in code and link
tags appropriately. You can also add families to each function. I have a
family for plots (just @family plot), one for generation functions
(generate_plot_data), and there is probably one to do with BMR.

Don't feel obliged to take all of this advice (other than the style and
namespace stuff) if you have objections.

—
Reply to this email directly or view it on GitHub
<https://github.com/berndbischl/mlr/pull/343#issuecomment-112893370>.

**Comment by zmjones** [comment]
Do you mean names of the functions @pfistfl added?

And idk about the generation. It wouldn't be a thesis project if it was trivial though right? It isn't just extracting things from a BMR.

**Comment by berndbischl** [comment]
> Do you mean names of the functions @pfistfl added?

Yes.

> And idk about the generation. It wouldn't be a thesis project if it was trivial though right? It isn't just 
> extracting things from a BMR.

Well the work is in the visualization and so on. What I mean is:
Isnt in his case the BMR object already the "container"?
Where do you see a point where he really generates data?

**Comment by zmjones** [comment]
`getBenchmarkSummaryData` and `getCritDifferencesData`. In both cases it appears that he is doing something more than extracting some part of a BMR object. Certainly it is non more trivial than some of the ones I converted to "generation" functions. If you disagree that is fine though. I have thought of get as for simple extraction and generate for extraction + manipulation of most any sort.

It seems that in the plot functions he calls the get functions (the ones i think should be renamed). A better structure (mine anyway) is to generate an object and then pass that to the plot. Otherwise we have the problem that people can't easily make custom plots. This comes with the necessity of giving the generation output a class and checking it in the plot function.

**Comment by berndbischl** [comment]
Ok, can we define the API here so can change it without working against a moving or blurry target?

**Comment by larskotthoff** [comment]
> A better structure (mine anyway) is to generate an object and then pass that
> to the plot. Otherwise we have the problem that people can't easily make
> custom plots. This comes with the necessity of giving the generation output a
> class and checking it in the plot function.

Could you document this in the style guide on the Wiki please?

**Comment by pfistfl** [comment]
Yes i mean the functions added and the Names of the params within. If Yo u have improvements I'll gladly change Them.

@zachary
Gotta Check your Code again.
My idea was for the User to Either Call the Plot fct to Plot Directory or the get to get the Data.frame used for plotting. (which then could ne used in  ggvis for example)

**Comment by berndbischl** [comment]
@zmjones 
Or you could also merge and improve this, after he has done the more easier changes?

**Comment by zmjones** [comment]
@larskotthoff yes. just did that.

@berndbischl do you mean more than what I added to the [style guide](https://github.com/berndbischl/mlr/wiki/mlr-Coding-Guidelines)? I think it would be easy to do this. I can of course write ggvis versions of these after they are merged. Let me know after @pfistfl has had some time if you want me to pull his remote branch and work on it (that is how I'd do that right?).

**Comment by pfistfl** [comment]
- Overhauled the style, should be according to style guide now.

@zmjones 
regarding the generateData functions:
As I do not get the advantages of the S3-Obj yet I'd like to ask for clarification.
I am still not entirely sold on the idea of generating the Data as a S3-Obj. Would that not just add another command? like:

`<a = generate...Data>` 
`<plot...(a) >`
 
If i wanted to plot the generated Data, do you not need to implement an `<as.data.frame>`
 method so I can plot it on my own in ggvis?
My idea was to simply allow the creation of a data.frame that a user can use to plot the data in ggvis for example. 
Could you clarify on this? I'm looking forward to learn from this!

**Comment by zmjones** [comment]
Yes it does add another layer, and so another command that the user has to write. No you don't have to coerce the object if you want to plot things yourself. You just extract the data object from the S3 list. The S3 list is nice because we can include extra meta information we need (or might need down the road) without changing the API. The output of the generation functions will always be a list of this class, it just might have more elements later.

**Comment by pfistfl** [comment]
Ah Ok, thanks for clarification! 

I'll go through your code and try to replicate tomorrow. 

Guess it makes sense to create it as a S3Obj, so I can include extra info.

**Comment by zmjones** [comment]
Yea I mean it is even nice for just printing, even if you don't use it. So users can see that it was created by this function, used this task, learner, etc. You can also document the object and write a little print method. There are examples of that in the generation files as well.

**Comment by pfistfl** [comment]
Mind looking over how I did the generate/plot separation now? 
If you got further input I'm glad to change further.

**Comment by zmjones** [comment]
@pfistfl 

have been going through your code for the past hour or so. what do you think about using "BenchmarkResultData" as a class name instead of "RankMatrixAsBarData". Is the the former too ambiguous, since we already have "BenchmarkSummaryData"?

I'll probably be through reviewing and testing in a few hours.

**Comment by pfistfl** [comment]
@zmjones 
1) I think that "BenchmarkResultData" might be easily confusable with "BenchmarkResult". Maybe something like "BenchmarkRankData" or "BenchmarkBarplotData" ?
2) Had a major fuckup in how I calculated the critical differences in the nemenyi-test. Corrected in latest commit (coming in ~3 minutes) 
3) CriticalDifferencesDiagram still not done, I have not found an elegant solution for the test = "nemenyi" part. (Want to merge lines that are fully included in another interval into the biggest one)
4) Let me know about improvements in visualisation, that could be done.

**Comment by zmjones** [comment]
Ok cool. Will look at it again soon.

**Comment by berndbischl** [comment]
what is the status here?

**Comment by berndbischl** [comment]
@pfistfl

**Comment by pfistfl** [comment]
@berndbischl , @zmjones 

I think I'm done for now.
There is still one plot and one hypothesis test that I could include at a later point, but this needs to be discussed first..
The added functions should work properly.

**Comment by zmjones** [comment]
OK I will work on cleaning and merging this today

**Comment by berndbischl** [comment]
great pls mail when done

**Comment by zmjones** [comment]
@pfistfl 

i got this error (aside from the travis breakage on master)

```{r}
Warning in if (nzchar(res <- isUME(ee))) return(res) :
  the condition has length > 1 and only the first element will be used
```

could you fix that? you definitely should not be doing assignment like that in a conditional. i assume that was a typo?

**Comment by zmjones** [comment]
Some of the plots appear to be broken as well. Investigating this now. The tests aren't detecting the failure because you have to "print" a ggplot2 object for it to actually be drawn. You still get a ggplot object even with something that won't be drawn. For example you could create an empty object.

**Comment by zmjones** [comment]
an error

```{r}
> plotCritDifferences(r2)
Error in matrix(value, n, p) : 
  'data' must be of a vector type, was 'NULL'
```

Also there appears to be some overplotting with the labels you are putting in the top right corner of this plot. I haven't looked through the plot code yet so am not sure what you are doing there however.

**Comment by larskotthoff** [comment]
Zach, it sounds like you want to create a unit test for each of the problems you've identified and open a PR for @pfistfl 's repository so he can fix and check easily :)

**Comment by zmjones** [comment]
Ok yea that is a good idea.

**Comment by zmjones** [comment]
I think I have fixed almost all of the problems now. I guess I will just open another PR after that is done.

**Comment by pfistfl** [comment]
Hey, thanks for going through.

1) i got this error when checking (aside from the travis breakage on master)

Warning in if (nzchar(res <- isUME(ee))) return(res) :
  the condition has length > 1 and only the first element will be used

could you fix that? you definitely should not be doing assignment like that in a conditional. i assume that was a typo?

I looked through your code a bit but couldn't find where that was coming from.

-- > Could you point me to anything? Have not seen this piece of code before.

3)
> plotCritDifferences(r2)
Error in matrix(value, n, p) : 
  'data' must be of a vector type, was 'NULL'

Never had that error before. Happens when all learners have equal ranks....
Gonna fix that.

2) Error in eval(expr, envir, enclos) : could not find function "desc"
plyr::desc --> Do not know why it should not work


3)

**Comment by zmjones** [comment]
Don't worry about these now. I've fixed all the ones I have found. I am going to keep working on it until it is ready and then reissue a PR. You can look at what I did there and decide if the changes I've made are ok.

The desc error was because you were using aes_string. Using it that way relies on NSE.
There have been some other small errors. I'm also messing with the plots a bit to make them consistent with the others, and adding a few features.

**Comment by zmjones** [comment]
@pfistfl 

your forked repo is really out of date w.r.t. master so i issued a PR (#388) here for you to look at. i think this will be less confusing.

in the future you should definitely keep a branch that tracks the master branch of whatever repo you are going to issue a PR for. periodically rebase the branch you are working on off of that. it will make it much easier for you to merge then.

**Comment by berndbischl** [comment]
can this be closed?

**Comment by pfistfl** [comment]
Fine by me.

**Comment by berndbischl** [comment]
@pfistfl said it can be closed. His code is in the most recent version already in mlr.
For further stuff / bugs we open separate issues when they appear.

**Pull request closed without merging**
