### PR TITLE
add auc filter

### PR DESCRIPTION
**Pull request by bommert**

### CODE REVIEW

**Comment by catastrophic-failure** [comment]
I don't think you need `ROCR` to do that, you could use the already implemented `auc` functions in `mlr`, and from what I remember these were faster.

**Comment by larskotthoff** [comment]
Looks like the tests are failing.

**Comment by smilesun** [comment]
Hi, We find the following error, not sure yet how this works to constrain to binary class
```
1. Error: filterFeatures (@test_featsel_filters.R#15) --------------------------
  Number of classes is not equal to 2.
  ROCR currently supports only evaluation of binary classification tasks.
  1: filterFeatures(task = multiclass.task, method = filter, perc = 0.5) at testthat/test_featsel_filters.R:15
  2: generateFilterValuesData(task = task, method = method, nselect = nselect, ...)
```

**Comment by mllg** [comment]
You could switch to `pROC` which supports multiclass auc and is already in `Suggests` (albeit we do not use it :-1:).

```r
#' Filter \dQuote{auc} determines for each feature how well the target
#' variable can be predicted only based on this feature. More precisely, the
#' prediction rule is: class 1 if the feature exceeds a threshold and class 0
#' otherwise. The performance of this classification rule is measured by the
#' AUC and the resulting filter score is |0.5 - AUC|.
#'
#' @rdname makeFilter
#' @name makeFilter
makeFilter(
  name = "auc",
  desc = "AUC filter for binary classification tasks",
  pkg  = "pROC",
  supported.tasks = "classif",
  supported.features = "numerics",
  fun = function(task, nselect, ...) {
    data = getTaskData(task, target.extra = TRUE)
    if (length(getTaskClassLevels(task)) == 2L) {
      score = vnapply(data$data, function(x, y) {
        as.numeric(pROC::roc(predictor = x, response = y)$auc)
      }, y = data$target)
    } else {
      score = vnapply(data$data, function(x, y) {
        as.numeric(pROC::multiclass.roc(predictor = x, response = y)$auc)
      }, y = data$target)
    }

    abs(0.5 - score)
  }
)
```

This snippet should already work, but it would be great if @bommert and/or @smilesun could carefully read the manual and confirm that you do not have to set any extra arguments for pROC. Additionally, a short unit test would be great (e.g., check on iris that `Petal.Length` and `Petal.Width` get a high score).

**Comment by berndbischl** [comment]
> You could switch to pROC which supports multiclass auc and is already in Suggests (albeit we do not use it ).

please be careful here. if you search the history, you will notice that we actually USED pROC for multiclass AUC. it was then removed for a reason

**Comment by berndbischl** [comment]
I guess you want to read at least this
https://github.com/mlr-org/mlr/issues/3

**Comment by berndbischl** [comment]
uuuh. just looked at the code. main point is:
we SURELY want to use the *same* calculation here for the AUC that mlr uses for its normal measures?

i DO NOT want be inconsistent. 
so not pROC there, ROCR in another place.

why not simply call into mlr's measureAUC function?

**Comment by mllg** [comment]
Right, multiclass was a bad idea in the first place for the filter. But we are apparently missing a property for the filters to flag them to only work on binary classif tasks.

**Comment by berndbischl** [comment]
> Right, multiclass was a bad idea in the first place for the filter.

why? what would make it more applicable? 

> But we are apparently missing a property for the filters to flag them to only work on binary classif tasks.

separate issue?

**Comment by mllg** [comment]
> why? that would make the filter more applicable? I would like that

`pROC` has a function for that, but they say it is less tested. And the multiclass measures in mlr seem to require probabilities for each class which is something we do not have in the filter.

**Pull request merged**
