### PR TITLE
Oneclass Local Outlier Factor (LOF) from DMwR

### PR DESCRIPTION
**Pull request by MinhAnhL**
Add Rlearner lofactor (Local Outlier Factor) from DMwR for Anomaly Detection

### CODE REVIEW

**Comment by pat-s** [comment]
@MinhAnhL Do you have time and motivation to rebase your work here? I can review it afterwards.

**Comment by MinhAnhL** [comment]
> @MinhAnhL Do you have time and motivation to rebase your work here? I can review it afterwards.
> 
> Q: Why are you not aiming to merge into master here?

Hi @pat-s Thank you for your offer, that is very kind. However, I currently don't have the capacity to continue to work on this. Maybe in the future :)
I developed the functions mainly for my Masterthesis, which worked perfectly for me. 
When I started, mlR had the supervised and unsupervised-class, from which I can inherit methods. Due to the limited time, I based the semi-supervised methods Autoencoder, LOF, and one-class SVM on the supervised-class (mainly to enable supervised evaluation). If I had to redo it and have more time, it would be nicer to create a new semi-supervised class, which is a whole lot more work :)  So I guess that is one of the reasons why it has not been merged.

**Comment by pat-s** [comment]
Thanks for the heads-up! Does this mean that we can close all the "OneClass" PRs since they all belong together and won't be finished anymore?

**Comment by MinhAnhL** [comment]
From my side, yes :)

**Pull request closed without merging**
