### PR TITLE
Add six new learners

### PR DESCRIPTION
**Pull request by hetong007**
In this PR I have added 

- `neuralnet::neuralnet` for binary classification
- `avNNet` from `caret` for classification and regression
- `SwarmSVM::clusterSVM`, `SwarmSVM::dcSVM` and `SwarmSVM::gaterSVM` for classification.

I have also fixed a possible bug in ` R/predictLearner.R`.

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks Tong, looks great! Could you add a note to NEWS please mentioning the new learners?

**Comment by berndbischl** [comment]
And please squash to one single commit so it is easier to review

**Comment by berndbischl** [comment]
and if swarmsvm is not on CRAN you need to remove it for now

**Comment by hetong007** [comment]
SwarmSVM is on cran now: http://cran.r-project.org/web/packages/SwarmSVM/index.html .

**Comment by berndbischl** [comment]
You also do some more complex stuff in avnet, probably bagging.
So more than just wrapping the learner.
You at least need to mention this in the $note

**Comment by hetong007** [comment]
I will rebase the code in one commit after I successfully pass the travis-ci test.

**Comment by berndbischl** [comment]
thx

**Comment by hetong007** [comment]
Currently my PR keeps breaking the travis CI, but the latest error is confusing me

```
* checking tests ...
  Running ‘run-base.R’ [89s/91s]
  Running ‘run-classif.R’ [74s/71s]
  Running ‘run-cluster.R’
  Running ‘run-featsel.R’ [58s/55s]
  Running ‘run-learners.R’ [47s/45s]
 ERROR
Running the tests in ‘tests/run-learners.R’ failed.
Last 13 lines of output:
  GConf Error: No D-BUS daemon running
  
  
  (process:30335): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
  Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
  GConf Error: No D-BUS daemon running
  
  testthat results ================================================================
  OK: 81 SKIPPED: 0 FAILED: 1
  1. Error: learners work 
  
  Error: testthat unit tests failed
  Execution halted
```

I cannot directly see the relationship between my code and this (possibly) X11 issue. I have closed and reopened the PR to trigger a rebuild on travis. The result stays the same. May I ask if anyone have met similar errors in `mlr` so that I can guess what is happening? Thank you very much.

Besides, I am wondering do you get email notifications if I keep failing on my PR? I am afraid that it is annoying you. If so, sorry about that.

**Comment by berndbischl** [comment]
> if I keep failing on my PR? I am afraid that it is annoying you. If so, sorry about that.

Forget about that at once. You are not annoying us, and I dont get a million emails. 

> I cannot directly see the relationship between my code and this (possibly) X11 issue.

IIRC this message is more or less a warning, I have seen it before, and it is generated not by your PR but one of the java based learners. But you do have a real error in there that we need to fix - and get its message. 

I know this is annoying, but as I am also sick, can you please then go the "hard" way and create PRs, one for each new learner? So we see where this occurs? If we have narrowed it down, I might be able to help you directly.

**Comment by larskotthoff** [comment]
Can you reproduce this on your local machine? It looks like the error is coming from the "learners work" test, which may be failing because it's pulling in one of your new learners and uses it in ways that you didn't anticipate.

**Comment by hetong007** [comment]
@larskotthoff If I run `R CMD check --as-cran` locally, I got errors other than this one:

First of all a lot of notes on

```
unused argument  (tunable = FALSE)
```

This unused argument is also causing an error in

```
* checking examples ... ERROR
Running examples in ‘mlr-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: FailureModel
> ### Title: Failure model.
> ### Aliases: FailureModel
> 
> ### ** Examples
> 
> configureMlr(on.learner.error = "warn")
> data = iris
> data$newfeat = 1 # will make LDA crash
> task = makeClassifTask(data = data, target = "Species")
> m = train("classif.lda", task) # LDA crashed, but mlr catches this
Error in makeLogicalLearnerParam(id = "CV", default = FALSE, tunable = FALSE) : 
  unused argument (tunable = FALSE)
Calls: train ... checkClass -> makeParamSet -> makeLogicalLearnerParam
Execution halted
```
I also have the following error, but I am not sure if it is because of my configuration:

```
Running the tests in ‘tests/run-base.R’ failed.
Last 13 lines of output:
  10: assertClass(par.set, classes = "ParamSet")
  11: checkClass(x, classes, ordered)
  12: makeParamSet(makeDiscreteLearnerParam(id = "method", default = "moment", values = c("moment", 
         "mle", "mve", "t")), makeNumericLearnerParam(id = "nu", lower = 2, requires = expression(method == 
         "t")), makeNumericLearnerParam(id = "tol", default = 1e-04, lower = 0), makeDiscreteLearnerParam(id = "predict.method", 
         values = c("plug-in", "predictive", "debiased"), default = "plug-in", when = "predict"), 
         makeLogicalLearnerParam(id = "CV", default = FALSE, tunable = FALSE))
  13: makeLogicalLearnerParam(id = "CV", default = FALSE, tunable = FALSE)
  
  
  (process:16714): GLib-GIO-ERROR **: Settings schema 'org.gnome.system.proxy' is not installed
  
  Trace/breakpoint trap (core dumped)
```

I am running this on an AWS machine with 4GB memory, 8GB hard disk and Ubuntu 14.04. 

So maybe the better way is to use travis :(

**Comment by berndbischl** [comment]
> unused argument  (tunable = FALSE)

You need ParamHelpers from Github for a short time

**Comment by larskotthoff** [comment]
Ok, I've cloned your repository. I've loaded `devtools` and run the tests locally with `test()`. At some point it loads too many DLLs and fails from then on, but before that I'm getting a lot of output from `classif_avNNet`:

    classif_avNNet : # weights:  187
    initial  value 70.931182
    iter  10 value 41.846430
    iter  20 value 27.443862

etc. Could you suppress that please?

When testing only `learners_all` (`test(filter = "learners_all")`), I'm getting an actual error:

    1. Error: learners work --------------------------------------------------------
    Either number of centers or the clustering result is needed
    1: withCallingHandlers(eval(code, new_test_environment), error = capture_calls, message = function(c) invokeRestart("muffleMessage"),
       warning = function(c) invokeRestart("muffleWarning"))
    2: eval(code, new_test_environment)
    3: eval(expr, envir, enclos)
    4: train(lrn, task) at test_learners_all.R:77
    5: system.time(fun1(learner.model <- fun2(do.call(trainLearner, pars))), gcFirst = FALSE) at /tmp/mlr/R/train.R:84
    6: fun1(learner.model <- fun2(do.call(trainLearner, pars)))
    7: evalVis(expr)
    8: withVisible(eval(expr, pf))
    9: eval(expr, pf)
    10: eval(expr, envir, enclos)
    11: fun2(do.call(trainLearner, pars))
    12: do.call(trainLearner, pars)

etc. Could you check this please? That's probably what's going wrong on Travis.

**Comment by berndbischl** [comment]
Lars, you need to test with rt --filter=<testgroup>

**Comment by larskotthoff** [comment]
That should give me the same errors though, shouldn't it?

**Comment by berndbischl** [comment]
I wont give you DLL errors, that is what I meant

**Comment by hetong007** [comment]
I have fixed the configuration error. But now it has just passed the check locally. 

```
* checking tests ...
  Running ‘run-base.R’ [68s/70s]
  Running ‘run-classif.R’
  Running ‘run-cluster.R’
  Running ‘run-featsel.R’
  Running ‘run-learners.R’
  Running ‘run-parallel.R’
  Running ‘run-regr.R’
  Running ‘run-stack.R’
  Running ‘run-surv.R’
  Running ‘run-tune.R’
 OK
```

I will split the new learners and submit them to travis one by one to try to reproduce the error.

**Comment by larskotthoff** [comment]
Ok, that seems to be fine. Does that contain everything now?

**Comment by hetong007** [comment]
Well not yet...The PR with SwarmSVM is breaking the Travis CI, while the other two seems to be fine. I will fix that today. It is just not so convenient for being not reproducible locally.

**Comment by hetong007** [comment]
I am a bit confused by Travis in the latest push. There's an ERROR at this line: https://travis-ci.org/mlr-org/mlr/builds/71343809#L3291, but it says all checks have passed. 

Anyway, the latest push has truly passed the travis ci check. I decide to add the three non-SwarmSVM learners first. The commit has been squashed a bit. However I forgot to pull your new changes before the rebase operation, so I need to pull them and fix the confliction. I am afraid of rebasing some commits not made by myself now, so if you are reviewing the code, could you please look into `Files changed` section? There are basically 3 new learners and the 3 corresponding test files. Thank you.

**Comment by larskotthoff** [comment]
The diff looks good to me and agreed on the Travis weirdness -- not sure what's going on there. I'll keep an eye on this build and merge if it passes and there're no errors. Thanks!

**Pull request merged**
