### PR TITLE
don't add additional classes if FailureModel encountered

### LINKED ISSUE #1981: Failure models not handled correctly in benchmarking
When running a benchmark and a learner model fails, the benchmark function stops regardless of the settings of `on.learner.error`.

Consider the following (minimal?) reproducible example:
```r

set.seed(123)

# Load mlr ----
library(mlr)
configureMlr("on.learner.error" = "warn")

# Generate data ----
data = data.frame(y = factor(c(1, sample(c(0), 99, TRUE)), 
                              levels = c(0,1), labels = c("control", "case")), 
                   x = matrix(rnorm(1000), nrow = 100))
task = makeClassifTask("test", data = data, target = "y")

# Define measures ----
measures = list(mlr::auc)

# Define filter parameter set ----
filter_ps = ParamHelpers::makeParamSet(ParamHelpers::makeIntegerParam("fw.abs",
                                                                       lower = 1,
                                                                       upper = mlr::getTaskNFeats(task)))

# Define tuning control ----
ctrl = mlr::makeTuneControlRandom(maxit = 10)

# Define resampling strategies ----
inner = mlr::makeResampleDesc("CV", stratify = FALSE, iters = 3)
outer = mlr::makeResampleDesc("CV", stratify = FALSE, iters = 3)

# Define learner ----
glm_lrn = mlr::makeLearner("classif.binomial", predict.type = "prob", config = list("on.learner.error" = "warn"))
glm_lrn = mlr::makeFilterWrapper(glm_lrn, fw.method = "chi.squared")
glm_lrn = mlr::makeDownsampleWrapper(glm_lrn, dw.perc = 1/5, dw.stratify = FALSE)

glm_ps = ParamHelpers::makeParamSet(ParamHelpers::makeDiscreteParam("link",
                                                                     values = c("logit",
                                                                                "probit",
                                                                                "cloglog")))

glm_lrn = mlr::makeTuneWrapper(glm_lrn,
                                resampling = inner,
                                control = ctrl,
                                measures = measures,
                                par.set = c(filter_ps, glm_ps),
                                show.info = TRUE)

# Benchmark ----
bmr = benchmark(learners = list(glm_lrn), 
                 tasks = task, 
                 resamplings = outer, 
                 measures = measures, 
                 keep.pred = FALSE, models = FALSE, show.info = TRUE)

Task: test, Learner: classif.binomial.filtered.downsampled.tuned
[Resample] cross-validation iter 1: [Tune] Started tuning learner classif.binomial.filtered.downsampled for parameter set:
           Type len Def               Constr Req Tunable Trafo
fw.abs  integer   -   -              1 to 10   -    TRUE     -
link   discrete   -   - logit,probit,cloglog   -    TRUE     -
With control class: TuneControlRandom
Imputation value: -0
[Tune-x] 1: fw.abs=8; link=logit
Warning in train(.learner$next.learner, .task, weights = .task$weights) :
  Could not train learner classif.binomial.filtered: Error in .jcall(filter, "Z", "setInputFormat", instances) : 
  weka.core.UnsupportedAttributeTypeException: weka.filters.supervised.attribute.Discretize: Cannot handle unary class!

Warning in train(learner, task, subset = train.i, weights = weights[train.i]) :
  Could not train learner classif.binomial.filtered.downsampled.tuned: Error : $ operator is invalid for atomic vectors

Error: $ operator is invalid for atomic vectors
```
Given settings of `on.learner.error` I expected many failure models during the benchmark and finally a bad performance, but no stop because of an error.

I think the error stems from [this line](https://github.com/mlr-org/mlr/blob/b38bc1152ad5b6b109c0c29f9ecc03fa5f502a88/R/BaseWrapper.R#L68). Here, `isFailureModel` is called repeatedly on `next.model` but at some point this is not a `BaseWrapperModel` or any other model anymore, but a string:
```{r}
str(model$learner.model$next.model$learner.model)
chr "Error in .jcall(filter, \"Z\", \"setInputFormat\", instances) : \n  weka.core.UnsupportedAttributeTypeException: weka.filters.s"| __truncated__
```

Is my expectation wrong or is this a bug?

## Session info
```{r}
sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

locale:
 [1] LC_CTYPE=en_US.UTF-8          LC_NUMERIC=C                 
 [3] LC_TIME=en_US.UTF-8           LC_COLLATE=en_US.UTF-8       
 [5] LC_MONETARY=en_US.UTF-8       LC_MESSAGES=en_US.UTF-8      
 [7] LC_PAPER=en_US.UTF-8          LC_NAME=en_US.UTF-8          
 [9] LC_ADDRESS=en_US.UTF-8        LC_TELEPHONE=en_US.UTF-8     
[11] LC_MEASUREMENT=en_US.UTF-8    LC_IDENTIFICATION=en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mlrMBO_1.1.0      smoof_1.5.1       checkmate_1.8.3   BBmisc_1.11      
[5] mlr_2.11          ParamHelpers_1.10

loaded via a namespace (and not attached):
 [1] parallelMap_1.3     Rcpp_0.12.12        RColorBrewer_1.1-2 
 [4] plyr_1.8.4          RWekajars_3.9.1-3   lhs_0.14           
 [7] tools_3.3.1         digest_0.6.12       viridisLite_0.2.0  
[10] jsonlite_1.0        tibble_1.3.3        gtable_0.2.0       
[13] lattice_0.20-33     DiceKriging_1.5.5   rlang_0.1.1        
[16] Matrix_1.2-6        DBI_0.7             parallel_3.3.1     
[19] rJava_0.9-8         dplyr_0.5.0         httr_1.2.1         
[22] htmlwidgets_0.9     plot3D_1.1          grid_3.3.1         
[25] data.table_1.10.4   R6_2.1.2            plotly_4.7.1       
[28] survival_2.39-4     mco_1.0-15.1        RJSONIO_1.3-0      
[31] RWeka_0.4-34        FSelector_0.21      ggplot2_2.2.1      
[34] purrr_0.2.3         tidyr_0.5.1         magrittr_1.5       
[37] backports_1.1.0     scales_0.4.1        htmltools_0.3.5    
[40] splines_3.3.1       randomForest_4.6-12 assertthat_0.1     
[43] misc3d_0.8-4        colorspace_1.2-6    entropy_1.2.1      
[46] stringi_1.1.5       lazyeval_0.2.0      munsell_0.4.3 
```

## Bug report

- [ x] Start a new R session
- [x ] Install the latest version of mlr: `update.packages(oldPkgs="mlr", ask=FALSE)` or if you use a GitHub install of mlr: `devtools::install_github(c("BBmisc", "ParamHelpers", "mlr"))`
- [ x] run `sessionInfo()`
- [x ] Give a minimal reproducible example

### PR DESCRIPTION
**Pull request by dagola**
fixes #1981. I've run `devtools::test(filter = "base")` and it doesn't seem to introduce new errors. The code I've posted in #1981 does show my expected behaviour now.

However, I tried to write a test to replicate the behaviour of #1981 using the mock learners, but I have to admit, that I'm not able to do that. Unfortunately, I don't have the time at the moment to dive deeper in the `mlr` internals to add a corresponding test - my apologies for that.

### CODE REVIEW

**Comment by dagola** [comment]
Rebase complete.

I will try to figure out how to create a test that mimics #1981 in the next week. Any tips for that? Is the use of mock learners appropriate for that?

**Comment by ja-thomas** [comment]
Cool.

Try to keep the unit test as small as possible, i.e., reduce your initial code from the bug report as much as possible. And use a mock learner to trigger a `failureModel`. 

When you have an initial version for the unittest we can review.

Thanks

**Comment by dagola** [comment]
Sorry for the delay, I've added a test now.

Probably I messed up the rebasing, because I don't really understand what to do. I'll try to fix.

**Comment by dagola** [comment]
@ja-thomas Can you assist me on rebasing, please? Should I choose a specific commit from `master` or just do `git rebase master`? If I run the latter, all commits on `master` until now are included but that's not what you want me to do, I guess?

**Comment by ja-thomas** [comment]
Since you're working in a seperate fork I can't directly do the rebase for you.

The steps should look like that:

- Pull the refs from the main mlr master branch (https://help.github.com/articles/syncing-a-fork/)
- Make sure your branch is clean, (git reset --hard to go back to the last working version)
- merge master and push

This should solve the problem

**Comment by dagola** [comment]
Thanks for your help. Looks like this is clean now.

**Comment by pat-s** [comment]
@dagola Could you check the checkbox "allow edits from maintainers"? So we can finish this PR here. Otherwise I would manually need to copy all of your changes to make additional ones.

The Travis error is probably caused because variable `measure` was not set in the test.

**Comment by dagola** [comment]
@pat-s The checkbox is checked.
Screenshot 2019-04-23 at 08 02 30

**Comment by pat-s** [comment]
Thanks. Merging soon. Thanks for contributing!

**Pull request merged**
