### PR TITLE
use getS3method in listLearners

### PR DESCRIPTION
**Pull request by mllg**

### CODE REVIEW

**Comment by berndbischl** [comment]
that change implies that people will not be able to list their locally added learners, except they register the S3 methods manually?

**Comment by mllg** [comment]
Before only learners found by `methods()` have been considered by `listLearners()`. This behavior is unchanged (except S4 methods are not considered any more, but I guess that is no biggie?).

**Comment by berndbischl** [comment]
merging this here, but we should communicate that people should registerS3 there local learners which are not packaged in mlr. see here:

https://github.com/mlr-org/mlr-tutorial/issues/39

@schiffner maybe you could be so nice to add 2 sentences about this in "how to extend mlr learners"?
pretty please?

**Comment by schiffner** [comment]
But only because you're asking so nicely. ;)

**Pull request merged**
