### PR TITLE
calculateROCMeasures and calculateConfusionMatrix: mini fixes

### PR DESCRIPTION
**Pull request by schiffner**
Fixed some typos and repaired family.

One nit-picky detail question: At the moment function calculateConfusionMatrix generates an object of class ConfMatrix. Do we want to make the names more consistent i.e. rename the class to ConfusionMatrix or the function to calculateConfMatrix?

### CODE REVIEW

**Comment by berndbischl** [comment]
thx a lot.


> One nit-picky detail question: At the moment function calculateConfusionMatrix generates an object of class ConfMatrix. Do we want to make the names more consistent i.e. rename the class to ConfusionMatrix or the function to calculateConfMatrix?

consistent names are good. can you please rename? ConfusionMatrix seems good.
do it in this PR?

**Comment by schiffner** [comment]
> do it in this PR?

Yep. Give me a second.

**Comment by schiffner** [comment]
Do I need to push the Rd-files and NAMESPACE, too?

**Comment by berndbischl** [comment]
paging @larskotthoff 

i really dont know. push them here for now.

**Comment by schiffner** [comment]
Yay. Seems to work without pushing them.

**Comment by larskotthoff** [comment]
The family overview page? That's auto-generated by Travis (not at the moment, but as soon as I've fixed it), so there's no need to do anything.

**Comment by berndbischl** [comment]
> The family overview page? That's auto-generated by Travis (not at the moment, but as soon as I've fixed it), so there's no need to do anything.

julia meant the normal "man" .RD files and the NAMESPACE entries.
autogenerating them seems to work now

**Comment by larskotthoff** [comment]
Wait, was that broken? And aren't you supposed to be on holiday?

**Comment by schiffner** [comment]
> Wait, was that broken? And aren't you supposed to be on holiday?
I don't think so, I was just clueless. :wink:

**Comment by berndbischl** [comment]
lars, that was i think broken quite often. so at least i couldnt remember whether it still worked

**Comment by larskotthoff** [comment]
It shouldn't be broken. Can you let me know when you think it's broken please? Also note that this will only work for master builds, not pull requests (intentionally).

**Comment by schiffner** [comment]
> Also note that this will only work for master builds, not pull requests (intentionally).

Ok, so if I have a PR where I for example add an argument to a function I *have* to push the Rd-files in order to pass R CMD check?

**Comment by larskotthoff** [comment]
No, sorry -- I mean that for PRs it won't commit the result. You never need to update the documentation yourself.

**Comment by berndbischl** [comment]
> No, sorry -- I mean that for PRs it won't commit the result. You never need to update the documentation yourself.

can you pls clarify this is in the devel wiki? this is asked every time.

**Comment by larskotthoff** [comment]
"You don't need to update the documentation. Travis does this automatically."

**Pull request merged**
