### PR TITLE
Multiclass functionality for the earth classifier

### PR DESCRIPTION
**Pull request by rwarnung**
I added back the multiclass functionality. The advice using package="!earth" was the key. Local tests have passed.

### CODE REVIEW

**Comment by rwarnung** [comment]
@larskotthoff Hi Lars, I tried to do the following: merge the newest state of mlr devel with my local repo and then removed the comment that you put into the learner and test file (sorry ... I didn't know these multiline comment signs ... what are they precisely ... I might sound stupid but I have never seen them before). I hope this pull request and the procedure was ok/helpful. Let's wait for the online tests. Locally it was all fine. Thanks for your help.

**Comment by larskotthoff** [comment]
I don't know what you mean by "multiline comment sign"? And you have the learner file in the root directory as well as the R/ directory. Please remove that.

**Comment by rwarnung** [comment]
@larskotthoff sorry for the inconveniance and about the additional learner file ...
I think I sometimes mess  a bit here in this github developement process- I am just getting used to it (and I think it is a great way to work). I hope my files are ok now. I see Jenkins failed and I don't know how to inspect this (I can not log in). Would it have been the best to download (clone) the newest version of the mlr-devel and then open up the pull request? If the Jenkins check is not crucial and the files are ok, then I will delete my personal repo and later when I try to work on mxnet then I will start fresh from skretch (with far more experience than when I begin with earth). With "multiline comment" I meant "<<<<<<< HEAD" and "=======" ... I just don't know this ...  although I work  in R for a while now ;). Please let me know how I can fix this multiclass thing (what you need for it).

**Comment by Stevo15025** [comment]
Until Lars can give you access, I logged into Jenkins and the error is 

```
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
* checking PDF version of manual without hyperrefs or index ... ERROR
Re-running with no redirection of stdout/stderr.
Hmm ... looks like a package
file 'mlr-manual.pdf' exists; please remove it first
* DONE
Status: 1 ERROR, 1 WARNING
Build step 'Execute shell' marked build as failure
```
Can you run R CMD check on your computer and see if you get the same error?

> I meant "<<<<<<< HEAD" and "=======" ... 

This is not a multi-line comment, and if they are in your code this is most likely causing the error. Did you have to perform a rebase at some point? This comes from git not R.

See here
http://stackoverflow.com/questions/7901864/git-conflict-markers

You should not have any of these lines in your final code.

**Comment by rwarnung** [comment]
@Stevo15025 your are right, I had some conflicts. as I said I am new to this process (which is a very good one).  I use git in R studio and the github desktop app. Could you tell me how I rebase in the cleanest way? Should I just download mlr devel and delte my project or what is the best way? I have copied the changes to a text file ... so I can easily add them to the files in an older state. Thank you!

**Comment by Stevo15025** [comment]
These links should give you an idea on how to rebase your branch to master. 

> press "update from mlr-org/master" - my files should be up to date.

 If you still have <<<<<<< HEAD" and "======="  in your code you ignored conflicts during merge and have redundant or conflicting code. If you are passing tests on Travis I'm guessing they are in the documentation. it may be best to reset to a commit before you merged, then use the docs below to rebase so you are up to date with master.

https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

https://git-scm.com/book/en/v2/Git-Branching-Rebasing

https://git-scm.com/docs/git-rebase

**Comment by rwarnung** [comment]
@Stevo15025 thanks for the links. I don't have the signs in my code .. this must be why it passes Travis. 
Maybe they somehow (via roxygen tags) slipped into the documentation? 
I am afraid that it is all quite complex now. Would it be ok (github wise) if I download the newest mlr-devel (https://github.com/mlr-org/mlr) and then just apply my changes to this afterwards? Can I use the same pull request or is it all just a mess now? Thank you very much for your help!

**Comment by Stevo15025** [comment]
The error was in the pdf creation, so your code itself is fine. Something seems to be wring in the .Rd files. Your build passes R CMD check on your desktop? Maybe you just need to run `devtools::document()` and push again.

When you have merge conflicts, never just copy and paste over the code. Resolve them manually. I would recommend using command line git in the future.

@larskotthoff manual.log in the workspace has a bunch of these warnings

```
pdfTeX warning (dest): name{Rfn.BreastCancer} has been referenced but does not 
exist, replaced by a fixed one
pdfTeX warning (dest): name{Rfn.Prediction} has been referenced but does not ex
ist, replaced by a fixed one
pdfTeX warning (dest): name{Rfn.agriculture} has been referenced but does not e
xist, replaced by a fixed one
```

Not sure if related to this?

**Comment by rwarnung** [comment]
@Stevo15025 thanks for your help. Locally the checks don't pass all functions (not with xgboost and not with some wrappers) but this is not my part.  On the other hand I did the call of devtools::document(). When I pushed back nothing changed on github ... it says that everything is up to date. I don't know what's wrong. It is just a pity ... I already had the multiclass functionality implemented (with tests) and it failed because there was a problem in the earth packages namespace. Using package = "!earth" (with the !) would have been the solution ... just one character ;) I don't know how to continue from here. Thanks for your help anyways.

**Comment by Stevo15025** [comment]
> Locally the checks don't pass all functions (not with xgboost and not with some wrappers) but this is not my part.

If master is passing and yours is not something is different in your branch. This can be due to your merge. I would check again.

Not sure what to do with the pdf error. Will have to wait for input from Lars

**Comment by larskotthoff** [comment]
The Jenkins error is a false positive. Looks all good, merging. Thanks both!

**Comment by larskotthoff** [comment]
I fixed some small style things (name of file, spacing) in https://github.com/mlr-org/mlr/commit/b3c16b98dab9e109ec3c665b52da7dd61a918982 -- please check these things next time.

**Comment by rwarnung** [comment]
@larskotthoff thanks for fixing the stlye and merging. My contributions will get better each time - hopefully :)

**Pull request merged**
