### PR TITLE
Added and adapted params in randomForest (#972)

### PR DESCRIPTION
**Pull request by MariaErdmann**
Solving #972 

- Added param "strata": I was not sure which kind of LearnerParam to take. I wanted to go for makeCharacterLearnerParam() but I think this one is depricated, so I chose Untyped. I chose this one because you specify strata by putting the name of the varaible you want to stratify for in. I looked here for an example of strata: https://stat.ethz.ch/pipermail/r-help/2005-October/081557.html

- Added param "proximity" and "oob.prox", which produces a (nxn) proximity measures matrix 
- Added param "nPerm" for regression.
-changed sampsize to IntegerVectorParam

- I did not add "keep.forest", since this one needs always to be true  in order to get predictions.

### CODE REVIEW

**Comment by MariaErdmann** [comment]
One of my commits said "added properties strata, proximity, oob.prox" --> of course I did not add properties. This should be "added params strata, proximity, oob.prox". Sorry for the confusion.

**Comment by MariaErdmann** [comment]
Regarding the "strata" argument: I still need to take a closer look at it. I will then create also a test. Will do this in the course of the week.

**Comment by larskotthoff** [comment]
Thanks, merging.

**Comment by berndbischl** [comment]
> Regarding the "strata" argument: I still need to take a closer look at it. I will then create also a test. Will do this in the course of the week.

@larskotthoff @MariaErdmann 
why is this merged then? was this now done or not?

**Comment by berndbischl** [comment]
> I did not add "keep.forest", since this one needs always to be true in order to get predictions.

this could be added. mlr could also be used with just training the model, but not predicting from it

**Comment by berndbischl** [comment]
also the issue is still open. i dont know how to proceed

**Comment by berndbischl** [comment]
> Well, this PR successfully closes the Issue. For everything else make a new issue if necessary.

if the PR creator says: "please wait, i am not done": we *wait*. an alternative would be to ask the creator. 

@MariaErdmann: please add comments what should be done from your side in the issue. ASAP. and also add keep.forest as a new param. do this in a new PR. 

i would like to resolve this soon.

**Comment by jakob-r** [comment]
>also add keep.forest as a new param. do this in a new PR. 

Then we also want this for ranger (and maybe others where predicting is optional)

**Comment by larskotthoff** [comment]
I didn't sound to me like "wait" (and this PR is completely standalone).

Shall we have a "ready-to-be-merged" label that we require to be added to avoid this?

**Comment by berndbischl** [comment]
> I didn't sound to me like "wait" (and this PR is completely standalone).
> 
> Shall we have a "ready-to-be-merged" label that we require to be added to avoid this?

our conclusion was: the PR creator should explicitly say whether he is done. otherwise we ask if we are unsure.

(at least for me this PR is an example of: "i am not done", at least it we should agree that it is not obvious whether maria is done here, so we should ask)

**Comment by MariaErdmann** [comment]
Sorry for the confusion and getting back a bit late.
The learners were ready to be merged (provided that I did everything right, which I was not sure about). But I would want to make a test testing whether the strata argument works properly. So this still needs to be done although you say there is no need.
Regarding the "keep.forest" param: Shall I add it?
I will do a new PR with the test and the "keep.forest" param when you say "go" ;-)

**Comment by berndbischl** [comment]
> But I would want to make a test testing whether the strata argument works properly. So this still needs to be done except you say there is no need.

you dont have to test every new learner param (i think we talked about this before?).
of course, mlr  options should be tested in general, but for learner params there are simply too many and also you dont do much more then simply pass "strata" down to the rf. 


> Regarding the "keep.forest" param: I will add it then, except there are objections.

ok, go. you can BRIEFLY look at ranger and randomforestsrc whether there we are missing the same param and add that too

**Comment by MariaErdmann** [comment]
> ok, go. you can BRIEFLY look at ranger and randomforestsrc whether there we are missing the same param and add that too

Resolved in PR #992

**Pull request merged**
