### PR TITLE
Relative error measures

### PR DESCRIPTION
**Pull request by catastrophic-failure**
Added the Root relative squared error measure and the Relative absolute error based on this answer http://stats.stackexchange.com/a/203187/60613.

These metrics are good to have in the package because they establish a baseline to compare results, i.e. if the relative error is above 1 you are doing worse than simply predicting the mean result.

- More measures can be added (e.g. Relative squared error)

- I could have used the already existing functions `measureSAE` and `measureSSE`, but I guess that wouldn't be optimal

- The measures won't work, for obvious reasons, with single instances (e.g. doing leave one out)

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks. Why didn't you want to use the existing functions and then normalise? It seems to me that this would result in less duplicated code. And I may be missing something obvious, but why won't this work with single instances?

**Comment by catastrophic-failure** [comment]
> Thanks. Why didn't you want to use the existing functions and then normalise? It seems to me that this would result in less duplicated code. 

Yes, I could do this, but while it's surely more readable, is it optimal? While I'm not sure how much measure evaluation is a resource drain, these aren't really complicated measures, I guessed calling functions wasn't necessary. But as I said I could just as well have called `measureSAE` and `measureSSE`, if it's the preferred path.

> And I may be missing something obvious, but why won't this work with single instances?

The denominator is proportional to the standard/mean absolute deviation of the `truth` vector. If it's a single stance it becomes zero.

**Comment by larskotthoff** [comment]
Not sure what you mean by optimal. I don't think a function call is going to cause a noticeable slowdown. My preference is to reduce code duplication as much as possible.

I got what you mean about the single instances now, but this is something that can occur in other cases as well. It would be great if you could check for that and provide a suitable error message in that case (and a test).

**Comment by catastrophic-failure** [comment]
@larskotthoff 

> Not sure what you mean by optimal. I don't think a function call is going to cause a noticeable slowdown. My preference is to reduce code duplication as much as possible.

Will do.

> I got what you mean about the single instances now, but this is something that can occur in other cases as well. It would be great if you could check for that and provide a suitable error message in that case (and a test).

The only other way it might happen is if there's a single unique `truth` value. I know it might happen by chance during resampling, but other measures breakdown upon that as well, such as `expvar`. What kind of error message should the measure output?

**Comment by larskotthoff** [comment]
It can happen if all truth values are equal to the mean.

The error message could be something like "Cannot normalise <measure> as all truth values are equal."

**Comment by catastrophic-failure** [comment]
@larskotthoff 
> It can happen if all truth values are equal to the mean.
Exactly, like I said.

> The error message could be something like "Cannot normalise as all truth values are equal."
Will do. Should we do it to Expvar too?

**Comment by larskotthoff** [comment]
The current code base can certainly be improved :)

If you want to, feel free to add similar error messages for the relevant other measures (in a separate PR please). But for this I consider it necessary.

**Comment by catastrophic-failure** [comment]
@larskotthoff I guess it should be a warning instead of an error then? Do resampling continue if the measure function return an error? As of now it accepts the NAs and report them as is.

**Comment by larskotthoff** [comment]
Ah, good point. Yes, let's make it a warning.

**Comment by berndbischl** [comment]
some comments:

1) if some measures fail, e.g. when executed on a single instance, MOST important is that we doc that.
i dont think we need much more here. you could output a warning. but note that warnings usually suck!

2) please doc the precise formula of the measure in the note. or explain it in words so that it is precisely clear. but i guess a formula is shorter.
the note could also mention the (orig) mlr measure that is normalized here. 

3) wrt the tests: i usually prefer REALLY manualy tests, without calling the copy-pasted R functions here. 
i can live with this, but would rather prefer a really handcrafted test.

4) if we are at it: can you add at least the MAPE as well? thats also used very often (sorry)

**Comment by catastrophic-failure** [comment]
@berndbischl 

> 1) if some measures fail, e.g. when executed on a single instance, MOST important is that we doc that.
i dont think we need much more here. you could output a warning. but note that warnings usually suck!

Will add warnings. About doc'ing, you mean the note, or the roxygen description, or something else?

> 2) please doc the precise formula of the measure in the note. or explain it in words so that it is precisely clear. but i guess a formula is shorter.

Could do either, the formula is quite short though, so perhaps it's preferable.

the note could also mention the (orig) mlr measure that is normalized here.

My local has it already, just need to push to the remote.

> 3) wrt the tests: i usually prefer REALLY manualy tests, without calling the copy-pasted R functions here.
i can live with this, but would rather prefer a really handcrafted test.

I'll add manual tests as well.

> 4) if we are at it: can you add at least the MAPE as well? thats also used very often (sorry)

Will do.

**Comment by catastrophic-failure** [comment]
@larskotthoff @berndbischl 
So, is this good enough?
```splus
measureMAPE = function(truth, response){
  if(all(truth != 0))  return(mean((abs(truth-response))/truth))
  warning("MAPE is undefined for actual values equal to 0!")
  return(NA)
}
```

**Comment by larskotthoff** [comment]
Either is fine with me, although I would prefer "truth values all equal" over "actual values equal".

**Comment by catastrophic-failure** [comment]
@larskotthoff 

> I got what you mean about the single instances now, but this is something that can occur in other cases as well. It would be great if you could check for that and provide a suitable error message in that case (and a test).

Now I'm writing this test, along with mape's test. What exactly should I test here? e.g test if it outputs `NA`s? Because the formula will actually return a `NaN` (`0/0`)

**Comment by larskotthoff** [comment]
Also test that you're getting the warning please.

**Comment by catastrophic-failure** [comment]
All right, what you think about this test?

```splus
expect_true(tryCatch(measureMAPE(0,0), warning = function(w) TRUE))
expect_true(tryCatch(measureMAPE(c(1,1,1,0),c(2,2,2,2)), warning = function(w) TRUE))
```

But I'm in doubt how to test that a valid entry doesn't output a warning.

**Comment by larskotthoff** [comment]
See https://stackoverflow.com/questions/22003306/is-there-something-in-testthat-like-expect-no-warnings

**Comment by catastrophic-failure** [comment]
If I output `NA`'s, they aren't equal to `NaN`'s, should we output `NaN`'s then?

**Comment by larskotthoff** [comment]
I think `NA`s are more suitable here.

**Comment by catastrophic-failure** [comment]
Then the handcrafted test and the measure won't agree: `expect_equal(NA, NaN)` throws an error.

**Comment by larskotthoff** [comment]
Well, you can change the handcrafted test accordingly and say that in a comment.

**Comment by catastrophic-failure** [comment]
The tests are
`expect_equal(mape.test, mape$fun(pred = pred.regr))`

And

` expect_equal(1/4*(abs((4-5)/5)+abs((11-10)/10)+abs((0-0)/0)+abs((4-5)/5)), measureMAPE(c(5, 10, 0, 5),c(4, 11, 0, 4)))`

I have no idea how to change the test without making it trivial. But obviously they aren't equal: one entry's a NA the other a NaN.

**Comment by larskotthoff** [comment]
So set the left hand side to `NA`. I don't see how this would be worse than the current test -- you're checking the value in a particular case.

**Comment by berndbischl** [comment]
> 1) if some measures fail, e.g. when executed on a single instance, MOST important is that we doc that.
> i dont think we need much more here. you could output a warning. but note that warnings usually suck!
> Will add warnings. About doc'ing, you mean the note, or the roxygen description, or something else?

i meant the note. that seems to be the only place where we can currently doc such objects. i am not too happy about this, but thats how it is for now.

i see you already have those notes in there. but its good to be precise. say that the measure will become NA in the "undefined case". dont leave that info out.




> 2) please doc the precise formula of the measure in the note. or explain it in words so that it is precisely clear. but i guess a formula is shorter.
> Could do either, the formula is quite short though, so perhaps it's preferable.

yes, formulas seem best.

**Comment by berndbischl** [comment]
style comment: after an "if" there goes a SPACE so, "if (foo)"

**Comment by larskotthoff** [comment]
Thanks, merging.

**Pull request merged**
