### PR TITLE
getFilteredFeatures works now on every Model Class

### PR DESCRIPTION
**Pull request by jakob-r**
Dealing with Issue #479

### CODE REVIEW

**Comment by berndbischl** [comment]
pushed back to 2.6. jakob currently reverts this

**Comment by larskotthoff** [comment]
What's the status here? Can/should this be merged?

**Comment by berndbischl** [comment]
We had problems. This needs to be severly reviewed by multiple people. And possibly discussed.

**Comment by larskotthoff** [comment]
The change in this PR is trivial; would it be useful to have?

**Comment by berndbischl** [comment]
there was some kind of a revert. we really need to check this IIRC and I am too tired now

**Comment by larskotthoff** [comment]
Is this ready to be merged? It would be good to have a test as well.

**Comment by larskotthoff** [comment]
@jakob-r @berndbischl What's the status of this? Merge?

**Comment by jakob-r** [comment]
I think this should still work and it is still a good idea. +1 for merge

**Pull request merged**
