### PR TITLE
fix plot tests

### LINKED ISSUE #1181: Re-enable and fix plot tests
The plot tests are currently broken and commented. To fix
- uncomment the code in the relevant files,
- see why the tests fail (most likely the xpath selector to get elements from the generated SVGs is broken, e.g. because of changed colour definitions)
- fix tests

### PR DESCRIPTION
**Pull request by larskotthoff**
Fixes #1181.

@zmjones Could you have a look at the partial dependence plots please? There are a few tests that fail there for real, i.e. there really are not as many plot elements as the tests expect. Did you change anything in the function?

### CODE REVIEW

**Comment by berndbischl** [comment]
are you serious? great! you just earned 5% of mlr stock options!

**Comment by larskotthoff** [comment]
Only 5% for about 2 hours of excruciatingly tedious work?

**Comment by berndbischl** [comment]
but they are worth millions...

**Comment by larskotthoff** [comment]
Ok, I'll just have the cash value then and retire.

**Comment by zmjones** [comment]
@larskotthoff yep I will check it out today.

**Comment by zmjones** [comment]
should be fixed now. i'd added some new features to the plots since we last had the plot tests enabled. 

i'll write tests for the other new plots when i get a chance.

**Comment by larskotthoff** [comment]
Sorry, looks like the tests are still failing...

**Pull request merged**
