### PR TITLE
Add unittests for fdaclassif 

### PR DESCRIPTION
**Pull request by lbeggel**
tests for response type "prob" and ROC measures

### CODE REVIEW

**Comment by smilesun** [comment]
@lbeggel @pfistfl  I think it is a better idea to put the unit test in one file which is called fda_base or some similar names, since we could 1 easily keep track of what we have to do to make FDA work like general ML and also keep track of what we have done   2. FDA is a seperate module, so we should keep it as more apart from others parts of mlr as possible, i.e. do not touch other files too much.  WHat do you two think?

Please add more unit test and finish the list I wrote once you have time.

**Comment by lbeggel** [comment]
The list you wrote is already complete. 
Ok, i will remove the tests in the individual files and create one base fda test.

**Comment by lbeggel** [comment]
Everything integrated in #1890

**Comment by smilesun** [comment]
since everything is integrated in #1890, this pr is not relevant anymore

**Pull request closed without merging**
