### PR TITLE
Fix Bug in critDiff plot, fixes #554, extend generateData function.

### LINKED ISSUE #554: Small bug with plotCritDifferences
See here 

```
library(mlr)
set.seed(1)
tasks = list(iris.task, sonar.task)

learners = list(
  makeLearner("classif.rpart"),
  makeLearner("classif.randomForest"),
  makeLearner("classif.svm")
)

rdesc = makeResampleDesc("CV", iters = 3)
br = benchmark(learners, tasks, rdesc)
r = generateCritDifferencesData(br, mmce, p.value = 0.1, test = "bd")
plotCritDifferences(r)

```

That produces
```
Cannot reject null hypothesis of overall Friedman test, returning overall Friedman test
Error in data.frame(x = numeric(0), y = 0.1, check.names = FALSE, stringsAsFactors = TRUE) : 
  arguments imply differing number of rows: 0, 1
In addition: Warning messages:
1: In is.na(e1) | is.na(e2) :
  longer object length is not a multiple of shorter object length
2: In `==.default`(df$learner.id, baseline) :
  longer object length is not a multiple of shorter object length
```

@pfistfl 

Can you pls fix and unit test this?

### PR DESCRIPTION
**Pull request by pfistfl**

### CODE REVIEW

**Comment by larskotthoff** [comment]
Ok, I'm rerunning the latest master build to see what's going on here.

**Comment by larskotthoff** [comment]
Master build is fine, don't know what's going on here. I'll try restarting the build.

**Comment by larskotthoff** [comment]
Right, works for me if I regenerate the documentation. Could you do that please? Might be something dodgy with our new Travis autogenerated documentation.

**Comment by larskotthoff** [comment]
I've fixed the documentation issue in the mlr master. If you rebase on that and push again, everything should work.

**Comment by pfistfl** [comment]
thanks, should work now.

**Pull request closed without merging**
