### PR TITLE
#537 added h2o learner

### PR DESCRIPTION
**Pull request by Coorsaa**
suggestion for NEWS 
````
new learners
-- classif.h2o.deeplearning
-- classif.h2o.gbm
-- classif.h2o.glm
-- classif.h2o.randomForest
-- regr.h2o.gbm
-- regr.h2o.glm
-- regr.h20.randomForest
````

makes Flo's pull request obsolete, can be closed.

### CODE REVIEW

**Comment by berndbischl** [comment]
Hi.
@Coorsaa please watch our for naming conventions. you use pCol in camel case. 
But we can fix that one thing after merge.

@ja-thomas can you also briefly review?

**Comment by ja-thomas** [comment]
Just a minor thing:
`beta_epsilon` in `h2oglm` hast to be nonnegative


What about the failing travis and Jenkins tests? The failing tests are passing on my machine. Seems to be an issue with the jvm on the CI servers?

**Comment by berndbischl** [comment]
please fix:

- vars not in camel case
- after "if" use a space so "if (foo)"
- rename the learners to classif.h2o.randomForest, with a "dot" (exactly as the function is named in the package)

**Comment by berndbischl** [comment]
. param "epsilon" must have lower = 0

**Pull request closed without merging**
