### PR TITLE
Fix #724: isFailureModel for ModelMultiplexer may fail.

### LINKED ISSUE #724: ModelMultiplexer errors not handled well when on.learner.error=="warn"
When the ModelMultiplexer `trainLearner` function throws an error and the `on.learner.error` mlr-config is set to "warn" or "quiet", the resulting object will cause errors when handled further:
```R
> configureMlr(on.learner.error="warn")
> ml = makeModelMultiplexer(list(makeLearner("classif.probit")))
> # If the classif.probit model throws an error, everything is fine.
> # If trainLearner.ModelMultiplexer itself throws an error, not so lucky.
> # The following is one way to make that happen.
> ml = removeHyperPars(ml, "selected.learner")  
> tml = train(ml, pid.task)
Warning in train(ml, pid.task) :
  Could not train learner ModelMultiplexer: Error in .learner$base.learners[[selected.learner]] : 
  invalid subscript type 'symbol'

> isFailureModel(tml)  # expected: TRUE
Error in model$learner.model$next.model (from WrappedModel.R#102) : 
  $ operator is invalid for atomic vectors
> tml  # expected: not an error
Model for learner.id=ModelMultiplexer; learner.class=ModelMultiplexer
Trained on: task.id = PimaIndiansDiabetes-example; obs = 768; features = 8
Hyperparameters: 
Error in model$learner.model$next.model (from WrappedModel.R#102) : 
  $ operator is invalid for atomic vectors
```

### PR DESCRIPTION
**Pull request by mb706**
So this clashes with PR #709, funnily enough, but the merge is trivial.

### CODE REVIEW

**Comment by larskotthoff** [comment]
@berndbischl This looks like it can be merged to me.

**Comment by berndbischl** [comment]
> @berndbischl This looks like it can be merged to me.

why are you saying this when travis fails here?

**Comment by berndbischl** [comment]
i have rebased this on master. but this still fails, also locally, the unit test for the test_tune_ModelMultiplexer

**Comment by larskotthoff** [comment]
Travis was fine when I had a look.

**Comment by larskotthoff** [comment]
Should be fixed now.

**Comment by berndbischl** [comment]
again:
 configureMlr(on.learner.error = "warn")

please really dont "reconfigure" mlr during unit tests. either ask for the option, store it, then reset it at the end.

**Comment by larskotthoff** [comment]
Done.

**Comment by berndbischl** [comment]
underscores in var names are against the style guide...

i will quickly fix this

**Pull request merged**
