### PR TITLE
Fix for 1522 (Impute types)

### PR DESCRIPTION
**Pull request by mllg**

### CODE REVIEW

**Comment by mllg** [comment]
Also: Detect if storage type has changed and throw an exception if this is the case (e.g., was numeric, now is logical for re-imputation).

**Comment by jakob-r** [comment]
#1522

**Comment by jakob-r** [comment]
> Running examples in ‘mlr-Ex.R’ failed

**Comment by jakob-r** [comment]
The changes made a change in the example necessary. 
If a column of a data.frame only contains NAs they are not of any specific type so the imputation will change it's type and create an error message - the one that we introduce here.
Is that a behavior that we want?

**Comment by jakob-r** [comment]
We talked and @mllg convinced us that this is a corner case that only happens if the user manually imputes/predicts on a data.frame with all-NA-columns. But thanks to the example code a solution is already given.

**Pull request merged**
