### PR TITLE
Fix for smote's wrong labeling of constant factors

### LINKED ISSUE #1951: Error in SMOTEing constant Features
I am still not sure if this is a bug or if I just misunderstood the smote function. 
Please take a look at the following snippet

```
Class = c(rep("1", 150), rep("2", 50))
x = c(rep("No", 125), rep("Yes", 75))
data = data.frame("Class" = Class, "X" = x)
task = makeClassifTask(data = data, target = "Class", positive = "2")

table("Class" = data$Class, "X" = data$X)

     X
Class  No Yes
    1 125  25
    2   0  50

taskOvr = smote(task, rate = 3)
dataOvr = getTaskData(taskOvr)
table("Class" = dataOvr$Class, "X" = dataOvr$X)

     X
Class  No Yes
    1 125  25
    2 100  50
```

So my tasks consists of 1/4 positive observations of class "2" and 3/4 negative observations of class "1". 
After applying the smote function the task is balanced but here's the point. I've always thought the oversampling is only happening in the space of the positve points. And since all the positive points have a X value of "Yes", all the synthetic points of class "2" should have the value "Yes" as well?
Am I wron or should the data structure after Smote look like this?
```
     X
Class  No Yes
    1 125  25
    2   0  150
```

### PR DESCRIPTION
**Pull request by AlexEngelhardt**
I added a comment to issue #1951 why it happens. Briefly, assigning levels to integers does not work in the current code. What should be E,E,F,F becomes A,A,B,B:

```
> x <- as.factor(c(4,4,5,5))
> levels(x) <- LETTERS[1:5]
> x
[1] A A B B
Levels: A B C D E
```

This PR is a fix for that bug and a unit test reproducing it. 

Again, I'm new to this, so handle with care. Feedback welcome. *Edit:* Specifically, feedback on why Travis seems to fail for tests I haven't touched :) This didn't happen on my machine.

Fixes #1951

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks. Looks good, but I'll wait until the batchmark problems are fixed before merging.

**Comment by AlexEngelhardt** [comment]
Alright. Is there any way I can be of help there?

**Comment by larskotthoff** [comment]
Not really -- merge master once the tests are passing and push again, that should take care of it.

**Comment by AlexEngelhardt** [comment]
ping @larskotthoff 

Okay, Janek's fix did the trick.

**Comment by larskotthoff** [comment]
Thanks, merging.

**Pull request merged**
