### PR TITLE
Revamp cdplot

### PR DESCRIPTION
**Pull request by pfistfl**
- R CMD check.  Everything but the following runs smoothly.
```
 WARNING
'qpdf' is needed for checks on size reduction of PDFs
```

- In regards to the changes: package ```PMCMR``` was updated to v.4.0. I updated the functions so     hypothesis tests / unit tests still work.

- ```pretty.names``` arg was added for ```plotCritDifferencesData``` function

- moved hypothesis Test into two seperate files ```friedmanTestBMR.R``` and  ```friedmanPostHocTestBMR.R```. File names now equal to function names

- added new convenience function ```getBMRLearnerShortNames(bmr)``` For the pretty.names arg.

- ```plotCritDifferencesData``` does not use ```vjust``` in annotate() anymore and should be more stable.

- revised UnitTests for hypothesis tests and CritDifferencesPlot. Should not be stochastic anymore.
- Now using ```checkBMRMeasures()``` where possible

### CODE REVIEW

**Comment by schiffner** [comment]
@berndbischl asked me to review.

My first test was to install this branch and try to build the tutorial. I encountered this error in `generateCritDifferencesData`:
```
set.seed(4444)

## Create a list of learners
lrns = list(
  makeLearner("classif.lda", id = "lda"),
  makeLearner("classif.rpart", id = "rpart"),
  makeLearner("classif.randomForest", id = "randomForest")
)

## Get additional Tasks from package mlbench
ring.task = convertMLBenchObjToTask("mlbench.ringnorm", n = 600)
wave.task = convertMLBenchObjToTask("mlbench.waveform", n = 600)

tasks = list(iris.task, sonar.task, pid.task, ring.task, wave.task)
rdesc = makeResampleDesc("CV", iters = 10)
meas = list(mmce, ber, timetrain)
bmr = benchmark(lrns, tasks, rdesc, meas, show.info = FALSE)
bmr

g = generateCritDifferencesData(bmr, p.value = 0.1, test = "nemenyi")

# Error in `$<-.data.frame`(`*tmp*`, "yend", value = c(1.5, 0.5)) : 
#   replacement has 2 rows, data has 3

# Enter a frame number, or 0 to exit   

# 1: generateCritDifferencesData(bmr, p.value = 0.1, test = "nemenyi")
# 2: `$<-`(`*tmp*`, "yend", value = c(1.5, 0.5))
# 3: `$<-.data.frame`(`*tmp*`, "yend", value = c(1.5, 0.5))
```

The problem (just a missing index vector on the left) is in this line: https://github.com/pfistfl/mlr/blob/f4f69922605efb90424f7ec2251bd62eaf74cac0/R/plotCritDifferences.R#L75

**Comment by berndbischl** [comment]
I will take over this branch now and finalize and merge.
This is mine now, everybody please stay away.

**Comment by schiffner** [comment]
I can continue reviewing when you are done.

**Comment by berndbischl** [comment]
Julia, can you kinda try to do that / as soon as possible? Because this is kinda blocking the upload, and me testing the package as a whole.
(I mean reading and pointing stuff out)

I am at a workshop now and have to fight for time windows but promised Uwe to upload today (well and also promised to you guys)

**Comment by schiffner** [comment]
Ok, can do this first thing tomorrow, will comment in #695.

**Comment by berndbischl** [comment]
OK if you really wait this, I will check all of the rest stuff and wait until then

**Pull request closed without merging**
