### PR TITLE
Tut: Only one tutorial version

### LINKED ISSUE #2372: tutorial (release) sec. 3.16.2 says it is about pima indians but code is about mtcars
3.16.2:  text

In the example below, we tune the number of clusters against the silhouette score on the Pima dataset. We
specify the x-axis with the x argument and the y-axis with the y argument. If the plot.type argument is
not specified, mlr will attempt to plot a scatterplot by default. Since plotHyperParsEffect() returns a
ggplot2::ggplot() object, we can easily customize it to our liking!

code uses mtcars.task:

library("clusterSim")
ps = makeParamSet(
makeDiscreteParam("centers", values = 3:10)
)
ctrl = makeTuneControlGrid()
rdesc = makeResampleDesc("Holdout")
res = tuneParams("cluster.kmeans", task = mtcars.task, control = ctrl,
measures = silhouette, resampling = rdesc, par.set = ps, show.info = FALSE)
data = generateHyperParsEffectData(res)
plt = plotHyperParsEffect(data, x = "centers", y = "silhouette.test.mean")
### add our own touches to the plot
plt + geom_point(colour = "red") +
ggtitle("Evaluating Number of Cluster Centers on mtcars") +
scale_x_contin

### LINKED ISSUE #2379: tic needs the most recent github version after git2r update
`git2r` got updated on the 10th of July. To get `tic` working with it (i.e. the doc deployment), we need the latest Github version of `tic`. This is already done in #2370 

Note: There will a CRAN release of `tic` in the next 2 months of `tic` (hopefully) that should stabilize its behavior. However, issues like this that are caused by an update of `git2r` will always apply.

### PR DESCRIPTION
**Pull request by pat-s**
As requested by Bernd.

- Only maintain one tutorial version (devel). No backups of old `mlr` versions. 
- This decreases build time of the HTML tut by 50% because we do not have to build the release version 
- No PDF tutorial anymore

I hope that I catched all links that need to be changed :duck: 
 

#### Other fixes

- We currently have a "chicken & egg" problem updating `penalized` on Travis. It requires a specific version of `survival`. Only running `devtools::install_deps(update = T)` does not seem to affect all packages installed including `survival`. Using `install.packages(old.packages())` updates all packages installed in the Travis cache.
- `R_MAX_NUM_DLLS=999` is not required anymore since the limit was raised since R v3.5.0
- `tic` problems have been fixed in the repo so we can use the latest github version again
- Tidy README

fixes #2379 
fixes #2372

### CODE REVIEW

**Comment by larskotthoff** [comment]
Why no backup of old versions anymore? Does this affect build time too?

**Comment by berndbischl** [comment]
@larskotthoff our setup is just too complicated. and most of this is not used at all

**Comment by larskotthoff** [comment]
Why does keeping copies of old versions complicate things? Do we have any data on it not being used?

**Comment by pat-s** [comment]
> Why does keeping copies of old versions complicate things? Do we have any data on it not being used?

This does not really complicate things but the practical question is: Who does ever specifically use a tutorial from a previous version? I am not biased towards keeping or not keeping, this is a small point anyways. 

Btw, the decision to drop the PDF tut also solves the sidebar ToC problem of the HTML tut because without the PDF tut we can again start with h1 for the HTML tutorial. I'll change this as well.

**Comment by berndbischl** [comment]
also have a look at how much "script code" patrick could remove here. that is also a burden....
i am currently lookin at the irace bug, but we should merge this here soon

**Comment by berndbischl** [comment]
can we please merge this really soon? it becomes huge and scary....

**Comment by pat-s** [comment]
Maybe someone can have a final look at it? From my perspective it's ready to merge. The page about the "mlr outreach" can be optimized in a new PR.

**Comment by pat-s** [comment]
> The build is failing (no output received for 10 minutes) 

This is a really annoying one - I did not change anything important to the `rcmdcheck` execution. I'll ssh into the build later on and try to debug..

**Comment by pat-s** [comment]
Ok, I tracked it down (after 4h of detective work and 2 PRs (https://github.com/r-lib/rcmdcheck/pull/72, https://github.com/ropenscilabs/tic/pull/64):

Because we now have the tutorials directly under `vignettes/`, `rcmdcheck()` also builds the vignettes during `R CMD build`. The output however is not shown as it only starts with the `R CMD check` sequence.

Building the vignette is (1) unnecessary for us because we check all the vignettes in the tutorial stage and (2) takes longer than 10 mins -> that's why the build times out due to no output to the console.

I fixed it for now by using two forks of mine (one enables passing args to `R CMD build` which we can use to suppress the vignette building) that contain both PR fixes. Hopefully they get accepted soon and then we can roll back to the official versions.

**Comment by berndbischl** [comment]
thx a lot for investing time here - i know the feeling.
does this mean that you think that travis should now work - i just restarted the job, again key problems and fail after 1 min

**Comment by berndbischl** [comment]
travis still breaks :(

**Comment by berndbischl** [comment]
is this now also blocking my cran upload?

**Comment by pat-s** [comment]
> again key problems and fail after 1 min

That's random travis behavior

> is this now also blocking my cran upload?

no, this PR should not block anything.
You just need to check if the check stage in the `master` build is really "green", i.e. checking for failing tests. There is still one left: 

> ── 1. Error: learners work: classif (@test_learners_all_classif.R#65)  ─────────
> argument "hyperpars" is missing, with no default
> 1: lapply(lrns, testBasicLearnerProperties, task = min.task) at testthat/test_learners_all_classif.R:65
> 2: FUN(X[[i]], ...)
> 3: lrn$id %in% names(hyperpars) at /tmp/RtmpcVYz7o/file2f1f6213768a/mlr.Rcheck/tests/testthat/helper_learners_all.R:60

We can merge this PR also after the CRAN release. It just tidys the tutorial and travis build (e.g. only one warmup stage). 

I'll let you know when I think we are ready here (hopefully today).

**Comment by berndbischl** [comment]
are we ready now? travis seems to be green

**Comment by pat-s** [comment]
I would prefer to first merge #2378 also because I am not available until late in the evening today. 

But other than that we are ready here.

**Comment by berndbischl** [comment]
@pat-s i am beginning to "hate" that you do so many different things, which are all "orthogonal" in this single PR....
can you please try to aboid that in the future?
dont want to be impolite, and really appreciate all the work, just gets very confusing to review and to get done at the same time

**Comment by berndbischl** [comment]
this might be very stupid but i will merge this in now and repair in master
please help?

**Comment by pat-s** [comment]
> i am beginning to "hate" that you do so many different things, which are all "orthogonal" in this single PR....
> can you please try to aboid that in the future?

Yes, sorry for this. Sometimes I just stumble over things while working on sth and then "just" fix it in the current PR. I should better note it and make a separate PR that contains only the "small fixes" then.

**Pull request merged**
