### PR TITLE
Multilabel-RandomForestSRC

### PR DESCRIPTION
**Pull request by PhilippPro**
This is the implementation of the Multilabel-RandomForestSRC algorithm.

I also included some tests.

### CODE REVIEW

**Comment by berndbischl** [comment]
Why close? Erroneous PR?
Please always communicate.

**Comment by PhilippPro** [comment]
Sry. I just saw two tiny errors.
Will make a new request.

Am 29.01.2016 um 16:55 schrieb Bernd Bischl:

**Comment by berndbischl** [comment]
Why dont you simply update your branch? Then you dont need to close the PR, right?

**Comment by berndbischl** [comment]
And write "please wait I am fixing some stuff!"" here

**Comment by PhilippPro** [comment]
Ok. My problem is I do not know how to merge two commits to one commit 
and you do not like several commits in on PR. So I delete my branch and 
make a new commit. Probably this is stupid.

Am 29.01.2016 um 16:57 schrieb Bernd Bischl:

**Comment by berndbischl** [comment]
0) If you need to know stuff, you know, asking is often a reasonable option....

1) Have you read this?
https://github.com/mlr-org/mlr/wiki/mlr-Coding-Guidelines
Quote:
Commits squashed into 1 with a meaningful commit message, see https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

2) It becomes a bit easier, if I give you access rights as a contributor. Then you can work in a branch instead of a fork. I will do that now.
But: make SURE you read the wiki page linked in 1) in toto and ask if you are unsure about something

**Pull request closed without merging**
