### PR TITLE
add functional anova

### PR DESCRIPTION
**Pull request by zmjones**
this is ready for a little reviewing now. the only major thing i think worth discussing is how i reused some of the existing code. i gave the output two classes, one new "FunctionalANOVAData" and the other "PartialDependenceData". The output is so similar (unsurprising given the former uses the latter heavily) that the plot functions can be re-used with essentially no modification. i could, however, not do this, and instead write a wrapper with a name that matches the generation function., `plotFunctionalANOVA`.

### CODE REVIEW

**Comment by zmjones** [comment]
i've rebased this now

**Comment by zmjones** [comment]
ping @berndbischl and @larskotthoff 

could we merge this relatively soon? this is one of the things i need to write my job market paper and so is somewhat time sensitive!

**Comment by larskotthoff** [comment]
Thanks, looks good. Sorry, missed this earlier.

**Comment by zmjones** [comment]
no worries! thanks!

**Comment by berndbischl** [comment]
@zmjones 
if this is merged now, can you please also explain this at least BRIEFLY in the tutorial pretty soon?
otherwise people just miss this.

do you need a new issue for this?

**Comment by zmjones** [comment]
No I will get to it asap

**Pull request merged**
