### PR TITLE
Fix 1093 refactor random forest filters

### PR DESCRIPTION
**Pull request by jakobbossek**
- Renamed `rf.importance` filter to `randomForestSRC.var.rfsrc`
- Renamed `rf.min.depth` filter to `randomForestSRC.var.select`
- Marked renamed filters as deprecated
- Added test for #1066
- Added some expect statements to featsel_filters test.
- Replaced `rf.impurity` and `rf.accuracy` filters (introduced yesterday) by a single `randomForest.importance` filter with a `method` parameter.

Going to address the missing docs for all filters in a detached PR.

### CODE REVIEW

**Comment by jakobbossek** [comment]
@berndbischl Review now! 😉

**Comment by berndbischl** [comment]
this looks good. should be merged when travis is done.

a) we should not forget NEWS
b) do you want an issue for the docs stuff?

**Comment by jakobbossek** [comment]
> a) we should not forget NEWS

This is your job once the PR is merged 😉 

b) do you want an issue for the docs stuff?

I already opened #1099. However, just realized that #826 already exists. I am going to close the latter now. One issue is enough.

**Comment by jakobbossek** [comment]
@larskotthoff What about that quickcheck error on travis? (there is no package called 'quickcheck')

**Comment by larskotthoff** [comment]
Travis-weirdness. Should be fixed when merging or rebasing.

**Comment by berndbischl** [comment]
warning("getFilterValues is deprecated. Use generateFilterValuesData.")

shouldnt that warning be  a call to deprecated?
(i know its old code)

**Comment by jakobbossek** [comment]
@berndbischl Fixed in e710a40

**Comment by jakobbossek** [comment]
Damn!

Undocumented code objects:
  makePrediction
All user-level objects in a package should have documentation entries.
See chapter â€˜Writing R documentation filesâ€™ in the â€˜Writing R
Extensions™ manual.

**Comment by larskotthoff** [comment]
Working on fixing this now.

**Comment by jakobbossek** [comment]
@larskotthoff  Thanks for fixing.

**Comment by larskotthoff** [comment]
Thanks, merging.

**Pull request merged**
