### PR TITLE
Add learner RRF

### PR DESCRIPTION
**Pull request by pfistfl**
Note: 
The added learner offers stratified resampling. As I understand, this is done internally in mlr.
This is why I did not include those parameters. 
If I should add them, please say so.

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks. Could you please also mention in NEWS? I see that there are a few FIXME comments in the code that could be done now -- please do that. It also looks like the unit tests are failing.

**Comment by pfistfl** [comment]
Will mention in NEWS,
For stratified resampling, should I include the parameters?
Unit tests and R CMD check worked for me, gonna check back again.

**Comment by larskotthoff** [comment]
I would include all the parameters a user may want to change.

**Comment by zmjones** [comment]
Yes you should definitely include those parameters. mlr's stratified resampling could approximate something like this if you could grow single RRF trees which could be then combined using a wrapper which uses stratified resampling, however this may be slower if it is possible at all.

**Comment by berndbischl** [comment]
We should always try to include as many params as possible.

**Comment by pfistfl** [comment]
included all params, gonna push.

 For
strata: 	A (factor) variable that is used for stratified sampling
Is there a better alternative to using ```makeUntypedLearnerParam``` ? 
Feels like it should be discrete, but I have neither a specified ```len``` nor any ```values```

**Comment by larskotthoff** [comment]
I guess we need data-dependent parameters for this. Untyped is ok for now.

**Comment by berndbischl** [comment]
Note that you can create a vector param without a specified length, by setting len = NA.
Just mentioning this so people know this. 

But in this case I would also set it to untyped, due to the fact that we really have no appropriate type match in paramhelpers. 

Doesnt strata exist for the normal randomForest? Shouldnt we add it there as well?
Probably in a different issue / PR though.

**Comment by zmjones** [comment]
@berndbischl You cannot with randomForest but can with cforest (in party). I don't think it works with rfsrc (in randomForestSRC).

With cforest you can do stratification by constructing and passing an appropriate bootstrap weighting matrix but not by passing a factor. I think this works with the stochastic boosting in mboost as well but can't remember for sure.

**Comment by berndbischl** [comment]
I just looked it up with ?randomForest? 
There is a "strata" param and we dont not cover it in classif.randomForest and regr.randomForest yet?

**Comment by zmjones** [comment]
woops missed that

**Comment by pfistfl** [comment]
I can not get to run ```R CMD check ``` for the latest mlr Version.

```
git clone https://github.com/mlr-org/mlr.git 
```
and 
```
R CMD build mlr
R CMD check mlr_2.5.tar.gz
```

Which produces the same Warnings Travis produces for this branch.
(https://travis-ci.org/mlr-org/mlr/builds/88647078)
```
...
* checking Rd files ... WARNING
checkRd: (5) generateThreshVsPerfData.Rd:0-55: Must have a \description
checkRd: (5) getBMRLearnerIds.Rd:0-41: Must have a \description
checkRd: (5) getBMRLearners.Rd:0-41: Must have a \description
checkRd: (5) getBMRMeasureIds.Rd:0-41: Must have a \description
checkRd: (5) getBMRMeasures.Rd:0-41: Must have a \description
checkRd: (5) getBMRTaskIds.Rd:0-41: Must have a \description
checkRd: (5) getClassWeightParam.Rd:0-28: Must have a \description
checkRd: (5) getHyperPars.Rd:0-33: Must have a \description
checkRd: (5) getMlrOptions.Rd:0-16: Must have a \description
checkRd: (5) makeCostMeasure.Rd:0-57: Must have a \description
checkRd: (5) mergeSmallFactorLevels.Rd:0-40: Must have a \description
checkRd: (5) plotCalibration.Rd:0-66: Must have a \description
checkRd: (5) plotROCCurves.Rd:0-69: Must have a \description
checkRd: (5) plotThreshVsPerf.Rd:0-60: Must have a \description
checkRd: (5) plotThreshVsPerfGGVIS.Rd:0-65: Must have a \description
* checking Rd metadata ... OK
...
```

**Comment by larskotthoff** [comment]
But the checks for the master branch succeed? https://travis-ci.org/mlr-org/mlr/builds/88379809

**Comment by pfistfl** [comment]
Yes. No Idea what I got wrong. Opened  different PR #555 to fix #554.
Lets see what Travis says, as changes there are minimal.

**Comment by larskotthoff** [comment]
Same thing here as for the other PR -- if you rebase on the mlr master and push again, it'll work.

**Comment by pfistfl** [comment]
Going to reopen aswell in order to get a clean commit

**Pull request closed without merging**
