### PR TITLE
Tuning methods

### PR DESCRIPTION
**Pull request by rgmantovani**
I coded three optimization methods for hyper-parameter tuning. All of them just handle numeric and integer hyper-parameters:
- **tuneGA** (using [GA] (https://cran.r-project.org/web/packages/GA/index.html) R package): a real-valued Genetic Algorithm. User can set some of the GA's parameters, such as: mutation probability, crossover probability, population size and the number of generations.
- **tunePSO** (using [pso] (https://cran.r-project.org/web/packages/pso/index.html) R package  ): a standard real-valued Particle Swarm Optimization 2007/2011 by Maurice Clerc et al [paper] (http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6557848&tag=1). User can set parameters, such as: the PSO type (2007 or 2011 standard), the number of swarm particles and the number of generations.
- **tuneEDA** (using [copulaedas](https://cran.r-project.org/web/packages/copulaedas/index.html) R package ): some Estimation of Distribution Algorithms that use copula and vine functions. User can specify which EDA he would like to use: UMDA, GCEDA, CVEDA or DVEDA. It is also possible to define the number of iterations and population size.

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks, looks good! Some comments:

- Could you please add a note in NEWS?
- You'll need to add the `copulaedas` package to `DESCRIPTION` and regenerate the doxygen documentation for everything to work correctly.
- Some of your error messages are wrapped across multiple lines, i.e. contain a newline character. Could you make them single-line please?
- In at least one place you're using `if(...)` (no space before opening parenthesis), which our dear leader, @berndbischl, doesn't like.

**Comment by berndbischl** [comment]
at the end also please squash the commits into a single one

**Comment by berndbischl** [comment]
shouldnt we also reference the packages / methods that are used in the TuneControl documentation?

**Comment by rgmantovani** [comment]
I already did the modifications. It just remains the "commits squashing" .

**Pull request closed without merging**
