### PR TITLE
move mmpf to suggests

### PR DESCRIPTION
**Pull request by zmjones**
for issue #2144 

all i do here is assume mmpf is installed and reference it using ::. is there a helper function i should use to throw a informative error message if it isn't installed? i know `requirePackageOrSkip` but that is in the test helper functions. i guess it will just say "mmpf::whateverfunction" isn't found by default.

### CODE REVIEW

**Comment by mb706** [comment]
I think what you're looking for is [`requirePackages`](https://www.rdocumentation.org/packages/BBmisc/functions/requirePackages), already imported from `BBmisc`.

**Comment by zmjones** [comment]
@mb706 cool thanks!

**Comment by larskotthoff** [comment]
Thanks, could you also move it from import to suggests please?

**Comment by zmjones** [comment]
yep ready for merge

**Comment by larskotthoff** [comment]
Thanks, merging.

**Pull request merged**
