### PR TITLE
Fixes survival learners from penalized package (somewhat related to #840)

### PR DESCRIPTION
**Pull request by florianfendt**
The survival learners from the penalized package were broken.
E.g: They were throwing an error for factor features.
@MariaErdmann detected this while she was working on #874 and we fixed it together.

### CODE REVIEW

**Comment by larskotthoff** [comment]
For the tests, since you're modifying the data in all of them, could you move that to one of the helper files so we don't have that much duplicated code please?

**Comment by florianfendt** [comment]
Yes ok, will do. I wasn't so sure if we wanted that. Thanks

**Comment by berndbischl** [comment]
please dont merge this, there are general problems here

**Comment by berndbischl** [comment]
handled better in #931

**Pull request closed without merging**
