### PR TITLE
Update `RLearner_classif_h2odeeplearning.R`

### LINKED ISSUE #2658: h2o.deeplearning early stopping: stopping_rounds is missing?
Doesn't seems to be `stopping_rounds` in `getParamSet("classif.h2o.deeplearning")`.
I'm aware of `classification_stop` but it's not the same.
Am i missing something here?

### PR DESCRIPTION
**Pull request by albersonmiranda**
Added params.

fixes #2658

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks, looks good. Could you also please add at least some of the new parameters to the tests for this learner?

Are these parameters relevant for the regression learner as well? If so, it would be great if you could add them to that as well please.

**Comment by jakob-r** [comment]
We should check, because some of these "new" ones were already in the regr learner.

**Comment by albersonmiranda** [comment]
@jakob-r i just verified and all of them are already set in regr learner, except for `stopping_rounds` which is se as integer in regr and i've set as numeric with another default. It worked locally but i'll make it match regr just in case.

**Comment by jakob-r** [comment]
> Also, there's a few more `stopping_metric` values in documentation (which i've added in classif.) that aren't defined for regr.

I would assume that `"deviance", "logloss", "MSE", "RMSE", "MAE", "RMSLE"` are stopping metrics for `regr` and not `classif`. Unfortunately the h2o documentation does not give hints here.

> `stopping_rounds` which is set as integer in regr and i've set as numeric with another default. It worked locally but i'll make it match regr just in case.

It might work because h2o converts it but certainly e.g. 43.4 would not be a plausible value.

**Comment by berndbischl** [comment]
Log loss is for classify... Come on... Deviance probably too

**Comment by jakob-r** [comment]
My bad. But deviance seems to be for regression according to [this page](http://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/deep-learning.html) Although I do not understand the "formula".

**Comment by berndbischl** [comment]
i was wrong. deviance is for regression. i think it should be possible to use it also for classif, but maybe not supported, maybe simply test it for 1 min.

also i had to stare 5 min at the formula to understand it

Loss = Quadratic -> MSE==Deviance For Absolute/Laplace or Huber -> MSE != Deviance

you have to read it like this

if loss=l2, then mse == dev
if loss=l1 or huber, then mse!=dev

**Comment by pat-s** [comment]
Whats the status here?

@albersonmiranda Will you incorporate the changes from Jakob?

**Comment by albersonmiranda** [comment]
@pat-s sorry for the delay. Updated  `stopping_metric` as Jakob pointed out and added `distribution` with values `c("bernoulli", "multinomial")`. I'm not sure if others available make sense for classification problems.

Also, `c("bernoulli", "multinomial")` distributions and `"logloss",  "AUC", "misclassification"` `stopping_metric`s are defined for regression. Do you agree to open a PR to exclude them?

**Comment by jakob-r** [comment]
From my side it is related enough to do it in one PR

**Comment by albersonmiranda** [comment]
Done!

**Comment by pat-s** [comment]
Thanks for contributing!

**Pull request merged**
