### PR TITLE
Revamp cdplot rebased

### PR DESCRIPTION
**Pull request by mllg**
Please check thoroughly before merging, the rebase was a little cumbersome.

### CODE REVIEW

**Comment by berndbischl** [comment]
Ok, I am not going to squash the commits here.

Things I noticed and have to fix now:
1) Julias bug in the other PR
2) getBMRLearnerShortNames has no test
3) NEWS needs to be changed

**Comment by schiffner** [comment]
In `generateCritDifferencesData`:
https://github.com/mlr-org/mlr/blob/c88c88630f56af4a26d354923ea59d70a094c557/R/plotCritDifferences.R#L66:
`as.data.frame(t(` is unnecessary (`tranp.rankmat` is never used again, anyway).
In l. 67 `colMeans` then needs to be replaced by `rowMeans`.

**Comment by schiffner** [comment]
https://github.com/mlr-org/mlr/blob/c88c88630f56af4a26d354923ea59d70a094c557/R/plotCritDifferences.R#L69: `cbind` is unnecessary.

**Comment by schiffner** [comment]
https://github.com/mlr-org/mlr/blob/c88c88630f56af4a26d354923ea59d70a094c557/R/plotCritDifferences.R#L86:
As only the first minimum is needed one could use `which.min`.

**Comment by schiffner** [comment]
https://github.com/mlr-org/mlr/blob/c88c88630f56af4a26d354923ea59d70a094c557/R/plotCritDifferences.R#L103:
It doesn't hurt, but I don't think that transposing is necessary here.

**Comment by schiffner** [comment]
´plotCritDifferences´:
https://github.com/mlr-org/mlr/blob/c88c88630f56af4a26d354923ea59d70a094c557/R/plotCritDifferences.R#L196:
I doubt that the `[1]` at the end is needed. If yes, it should also be added in l. 96.

**Comment by schiffner** [comment]
One could maybe encapsulate the aggregation (e.g. here: https://github.com/mlr-org/mlr/commit/c88c88630f56af4a26d354923ea59d70a094c557#diff-83e099620baaa8b3dbd52aba3a6fc7afR25) of performances in a new helper function. It's used in both `friedman*TestBMR` functions and `convertBMRToRankMatrix`.

**Comment by schiffner** [comment]
The docs of `friedman*TestBMR`, `generateCritDifferencesData`, `plotCritDifferences` need some improvements. It's probably easiest if I just do a commit in this branch after you are done, Bernd.

**Comment by schiffner** [comment]
I just checked if changing the `baseline` in `plotCritDifferences` works. Unfortunately, it doesn't.

```
## corrected version of generateCritDifferencesData because of bug reported in PR #643
generateCritDifferencesData = function (bmr, measure = NULL, p.value = 0.05, baseline = NULL, 
    test = "bd") 
{
    assertClass(bmr, "BenchmarkResult")
    assertChoice(test, c("nemenyi", "bd"))
    assertNumeric(p.value, lower = 0, upper = 1, len = 1)
    measure = checkBMRMeasure(measure, bmr)
    transp.rankmat = as.data.frame(t(convertBMRToRankMatrix(bmr, 
        measure)))
    mean.rank = colMeans(transp.rankmat)
    df = data.frame(cbind(mean.rank), learner.id = names(mean.rank), 
        rank = rank(mean.rank, ties.method = "average"))
    right = df$rank > median(df$rank)
    df$yend[!right] = rank(df$rank[!right], ties.method = "first") - 
        0.5
    df$yend[right] = rank(desc(df$rank[right]), ties.method = "first") - 
        0.5
    df$xend = ifelse(!right, 0, max(df$rank) + 1L)
    df$right = as.numeric(right)
    df$short.name = getBMRLearnerShortNames(bmr)
    if (is.null(baseline)) {
        baseline = df$learner.id[df$rank == min(df$rank)][1L]
    }
    else {
        assertChoice(baseline, getBMRLearnerIds(bmr))
    }
    nem.test = friedmanPostHocTestBMR(bmr, measure, p.value)
    cd.info = list(test = test, cd = nem.test$crit.difference[[test]], 
        x = df$mean.rank[df$learner.id == baseline], y = 0.1)
    if (test == "nemenyi") {
        sub = sort(df$mean.rank)
        mat = apply(t(outer(sub, sub, `-`)), c(1, 2), FUN = function(x) ifelse(x > 
            0 && x < cd.info$cd, x, 0))
        xstart = round(apply(mat + sub, 1, min), 3)
        xend = round(apply(mat + sub, 1, max), 3)
        nem.df = data.frame(xstart, xend, diff = xend - xstart)
        nem.df = ddply(nem.df, .(xend), function(x) x[which.max(x$diff), 
            ])
        nem.df = nem.df[nem.df$xend - nem.df$xstart > 0, ]
        nem.df$y = seq(from = 0.1, to = 0.35, length.out = dim(nem.df)[1])
        cd.info$nemenyi.data = nem.df
    }
    makeS3Obj("CritDifferencesData", data = df, cd.info = cd.info, 
        friedman.nemenyi.test = nem.test, baseline = baseline, 
        p.value = p.value)
}

library(checkmate)
checkBMRMeasure = mlr:::checkBMRMeasure

lrns = list(
  makeLearner("classif.lda", id = "lda"),
  makeLearner("classif.rpart", id = "rpart"),
  makeLearner("classif.randomForest", id = "randomForest")
)

tasks = list(iris.task, sonar.task)
rdesc = makeResampleDesc("CV", iters = 3)
bmr = benchmark(lrns, tasks, rdesc, show.info = FALSE)
bmr

g = generateCritDifferencesData(bmr)
plotCritDifferences(g)
plotCritDifferences(g, baseline = "rpart")
```

In both plots the critical differences bar is positioned around "rf".

**Comment by berndbischl** [comment]
ok, l 196 simply needs to be changed

**Comment by berndbischl** [comment]
@schiffner 
OK I pulled it now. Would you maybe be so kind, to look at this a bit closer? 
It annoys me a bit that I dont really understand all lines in the code and I have not enough time currentyl to look at this closely.

I will open up a new issue for you, ok?

**Pull request merged**
