### PR TITLE
Make it possible for makeTuneControlGrid resolution to be vector

### LINKED ISSUE #1921: resoultion in makeTuneControlGrid
In the help for makeTuneControlGrid it says for resolution:
"Either pass one resolution for all parameters, or a named vector."

But if I pass a named vector 
makeTuneControlGrid(resolution = c(x1 = 4, x2 = 5))

I get the error
Error in makeTuneControlGrid(resolution = c(x1 = 4, x2 = 5)) : 
  Assertion on 'resolution' failed: Must have length 1.

### PR DESCRIPTION
**Pull request by mb706**
Fix #1921

### CODE REVIEW

**Comment by berndbischl** [comment]
wow trhat was quick
but lets not remove the arg check completely?

**Comment by berndbischl** [comment]
one can make an or-combo with assert()

**Comment by mb706** [comment]
whats up with travis?

**Comment by pat-s** [comment]
> whats up with travis?

thats because trusty is now the default and we did not yet account for it

removing `- mkdir $HOME/bin` should help

see also #1912

**Pull request merged**
