### PR TITLE
Ranger hyperparameter sample.fraction

### PR DESCRIPTION
**Pull request by PhilippPro**
Added it also for regression and survival

### CODE REVIEW

**Comment by berndbischl** [comment]
@larskotthoff 
please lets check these thing in review....

**Comment by larskotthoff** [comment]
Looks good to me -- it's a small enough change.

**Comment by berndbischl** [comment]
> Looks good to me -- it's a small enough change.

sure, but please check this type of consistency in review.
like 
"ok, he did this change, does he have to do exactly the same place else?"
we dont want to have the param included for the one ranger learner, but not for the 2 others.

thats what the review is supposed to be for ;-)

**Comment by larskotthoff** [comment]
Yes. Did I miss that in some other PR?

**Comment by berndbischl** [comment]
> Yes. Did I miss that in some other PR?

not that i know of, and we are still friends, and i am not cranky ;-)
just saying to make sure

**Comment by berndbischl** [comment]
(well, you missed it in the PR directly before this, about the same issue for ranger but that is clear right?)

**Comment by larskotthoff** [comment]
Ok, fair point. I assumed that the PR-opener would check this :)

**Comment by PhilippPro** [comment]
responsabilities are always delegated. ;)

**Comment by berndbischl** [comment]
> Ok, fair point. I assumed that the PR-opener would check this :)

always "actively" search for potential problems in the PR.
I always assume the PR is wrong until I am 100% convinced otherwise.

**Pull request merged**
