### PR TITLE
ksvm: add cache parameter

### PR DESCRIPTION
**Pull request by jakob-r**

### CODE REVIEW

**Comment by berndbischl** [comment]
Please add to NEWS and squash. 
(Actually the cache can affect the runtime measures, but lets keep tuneable = FALSE)

**Comment by jakob-r** [comment]
done

**Comment by berndbischl** [comment]
Well spotted for "regr." Merging.

**Comment by berndbischl** [comment]
1) The names are much too long now. Note that they will appear in objects and prints. 
test.rmseaggr? 
That was my best output after 10 secs of thought? 

2) You also need to add the NAMESPACE, for travis. See break.

**Pull request merged**
