### PR TITLE
multiclass AUC measures

### PR DESCRIPTION
**Pull request by Coorsaa**
basically the same as #910 .

suggestion for news:

````
new multiclass measures:
-- multiclass.au1p
-- multiclass.au1u
-- multiclass.aunp
-- multiclass.aunu
removed multiclass measures:
-- multiclass.auc renamed to multiclass.au1u
````

### CODE REVIEW

**Comment by berndbischl** [comment]
- please remove combs and use utils::combn

- please in colAUC follow the style guide for variable names etc

- please document what colAUC actually computes. describe signature!

- add in notes 1 sentence to explain what the different measures actually do

**Comment by berndbischl** [comment]
@Coorsaa 
please mention the status here when you push. ready to be merged? you still working on this?

**Comment by Coorsaa** [comment]
@berndbischl 
should be ready for your review.

>- please remove combs and use utils::combn

Done.

>- please in colAUC follow the style guide for variable names etc

Done, changed all capital letters to small ones

>- please document what colAUC actually computes. describe signature!

Done in colAUC.R

>- add in notes 1 sentence to explain what the different measures actually do

Done in measures.R

**Comment by kdpsingh** [comment]
I ran into problems with the multiclass AUCs recently. Glad to see this issue is being worked on. Eager for it to be merged!

**Pull request merged**
