### PR TITLE
expanded test_base_getTaskData, test_base_getHyperpars, test_base_multilabel

### PR DESCRIPTION
**Pull request by IcedragonP**
in test_base_getTaskData: same things for multilabel like for survival.
in test_base_getHyperpars: The default case with no hyperpars.
in test_base_multilabel: imputeWrapper and hyperpars for both cases

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks. Could you add some expectations for the new multilabel tests please?

**Comment by IcedragonP** [comment]
done.

**Comment by larskotthoff** [comment]
Looks like one of the tests you've added fails.

**Comment by larskotthoff** [comment]
Thanks, merging.

**Pull request merged**
