### PR TITLE
fix ModelMultiplexer with predict.type = prob for basellearners, fixe…

### PR DESCRIPTION
**Pull request by berndbischl**
…s #609

### CODE REVIEW

**Comment by larskotthoff** [comment]
Could you also add a test for the error condition please?

**Comment by berndbischl** [comment]
Lars, I dont know what you mean

**Comment by berndbischl** [comment]
I added 1 sentence to docs to explain better what happens and squashed

**Comment by larskotthoff** [comment]
There's no test that checks if an error is generated when more than one predict type is given.

**Comment by berndbischl** [comment]
Sigh. Ok

**Comment by berndbischl** [comment]
ok, pls review again added test + squashed

**Comment by larskotthoff** [comment]
Looks good. I'll merge when Travis is done.

**Comment by berndbischl** [comment]
Its not an API change. Do we still add this to NEWS?

**Comment by larskotthoff** [comment]
I wouldn't. Maybe as a bug fix if you want to?

**Comment by berndbischl** [comment]
Well, I mean I think you told me before that we should mention these things?
And of course ala "We fixed a bug in .... which was ..."

**Comment by larskotthoff** [comment]
Fair enough. I'll merge and add this.

**Pull request merged**
