### PR TITLE
Add `na.rm` flag to remove NAs during resample aggregation

### PR DESCRIPTION
**Pull request by pat-s**
# Blocked by #2600 	

#1887 

New attempt of #1980 

When the user sets the `na.rm` flag in `resample()`, all error measures will remove `NA`s encountered during runs and return a numeric value instead of `NA`. 

```r
task = sonar.task
  
rdesc = makeResampleDesc("RepCV", folds = 3, reps = 2)
  
lrn = makeLearner("classif.binomial",
                  link = "logit",
                  predict.type = "prob")
  
resa = resample(lrn, task, rdesc, measures = list(auc, mmce),  na.rm = T)
```

### CODE REVIEW

**Comment by ja-thomas** [comment]
Hi,

just as a note, your Unit tests are not running: `Total time 11 min 44 sec`.

Do you have the most recent version of the mlr master in your fork? My hunch is that your fork was at the time Travis was broken.

**Comment by pat-s** [comment]
> just as a note, your Unit tests are not running:

(This time) I am aware of this, I just wanted to verify this with the last commit 👍  I will rebase with master next and then check all unit test problems

**Comment by pat-s** [comment]
Blocked by #2600

**Comment by pat-s** [comment]
I do not really have the time to dig deeper here. 
A bit sad, I was so close...

Didn't know which can of worms I opened when I started this PR back then :sweat:

**Pull request closed without merging**
