### PR TITLE
cleanup measures and extend tests

### PR DESCRIPTION
**Pull request by giuseppec**
This is a pull-request for: https://github.com/mlr-org/mlr/issues/1005

We might need to discuss this issue before merge https://github.com/mlr-org/mlr/issues/1016. For TPR, for example:

``` r
bincombo = matrix(c(TRUE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, FALSE), ncol = 2, byrow = TRUE)
bincombo
#      [,1]  [,2]
#[1,]  TRUE FALSE
#[2,]  TRUE  TRUE
#[3,] FALSE  TRUE
#[4,] FALSE FALSE

# without the 4th line, TPR corresponds to the worst value
measureMultilabelTPR(bincombo[-4,], !bincombo[-4,])
#[1] 0

# 4th line yields a denominator of 0 for the computation of the TPR
measureMultilabelTPR(bincombo, !bincombo)
# [1] 0.25
```

For `measureMultilabelTPR(bincombo, !bincombo)` one would expect that either the worst TPR value from `multilabel.tpr$worst` (which is 0) is returned or `NaN` (when denominator is zero).

### CODE REVIEW

**Comment by larskotthoff** [comment]
Is this ready to be merged?

Do I see it correctly that most of the new unit tests are simply comparing the old implementation to the new implementation? Do we really need this?

**Comment by berndbischl** [comment]
the code cleanup is good. 
but please, instead of the for loops in the tests, add handcrafted simple examples.

see what i did around lines 309 for brier score and logloss

**Comment by berndbischl** [comment]
@giuseppec 
what is the status here? i want to merge this soon

**Comment by giuseppec** [comment]
Status: still waiting for an answer in https://github.com/mlr-org/mlr/issues/1016 regarding what to do in the corner cases for **multilabel** TPR and PPV. 

Because currently, we are doing this:

```r
(y = matrix(c(TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE), 4, 2))
#      [,1]  [,2]
#[1,]  TRUE  TRUE
#[2,] FALSE  TRUE
#[3,] FALSE FALSE
#[4,]  TRUE  TRUE
(pred1 = matrix(c(TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE), 4, 2))
#      [,1] [,2]
#[1,]  TRUE TRUE
#[2,] FALSE TRUE
#[3,] FALSE TRUE
#[4,]  TRUE TRUE
(pred2 = matrix(c(TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE), 4, 2))
#      [,1]  [,2]
#[1,]  TRUE  TRUE
#[2,] FALSE  TRUE
#[3,] FALSE FALSE
#[4,]  TRUE FALSE

measureMultilabelTPR(y, pred1)
# [1] 1

measureMultilabelTPR(y, !y) # the worst tpr value should be 0, right?
# [1] 0.25

measureMultilabelPPV(y, pred2) 
# [1] 1

measureMultilabelPPV(y, !y) # the worst ppv vlaue should be 0, right?
# [1] 0.5
```

Is it okay that we return the values above? If yes, I will push my local comit, otherwise we should decide what to do.

**Comment by smilesun** [comment]
if we change the code like this, the result will make sense
```
bincombo = matrix(c(TRUE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, FALSE), ncol = 2, byrow = TRUE)
truth = bincombo
response = !bincombo
numerator = rowSums(truth & response)  # 1&1 is 1, which is the only possible case
denominator = rowSums(truth)
t = numerator/denominator # I prefer to use apply here  

mean(ifelse(denominator == 0, 1, t)) # generate 0.25
ifelse(sum(denominator) == 0, 1, mean(t)) # generate NA
```

After this, we need to deal with the NA case

**Comment by smilesun** [comment]
Another option would be` ifelse(sum(denominator) == 0, 1, mean(t, na.rm = TRUE))` in this case it generate 0 as expected by ignoring the label with only negative samples.

**Comment by smilesun** [comment]
@berndbischl  ping

**Comment by giuseppec** [comment]
@berndbischl and I agreed on letting 0/0 be NaN and using na.rm = TRUE when taking the mean (currently we replace the NaN with 1). This is also what the guys from the mldr package are doing (see https://cran.r-project.org/web/packages/mldr/vignettes/mldr.pdf). 
We also need to write a test that compares our measures from the ones from the mldr package.

**Comment by berndbischl** [comment]
@giuseppec 
are the corner cases for the measures documented? 
otherwise can be merged

**Comment by giuseppec** [comment]
@berndbischl I added a sentence (in the note of the measure) stating what happens when the denominator becomes 0.

**Pull request merged**
