### PR TITLE
Fix broken travis by xgboost

### PR DESCRIPTION
**Pull request by hetong007**
Fix the broken Travis caused by `xgboost`.

### CODE REVIEW

**Comment by hetong007** [comment]
It seems that the `xgboost` issue has been resolved. But the error in the example remains.

**Comment by larskotthoff** [comment]
Hmm, all I see are lots and lots of warnings about mtry. I'll run the build again.

**Comment by larskotthoff** [comment]
I'm also seeing lots of warnings like

    makeRLearner.classif.xgboost: warning in makeRLearnerClassif(cl =
    "classif.xgboost", package = "xgboost", par.set =
    makeParamSet(makeUntypedLearnerParam(id = "params", default =
    list()), makeDiscreteLearnerParam(id = "booster", default = "gbtree",
    values = c("gbtree", "gblinear")), makeIntegerLearnerParam(id =
    "silent", default = 0), makeNumericLearnerParam(id = "eta", default =
    0.3, lower = 0), makeNumericLearnerParam(id = "gamma", default = 0,
    lower = 0), makeIntegerLearnerParam(id = "max_depth", default = 6,
    lower = 0), makeNumericLearnerParam(id = "min_child_weight", :
    partial argument match of 'par.val' to 'par.vals'

**Comment by larskotthoff** [comment]
Seems to be fine apart from that typo.

**Comment by hetong007** [comment]
Sorry for the typo! I have fix it now. In the log file the error from the example remains, and there's no warning/error on `xgboost`'s learners now. It seems the `mtry` messages are caused by the error.

**Comment by larskotthoff** [comment]
Thanks. I'll merge this and investigate what's going on with the other stuff.

**Comment by larskotthoff** [comment]
Ok, it seems that the source of the messages are your hill climbing tests. I've fixed it now I hope. Two things for the future:

- Never *ever* use `listLeaners()` with `create = TRUE` in a test. This will load *all* the packages and break everything because the maximum number of DLLs will be reached.
- List the learners you use for testing explicitly and make sure that they are cheap to run. If you use `listLearners()` the learners that are being tested will change as the package develops and lead to unexpected behaviour. Keep the unit tests cheap and as predictable as possible.

I should have caught this when checking your PR for this though, so it's really my fault :)

**Comment by hetong007** [comment]
Oh I see. Thank you very much for pointing that out! I am still on the way learning about every piece of `mlr`, and I will keep it in mind.

**Pull request merged**
