### PR TITLE
fix binaryToFeatures (Part of #2468)

### PR DESCRIPTION
**Pull request by jakob-r**
Clean up the code as most parts arent used anymore. Add a check to avoid unwanted vector recycling.

### CODE REVIEW

**Comment by larskotthoff** [comment]
Can you add a test please?

**Comment by jakob-r** [comment]
Hmm. It's an internal function which is already called numerous times by other tests. And it seems that it is never triggered (fortunately). But I probably could write a test with a wrong bits.to.features function.

**Comment by larskotthoff** [comment]
That would be great, in particular for unwanted vector recycling.

**Comment by berndbischl** [comment]
how do you know that this is correct? you just removed the matrix case.
sure that this not used on parallelization?

**Comment by berndbischl** [comment]
can we try to fix the problem in issue #2468 here too?

**Comment by jakob-r** [comment]
@berndbischl We could. But I would still like to seperate the two things. First lets do the basic stuff a bit better and afterwards we have to fix the FeatSelResult.
I would do a second PR after this here is accepted.

**Comment by berndbischl** [comment]
Totally good and agreed

**Comment by larskotthoff** [comment]
Thanks, merging.

**Pull request merged**
