### PR TITLE
Fix dropped weights

### LINKED ISSUE #1850: changeData ignores weights for multiclass task
because of a bug in changeData. This probably has other ramifications as well.

### PR DESCRIPTION
**Pull request by mb706**
Should fix #1850

### CODE REVIEW

**Comment by berndbischl** [comment]
why not add clustering in the tests?

**Comment by mb706** [comment]
I remembered there was one kind of task without weights. It turned out to be costsens, not cluster, but for some reason I removed both.

**Comment by mb706** [comment]
Can be merged as soon as tests pass imho.

**Comment by larskotthoff** [comment]
Cluster task is still missing from the tests?

**Comment by berndbischl** [comment]
> Cluster task is still missing from the tests?

yup pls add

**Comment by mb706** [comment]
Isn't `noclass.task` a cluster task? What change exactly do you guys want me to make?

**Comment by berndbischl** [comment]
> Isn't noclass.task a cluster task?

yes. and sorry!

**Comment by larskotthoff** [comment]
Argh, sorry, should have given that task a better name...

**Pull request merged**
