### PR TITLE
Added regr and classif evtree and tests

### PR DESCRIPTION
**Pull request by catastrophic-failure**
I saw `evtree` in the potential learners in the Wiki, so I decided to implement it. The tests were mostly copied from `cforest`, so expect some changes.

### CODE REVIEW

**Comment by catastrophic-failure** [comment]
I've tracked the error locally, have to delve into `testSimple` to understand what's going on. The last commit won't solve it yet.

**Comment by larskotthoff** [comment]
Thanks. Where did you get the parameters from? They don't seem to be documented.

**Comment by catastrophic-failure** [comment]
> Thanks. Where did you get the parameters from? They don't seem to be documented.

Yes, the documentation of this library is lacking several important bits. I'm using the defaults defined in the functions `evtree` and `evtree.control`.

**Comment by larskotthoff** [comment]
Ok, thanks. Merging.

**Pull request merged**
