### PR TITLE
Add probabilities to RLearner_classif_mxff

### PR DESCRIPTION
**Pull request by bklppr**
Add the possibility to predict probabilities for `RLearner_classif_mxff`.
See also #1120 and #1789.

### CODE REVIEW

**Comment by ParasSipani** [comment]
I can't understand how this is related to problem I reported #1825.

**Comment by ja-thomas** [comment]
@bklppr the error has nothing to do with your code (yet). 

You can restart the build by clicking on Details selecting the build and there should be a small symbol in the right upper corner. 

You have to do that yourself as you are working on a fork.

**Comment by bklppr** [comment]
@ParasSipani It's not related at all, I didn't reference your issue. Not quite sure what happened here.

@ja-thomas I don't see the symbol when I click on Details:
bildschirmfoto 2017-06-04 um 18 43 58

Am I missing something here?

**Comment by ja-thomas** [comment]
You need to sign in to Travis (that works with your github credentials) then there should be a button right under "more options"

But actually I don't think this willl solve the problem as the master is currently erroring as well...

**Comment by bklppr** [comment]
I signed in and this is all I get:
bildschirmfoto 2017-06-04 um 19 12 36

**Comment by larskotthoff** [comment]
Looks good to me, merging.

**Comment by bklppr** [comment]
Thanks @larskotthoff !

**Pull request merged**
