### PR TITLE
Travis: Fix allow_failures

### PR DESCRIPTION
**Pull request by pat-s**
If the tutorial fails, the Travis build should still succeed. 
This did not happen in https://travis-ci.org/mlr-org/mlr/builds/370688009

I did some testing and found out that the cause for this is a slightly wrong specification of the "env" setting in the stages. 

It now works as desired: https://travis-ci.org/mlr-org/mlr/builds/371611368

### CODE REVIEW

**Comment by larskotthoff** [comment]
Hang on, I'm not sure if I agree. If the tutorial fails, something should fail to let us know that something is wrong. And if the tutorial fails because of the change in mlr, this build should fail.

**Comment by larskotthoff** [comment]
Ok, do we still need this PR then?

**Comment by pat-s** [comment]
Yes, I'll change it here 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by larskotthoff** [comment]
Thanks, merging.

**Pull request merged**
