### PR TITLE
Add param "keep.forest" to randomForest, ....

### PR DESCRIPTION
**Pull request by MariaErdmann**
... "write.forest" to ranger, "forest" to randomForestSRC

In ranger: added "write.forest". The default is FALSE, but mlr default is now set to TRUE, to enable making predictions. Note is adpated accordingly. Please, check the wording.

This is ready to be merged if everything is correct and wording of note is alright.

### CODE REVIEW

**Comment by jakob-r** [comment]
- [ ] ranger_classif
- [ ] ranger_regr
- [ ] ranger_surv
- [ ] randomForest_classif
- [ ] randomForest_regr
- [ ] randomForestSRC_classif
- [ ] randomForestSRC_regr
- [ ] randomForestSRC_surv
- [ ] randomForestSRCSyn_regr
- [ ] added notes
- [ ] good par.vals
- [ ] removed unnecessary stuff

**Comment by larskotthoff** [comment]
These arguments rely on a recent version of ranger, don't they? Could you please update the version number for ranger accordingly in DESCRIPTION?

**Comment by berndbischl** [comment]
i will just rely on the newest version of ranger now. and merge. i guess we do not have to mention this in NEWS

**Comment by berndbischl** [comment]
> i will just rely on the newest version of ranger now. and merge.

done

**Pull request merged**
