### PR TITLE
Better print for predictions (fixes #1049)

### LINKED ISSUE #1049: Prediction object (and others?) better printer
we currently display the data with a call to "head" in the printer.
can be confusing to users, when they think this is the complete data.

we should end with something like

... (100 rows, 5 cols)

### PR DESCRIPTION
**Pull request by jakobbossek**
The `head` output is now followed by a single line mentioning the number of rows and columns in the data.frame as proposed by @berndbischl in #1049.

### CODE REVIEW

**Comment by jakobbossek** [comment]
- Added helper `printHead` in utils.R.
- Use it in printer for Prediction and LearningCurveData

**Comment by berndbischl** [comment]
ok, i like this.

i have also found this. can you take a look?

R/Prediction.R
195:  print(head(as.data.frame(x)))

R/generatePartialDependence.R
475:  print(head(x$data))
605:  print(head(x$data))

R/generateLearningCurve.R
100:  print(head(x$data))

R/ModelMultiplexer.R
48:#' print(head(as.data.frame(res$opt.path)))

R/ResamplePrediction.R
54:  print(head(as.data.frame(x)))

R/generateFilterValues.R
93:  print(head(x$data))

R/tuneParams.R
47:#' print(head(as.data.frame(res$opt.path)))
48:#' print(head(as.data.frame(res$opt.path, trafo = TRUE)))
50:#' print(head(generateHyperParsEffectData(res)))
51:#' print(head(generateHyperParsEffectData(res, trafo = TRUE)))
69:#' print(head(as.data.frame(res$opt.path)))
76:#' print(head(as.data.frame(res$opt.path)))

R/generateHyperParsEffect.R
129:  print(head(x$data))

**Comment by jakobbossek** [comment]
Sure

**Comment by jakobbossek** [comment]
The calls in R/tuneParams.R and R/ModelMultiplexer.R are located in the @examples section. Not changing this, since `printHead` is not exported.

**Comment by berndbischl** [comment]
> The calls in R/tuneParams.R and R/ModelMultiplexer.R are located in the @examples section. Not changing this, since printHead is not exported.

of course, this was simply a hasty output from my ack.... sorry

**Pull request merged**
