### PR TITLE
Move Paramhelpers from Depends to Imports

### PR DESCRIPTION
**Pull request by pat-s**
To avoid the autoloading of ParamHelpers when calling `library(mlr)`.

### CODE REVIEW

**Comment by jakob-r** [comment]
Okay. But then users have to load ParamHelpers manually as soon as they want to define ParamSets etc. So this would break a lot of old code once people get this update. Also this would have to be made clear in the tutorial etc.
I don't think this is a good idea. Why is it even necessary?

**Comment by jakob-r** [comment]
@berndbischl @mllg Thoughts?

**Comment by berndbischl** [comment]
i dont know. i have the feeling we are changing way too much for "maintenance mode"?
@mllg ?

**Comment by pat-s** [comment]
My thoughts to this:

- One can do a lot in _mlr_ without _ParamHelpers_
- In mlr3 we also have to load _paradox_ externally now
- We get rid of the "loading required package" message
- People would become more aware for what ParamHelpers is actually there for and would load it on purpose (I've come across a bunch of cases where people asked me what this message actually says or what this package does)

Downside: This can be seen as a breaking change to older scripts since one would need to add `library(ParamHelpers)` now in scripts before constructing a ParamSet

**Comment by jakob-r** [comment]
All the arguments seem to be minor inconveniences in comparison to the annoyance it will create for many users. I think about batch(tool) scripts that suddenly fail, stackoverflow answers that have to be edited, tutorial pages that have to be edited. Of course it is an easy fix if the people are aware of ParamHelpes. But you specifically say that this PR is targeted towards beginners or people that are confused by loading messages. Imagine what those kind of people will think if they suddenly see `ParamSet function not found`
So I very much vote for _no merge_.

**Comment by pat-s** [comment]
OK I agree, this will cause more confusion than it helps.
Thanks @jakob-r for bringing this up.

**Comment by berndbischl** [comment]
Agreeing with Jakob

**Comment by jakob-r** [comment]
:raised_hands:

**Pull request closed without merging**
