### PR TITLE
add cluster.DBScan learner

### PR DESCRIPTION
**Pull request by larskotthoff**
Issue #130 is hopefully fixed with this.

### CODE REVIEW

**Comment by larskotthoff** [comment]
I think the error is related to the class names parameter arguments. I cannot reproduce this on my machine and will check this later.

**Comment by berndbischl** [comment]
can reproduce on my uni laptop but dont know how to help

**Comment by berndbischl** [comment]
travis fails, pls repair.
in such cases, run a full local rtest with all groups locally. 
always at least "base" (but here it might be in the featsel test group)

**Comment by larskotthoff** [comment]
Ok, apparently the latest 3 versions of the DBScan package (1.0.5, 1.0.4, 1.0.3) don't work. 1.0.1 works fine.

**Comment by berndbischl** [comment]
Ok, so you mainly exhanged the DBscan package here? (downgrade?).

Great that you also added a note. 

Can you pls squash, so we can then merge for 2.6?

**Comment by larskotthoff** [comment]
Well anybody who installs the DBScan package the normal way and doesn't read the note (i.e. everybody) will get this unhelpful error message. I'm wondering whether it's a good idea to include something that by default will be broken for most people. We could have a more prominent warning about the package version.

The `fpc` package implements DBScan as well, so that's probably the better thing to include?

**Comment by berndbischl** [comment]
Ok, I didnt think about this. 

> The fpc package implements DBScan as well, so that's probably the better thing to include?

Yes, agreed.

**Comment by berndbischl** [comment]
One way to deal with this here, might be to internally try to catch that error msg and then inform people about the downgrade / version problem. But that might be a lot of effort for something we are not really responsible... OTOH it might finally close this here.

**Comment by larskotthoff** [comment]
Yep, will do that. I'll have a look at integrating the other DBScan later on.

**Comment by berndbischl** [comment]
Sure you want to close here?

**Comment by larskotthoff** [comment]
Yep. Not worth it, especially given that we have an alternative implementation we can use.

**Pull request closed without merging**
