### PR TITLE
#235 Control which class is over- or undersampled

### PR DESCRIPTION
**Pull request by florianfendt**

### CODE REVIEW

**Comment by berndbischl** [comment]
we agreed: 
- cl must be a class name, not "min" or "max", default is NULL, that implies the smaller or larger class, depending on the function
- first assert on cl is: either NULL or string
- later, when we have the data we check wether it truely is a class name

**Comment by florianfendt** [comment]
@berndbischl 
changed what we discussed. Open for review

**Comment by berndbischl** [comment]
I will merge this on the CLI now, that way it is easier for me to review

**Comment by berndbischl** [comment]
1) Please dont use testNull when is.null exists

**Comment by berndbischl** [comment]
2) Please have a look at how I am shortening the code of oversample() and undersample() now.

**Comment by berndbischl** [comment]
3) one thing one can notice here, is that the "finer" more subtle thing of how the sampling works are actually underdocumented. I will fix this now.

**Comment by berndbischl** [comment]
4) Please note that assertString exists

**Comment by berndbischl** [comment]
branch is on my laptop, must be uploaded NOW
imbalancy_add_arg_to_select_sampled_class

**Comment by berndbischl** [comment]
merged on console. we should be done here.

**Pull request closed without merging**
