### PR TITLE
add two new learners for xgboost 

### PR DESCRIPTION
**Pull request by hetong007**
`xgboost` is back on CRAN now. So I want to add it back here. The code has passed the local check.

Besides, I think the name of the file `R/RLearner-classif_nnTrain.R` is a typo, so I changed it into `R/RLearner_classif_nnTrain.R`.

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks, merging. Please don't put several independent things into one pull request in the future though.

**Comment by larskotthoff** [comment]
Hang on, that actually fails tests (see https://s3.amazonaws.com/archive.travis-ci.org/jobs/74090306/log.txt). No idea why Travis says the build succeeded. Could you have a look at that please? Open a separate PR for the fixes.

**Comment by hetong007** [comment]
Oh sorry, I am look into that right now.

**Comment by hetong007** [comment]
At the 3701th line:https://travis-ci.org/mlr-org/mlr#L3071, there's also an error on the example:

```r
> pred = lapply(fit, predict, task = iris.task)
> names(pred) = c("rpart", "nnet")
> out = generateCalibrationData(pred, groups = 3)
Error in requirePackages("Hmisc", default.method = "load", why = "Equal width binning of probabilities.") : 
  For Equal width binning of probabilities. please install the following packages: Hmisc
Calls: generateCalibrationData ... generateCalibrationData.list -> lapply -> FUN -> requirePackages -> stopf
```

Do you think this is relevant to this PR?

**Comment by larskotthoff** [comment]
I don't think so -- this is probably caused by the maximum number of DLLs reached error again.

**Pull request merged**
