### PR TITLE
New Learner: added GAM(binary classification) learner

### PR DESCRIPTION
**Pull request by rishy**
Not sure, whether this is already working properly. I was getting some error on my local machine while running the tests. It's something related to mgcv::gam, which basically doesn't allows the usage of '.' in formula. Can anyone help me with the work around?

### CODE REVIEW

**Comment by zmjones** [comment]
looks like you accidentally committed `tests.Rcheck/00check.log`

**Comment by rishy** [comment]
@zmjones, yeah, that was a mistake, let me just fix that up. Any thoughts about the error I was getting earlier: regarding mgcv::gam?

**Comment by zmjones** [comment]
can we close this?

**Comment by larskotthoff** [comment]
Well, it needs to be fixed if we want to merge it.

**Comment by zmjones** [comment]
for some reason i thought we already had mgcv gams integrated

**Comment by berndbischl** [comment]
Huh? Why can I not click on the details link to see why the test has failed?

"The repository at berndbischl/mlr was not found."

**Comment by larskotthoff** [comment]
Hmm, looks like this was run before we moved the repo. Somebody needs to push again or open a new PR.

**Comment by larskotthoff** [comment]
No activity in 4 months. I'll close this; we can open a new PR if we want this learner.

**Pull request closed without merging**
