### PR TITLE
new function getOutOfBag, related to issue #338

### PR DESCRIPTION
**Pull request by florianfendt**
This is not really finished, since I'm still not sure if we should rather add 2 functions
````getOOBPredictions```` and ````getOOBError````.
Right now ````getOutOfBag```` returns both predictions and error rates in a list.
Opinions?

### CODE REVIEW

**Comment by zmjones** [comment]
Just do the prediction extraction. Then we can apply whatever measure we
like.

**Comment by berndbischl** [comment]
1) Lets be more specific with property names. lets use property name "oobpreds".

**Comment by berndbischl** [comment]
Actually lets wait here. We need to decide what to to get probs. We need to define the API here first.

**Comment by PhilippPro** [comment]
> what to to get probs
What do you mean with that? 
In Classification case probabilities would be nicer so we can calculate any measure. 
These are directly provided at least by rfsrc, ranger and randomForest. 
But maybe it would be nice to have also the opportunity to get only the bare predictions.

**Comment by PhilippPro** [comment]
Ok, in my opinion, the result of the "getOutOfBag" function should be of the same format like the result of the "predict" function (could be with probabilities or not), so the same things (e.g. the function "performance") can be applied on this object.

**Comment by larskotthoff** [comment]
@PhilippPro @berndbischl What's the status here?

**Comment by berndbischl** [comment]
1) this needs to be transformed into a branch so we can all work on it

2) for the unit tests, we need a unit test helper function like in helpers_learners_all

**Comment by berndbischl** [comment]
3) we really dont want to compute the oob error manually in each getOOBfunction, simply return the predictions

4) we also need a way to return OOB probabilities i guess

**Pull request closed without merging**
