### PR TITLE
Featuer: add `getLearnerNote()` to access Notes information of learners

### PR DESCRIPTION
**Pull request by alona-sydorova**
fixes https://github.com/mlr-org/mlr/issues/1463

### CODE REVIEW

**Comment by jakob-r** [comment]
This will not work for wrapped learners, should we S3 that?

**Comment by larskotthoff** [comment]
Yes. (And please don't regenerate/commit Rd files.)

**Comment by larskotthoff** [comment]
ping @alona-sydorova

**Comment by pat-s** [comment]
> This will not work for wrapped learners, should we S3 that?

Is this really important here? The other operators also do not work in an S3 way.
It's a really small change and just completes the `getLearner*()` family.

I cannot clean up here since its a fork. Should we just add this change in a single commit? @jakob-r 	@larskotthoff

**Comment by larskotthoff** [comment]
Sounds good to me.

**Comment by jakob-r** [comment]
If you want to, you can merge.

**Pull request merged**
