### PR TITLE
the lower and the upper for "mincriterion" or "logmincriterion" are  w.r.t. " testtype"

### PR DESCRIPTION
**Pull request by QWERTZ11**

### CODE REVIEW

**Comment by HeidiSeibold** [comment]
deploy/netlify says:

```
3:57:54 PM: Failing build: Failed to build site
3:57:54 PM: failed during stage 'building site': Deploy directory 'docs' does not exist
3:57:54 PM: Finished processing build request in 19.978584328s
```

Not sure what the problem is here. Please help! :person_frowning:

**Comment by pat-s** [comment]
> failed during stage 'building site': Deploy directory 'docs' does not exist

This means that `docs/` does not exist in branch `partykit-transition`. Merging the master branch should solve it :)

**Comment by pat-s** [comment]
@HeidiSeibold 	Did that help?

**Comment by QWERTZ11** [comment]
Hallo, @pat-s. Danke für die Hinweis.  
Meist du branch ”partykit-transition“ , nicht direkt  branch "QWERTZ11:patch-1"?  
("QWERTZ11:patch-1" ist ein Subbranch von  ”partykit-transition“.)

Wenn ich “docs” zur "QWERTZ11:patch-1" hinzufügen und push möchte, bekomme ich 

```
$ git push origin patch-1
Username for 'https://github.com': QWERTZ11
remote: Permission to mlr-org/mlr.git denied to QWERTZ11.
fatal: unable to access 'https://github.com/mlr-org/mlr.git/': The requested URL returned error: 403
```

**Comment by pat-s** [comment]
No, what I've written relates to the question form Heidi and applies to it.

Your error comes from the fact that you are trying to push to the mlr-org remote without having rights to do so whereas you actually want to push to your fork.
You may need to check your local settings.

Looks like you're overcomplicating this change here a bit - @HeidiSeibold 	could just push the small changes from her account with one commit without the need to open a custom PR here :)

(Please stick to English in this repo, thanks).

**Comment by QWERTZ11** [comment]
@pat-s Thanks for answer.

**Comment by HeidiSeibold** [comment]
@pat-s I am not sure I understand what you are asking me to do :upside_down_face:

**Comment by pat-s** [comment]
@HeidiSeibold 	I was suggesting to simplify things by YOU commiting the changes of this PR directly into the branch because 

- you have rights in mlr
- This PR makes changes to another PR by a fork of a user with no rights to mlr (-> quite complicated :) )

**Comment by pat-s** [comment]
I am closing this now here since the state of this PR is very unclear. Let me know if I can help you updating the `partykit-transition` branch or whatever you want to do here :)

**Pull request closed without merging**
