### PR TITLE
fix pretty.names = FALSE in plotThreshVsPerf

### PR DESCRIPTION
**Pull request by zmjones**
fix for #1167

### CODE REVIEW

**Comment by larskotthoff** [comment]
Could you make the test an additional one please so that pretty names are also tested?

**Comment by zmjones** [comment]
so i modified a test so that this bug would have caused a failure. you would prefer that i duplicate the test with only pretty.names changed so the failure would be unambiguous?

**Comment by larskotthoff** [comment]
Yes. In particular the modified test doesn't test what happens for the other value of pretty names :)

**Comment by zmjones** [comment]
No but since it is the default it is checked in all of the other calls to plotThreshVsPerf.

**Comment by larskotthoff** [comment]
Ok, fair enough.

**Pull request merged**
