### PR TITLE
generateFilterValuesData: added 'more.args', fixes #941

### LINKED ISSUE #941: generateFilterValuesData: Additional args for two or more filters
This is not that important, rarely happens and not hard to circumvent, but we should think of a better solution how to pass additional args to filters when two or more filters are used simultaneously.

```
generateFilterValuesData(iris.task, method = c("mrmr","univariate.model.score"), nselect = 3, perf.learner = "classif.lda")
Error in .local(.Object, ...) : 
  unused argument (perf.learner = "classif.lda")

traceback()
10: .local(.Object, ...)
9: initialize(value, ...)
8: initialize(value, ...)
7: new("mRMRe.Filter", levels = rep(1, feature_count), ...)
6: mRMRe::mRMR.classic(data = data, target_indices = target.ind, 
       feature_count = nselect, ...)
5: (function (task, nselect, ...) 
   {
          positive = NA_character_, negative = NA_character_)), 
       nselect = 3, perf.learner = "classif.lda")
4: do.call(x$fun, c(list(task = task, nselect = nselect), list(...)))
3: FUN(X[[i]], ...)
2: lapply(filter, function(x) {
       x = do.call(x$fun, c(list(task = task, nselect = nselect), 
           list(...)))
       missing.score = setdiff(fn, names(x))
       x[missing.score] = NA_real_
       x[match(names(x), fn)]
   })
1: generateFilterValuesData(iris.task, method = c("mrmr", "univariate.model.score"), 
       nselect = 3, perf.learner = "classif.lda")
```

### PR DESCRIPTION
**Pull request by berndbischl**
This deals with issue #941 

I have selected option b) from the thread. its documented and test.

NEWS:
- generateFilterValuesData: added argument 'more.args' 

PS:

I have restructed the test files a bit better. basic filters are in test_base now, exhaustive loopy tests for all filters remained in test_featsel.

please review

### CODE REVIEW

**Comment by larskotthoff** [comment]
Hmm, not a fan of two separate things in one PR, but looks ok to me apart from that.

**Comment by berndbischl** [comment]
> Hmm, not a fan of two separate things in one PR

Come on. I repair this when I see this, and if is 100% related.

**Comment by berndbischl** [comment]
ok, wait for travis then merge pls (me = not allowed)

**Comment by larskotthoff** [comment]
Travis build fails because of documentation mismatches, merging.

**Comment by berndbischl** [comment]
> Travis build fails because of documentation mismatches, merging.

wont this break the travis master build now?

**Comment by larskotthoff** [comment]
It shouldn't; the master build updates the documentation.

**Pull request merged**
