### PR TITLE
partial derivative estimation for partial prediction functions

### PR DESCRIPTION
**Pull request by zmjones**
- for regression, classification, and survival tasks
 - also a fix for #465 (part of the above depends on this)

### CODE REVIEW

**Comment by larskotthoff** [comment]
I think you got the failed commit in the master branch in here and that's why the build is failing. Could you please rebase once that's fixed?

**Comment by zmjones** [comment]
Yep

**Comment by larskotthoff** [comment]
Ping. Master is fixed now.

**Comment by zmjones** [comment]
Thanks! Rebased. Pumped to have this feature.

**Comment by zmjones** [comment]
I thought I had commit rights but apparently not.

**Comment by larskotthoff** [comment]
Yeah, Bernd got annoyed and now only a select number of people can commit. Merging, thanks for your work on this!

**Pull request merged**
