### PR TITLE
Get ROC matrix

### PR DESCRIPTION
**Pull request by ja-thomas**
nicer printer for the ROC matrix.

```
> print(x)
    predicted
true M         R                            
   M 14        15        TPR: 0.48 FNR: 0.52
   R 4         42        FPR: 0.09 TNR: 0.91
     PPV: 0.60 FOR: 0.26 LRP: 5.55 ACC: 0.75
     FDR: 0.40 NPV: 0.74 LRM: 0.57 DOR: 9.80


Abbreviations:
TPR - True positive rate (Sensisivity, Recall)
FPR - False positve rate (Fall-out)
FNR - False negative rate (Miss rate)
TNR - True negative rate (Specifity)
PPV - Positive predictive value (Precision)
FOR - False omission rate
LRP - Positive likelihood ratio (LR+)
ACC - Accuracy
LRM - Nevative likelihood ratio (LR-)
DOR - Diagnostic odds ratio
```

### CODE REVIEW

**Comment by berndbischl** [comment]
1) pls doc
2) the printer should have a flag to display the abbrevs
3) getROCMatrix with "M"
4) does relative = FALSE even make sense? remove?

**Comment by catastrophic-failure** [comment]
Is ROC matrix a good name though?

**Comment by berndbischl** [comment]
> Is ROC matrix a good name though?

well it was what came to our mind first.
it is basically this here
https://en.wikipedia.org/wiki/Receiver_operating_characteristic

better suggestion welcome

**Comment by PhilippPro** [comment]
confusion matrix?

at first glance roc matrix seemed to me a bit confusing (I thought about a matrix with the values of the ROC Curve)

**Comment by ja-thomas** [comment]
there is already getConfusionMatrix, which is also possible for multiclass problems. 

Maybe it makes sense to combine both functions?

**Comment by berndbischl** [comment]
confusion matrix we already have.
calcROCMeasures?

reasons:
- it is no getter
- it returns no matrix
- clearer

we should then maybe also rename getConfMarix --> calcConfusionMatrix

**Comment by berndbischl** [comment]
and deprecate getConfMatrix

**Comment by berndbischl** [comment]
> Maybe it makes sense to combine both functions?

hmmm. maybe. yes. probably

**Comment by ja-thomas** [comment]
should hopefully be good now. The name is `calculateROCMeasures`

**Comment by berndbischl** [comment]
1) pls rename als measures to lower case

2) pls doc the return type in a complete fashion. and conf.matrix not confMatrix.

3) for all defaults add them to the docs

4) use families "roc" and "performance"

**Comment by ja-thomas** [comment]
so the renaming for the measures is kind of annoying,

for example False Omission Rate -> `for`. I can't think of a diffferent three letter abbreviation. Everything else should be fixed.

**Comment by ja-thomas** [comment]
Now with small abbreviation and measure names.

```
> calculateROCMeasures(pred)
    predicted
true M         R                            
   M 0.52      0.48      tpr: 0.52 fnr: 0.48
   R 0.31      0.69      fpr: 0.31 tnr: 0.69
     ppv: 0.48 for: 0.28 lrp: 1.66 acc: 0.63
     fdr: 0.52 npv: 0.72 lrm: 0.7  dor: 2.37


Abbreviations:
tpr - True positive rate (Sensisivity, Recall)
fpr - False positve rate (Fall-out)
fnr - False negative rate (Miss rate)
tnr - True negative rate (Specifity)
ppv - Positive predictive value (Precision)
for - False omission rate
lrp - Positive likelihood ratio (LR+)
fdr - False discovery ratenpv - Negative predictive valueacc - Accuracy
lrm - Negative likelihood ratio (LR-)
dor - Diagnostic odds ratio)
```

**Comment by berndbischl** [comment]
@ja-thomas 
i guess you need to fix this

**Pull request merged**
