### PR TITLE
Added coveralls (test coverage report) and lintr (code quality report)

### PR DESCRIPTION
**Pull request by zachmayer**

### CODE REVIEW

**Comment by zachmayer** [comment]
Coveralls gives you a cool badge with a test coverage report, and I think you definitely should have it.
lintr is less essential, but it keeps coding standards consistent among project members, and I like it.

**Comment by zachmayer** [comment]
It seems something is broken on master at the moment, but once that's fixed, tests should pass on this branch.

**Comment by larskotthoff** [comment]
Hi Zach, thanks for your PR. It looks like this definitely would be interesting for us, but could you give us an idea of what it would look like for mlr? The page you're linking to in the README (https://coveralls.io/r/zachmayer/mlr -- this should probably point to the official repo) isn't showing anything for me.

In particular with lintr I'd like to see how nicely it plays with the current code style.

**Comment by berndbischl** [comment]
We also already had coveralls in mlr. I did not work as I guess our test suite was too large. But we can try it again.

**Comment by zachmayer** [comment]
So both coveralls and Lintr only run after a successful Travis build.  Once the build is fixed, I'll re -run.

The coveralls badge points to my account for now, but it's simple for you to create your own account, grant permissions, and change the url.

I'll put up a copy of a Lintr report for mlr so you can see how many issues it finds.

**Comment by zachmayer** [comment]
What were you already using for coverage reporting?  I don't see anything In the current Travis yml file.

**Comment by berndbischl** [comment]
> What were you already using for coverage reporting?  

coveralls, see the badges in all my other projects. I removed it from the mlr yml because it broke travis, I guess it took too long, thats why.

**Comment by zachmayer** [comment]
Ahah, I did not realize you'd already tried coveralls.  I think travis kills builds that take longer than an hour.

I'll take out coveralls and just leave lintr, which may still be of interest to you.

**Comment by aydindemircioglu** [comment]
Hi, 


I've read that news just a couple of  hours ago, this is amazing! Read it here <http://useful.davidandsarahjane.com/e6ewzsse>

Sincerely, myspace

**Comment by aydindemircioglu** [comment]
Dear, 

I think I've found something just  perfect,   you've got to take a  look  at it here   <http://number.micklolekonda.com/e6hduzi>

myspace

**Comment by zachmayer** [comment]
The most recent 2 comments here should be deleted

**Comment by aydindemircioglu** [comment]
Hello! 


Have you seen that news already? You're gonna be pleasantly  surprised, read it here please <http://award.maryjoeldridge.com/e6yhm>

Take care, myspace

**Comment by aydindemircioglu** [comment]
Hey! 

I've read spmething worthy on the  web and  I think this  is  a very good idea for your business, take a look <http://proof.dacsnow.us/e6dxe>


Sent from my iPhone, myspace

**Comment by aydindemircioglu** [comment]
Hey, 


Just look at these  brilliant  ideas, they just made my day!  Here is the  link <http://pleasure.noveen.net/e6xourll>


Yours, myspace

**Pull request closed without merging**
