### PR TITLE
Move from mkdocs to pkgdown and integrate mlr-tutorial into mlr

### PR DESCRIPTION
**Pull request by pat-s**
Hi guys,

sorry for the mass of modified files but I see no option how I could do this in another way?

Looking forward hearing your opinion on this PR :smiley: 

For Travis, please refer to the [recent builds of my fork](https://travis-ci.org/pat-s/mlr) and not the PR 
one.

# Before merging

- [ ]  Update the .travis.yml. Currently its tailored to my fork.

# Features

* Live preview of [mlr-tutorial (devel)](https://pat-s.github.io/mlr/) (will of course be changed from `pat-s` url to `mlr-org` when being merged)
* Integration of [mlr-tutorial (release)](https://pat-s.github.io/mlr/articles/tutorial/release/index.html) with all internal links working. I needed to manually edit most of the `release` files to get the internal links working while maintaining the same url structure as `devel`. However, this should have been a one-time thing and not needed to be done again after the next CRAN release.
* Linking to `pkgdown` implementations of other packages
* Fully R based
* Integrated NEWS menu in menu bar
* Cheatsheet linked on main page
* Links to slack, stackoverflow, github and blog in menu bar
* Better and cleaner look
* Easier build process
* Orcid ID linked next to author name in main page
* Search bar (right now a bit buggy as search need to be entered twice)
* Easier travis build process
* Build of new PDF version based on `bookdown::pdf_document2()` [release](https://github.com/pat-s/mlr/blob/gh-pages/articles/tutorial/release/mlr-tutorial.pdf), [devel](https://github.com/pat-s/mlr/tree/master/vignettes/tutorial/devel/pdf/mlr-tutorial.pdf)
* Uses the new logo that was proposed some months ago in the Slack group

# Miscellaneous
* Cleaned up `mlr-tutorial` sources (new line for every new sentence, consistent new line spacing, consistent space around code-chunks)
* Added [mlr-contribution guide](https://pat-s.github.io/mlr/#mlr-tutorial) to `README.md`
* Older `mlr-tutorial` versions starting from =< 2.10 are placed in `vignettes/tutorial/old/` and are still accessible but only file-by-file, i.e. without working internal linking, e.g. [Bagging section from 2.10](https://pat-s.github.io/mlr/articles/tutorial/old/2.10/html/bagging/index.html)

# Implementation 
* Site is served via `gh-pages` branch and deployed via `ropenscilabs/tic`. 
* As `pkgdown` takes a lot of information from the DESCRIPTION and other informative files of the main repo, there is no way to put all this into a separate repo as it was before with `mlr-tutorial`
* Building is done with a forked version of `pkgdown` in which I implemented some open PR's from the main repo (Orcid ID, ability to exclude certain files, search bar). I will keep the fork up-to-date with master until everything is implemented.
* Currently it is necessary to specify a output format dependent insertion of figures as the scaling for html and pdf output does not align nicely with the same settings. However, we only have 3 external images right now in all ~300 pages of `mlr-tutorial` so this should not be a problem. See [this section](https://github.com/pat-s/mlr/blob/master/vignettes/tutorial/devel/handling_of_spatial_data.Rmd) for an example.
* [The Travis builds](https://travis-ci.org/pat-s/mlr/builds) are currently running on a matrix to separate html and pdf version but can of course be combined. Due to the limited build time in my fork implementation this was not possible. 
* For merge, the repo owner (I assume @berndbischl?) has to set the Github pages branch under `Settings >> Github pages` so that the site deployment can work
* For the handling of issues and PR, I propose to add labels with `tutorial` or `mlr-tutorial`. There not that many issues and PRs in `mlr-tutorial` compared to `mlr` so I think this is handable.

# To Do

- [x] Figures are not displayed anymore after applying "display code in boxes" -> Using rawgithubuser paths as that works for all instances (docs, pdf, vignettes dirs)

- [x] PDF headers are misaligned due to the need of the "title" field in the .Rmd files. I need to find a way to decrease all headers of the child documents in the PDF wrapper `_pdf_wrapper.Rmd` by one level -> fixed by inserting topic headers (h2) manually in _pdf_wrapper.Rmd

### CODE REVIEW

**Comment by pat-s** [comment]
ping @jakob-r, @larskotthoff

**Comment by jakob-r** [comment]
I like it but I still have some issues (checked on https://pat-s.github.io/mlr/):

* `<title>` is not set which is bad for SEO
* search still does not work
* the conent nav on the right only displays `<h1>` and `<h2>`(?) and is basically useless atm. So: Just rearrange the headlines in the source?
* Output has a "box" for each line of output (e.g. https://pat-s.github.io/mlr/articles/tutorial/devel/parallelization.html)

**Comment by pat-s** [comment]
> * `<title>` is not set which is bad for SEO and bookmarking...

I have no experience with this. Do you mean something like [this](https://stackoverflow.com/questions/413439/how-to-dynamically-change-a-web-pages-title)?

> * search still does not work

Right, currently it does not work at all. Before it worked at least with the second try.
Well, this is a WIP from a `pkgdown` [PR](https://github.com/r-lib/pkgdown/pull/426). Maybe the PR will be changed soon and then uses the `mkdocs` search capability.

> * the conent nav on the right only displays `<h1>` and `<h2>`(?) and is basically useless atm. So: Just rearrange the headlines in the source?

Right, that should not be too complicated to be changed. I'm on it.

> * Output has a "box" for each line of output (e.g. https://pat-s.github.io/mlr/articles/tutorial/devel/parallelization.html)
> 

I don't know if we can do something here. That's also the output if you render the doc as a standard `html_document()`. I think this maybe more related to the way the output is written than to how it is rendered?

**Comment by pat-s** [comment]
> the conent nav on the right only displays h1 and h2(?) and is basically useless atm. So: Just rearrange the headlines in the source?

solved.

I am now trying out if some other fonts (Droid Serif, Fira code) further improve the appearance.

**Comment by jakob-r** [comment]
> > * Output has a "box" for each line of output (e.g. https://pat-s.github.io/mlr/articles/tutorial/devel/parallelization.html)
> > 
> 
> I don't know if we can do something here. That's also the output if you render the doc as a standard `html_document()`. I think this maybe more related to the way the output is written than to how it is rendered?

One can do it manually in each Rmd file but there might be a smarter way. I mean we can still have a build file that calls pkgdown but does some preprocessing first.

**Comment by jakob-r** [comment]
> > * `<title>` is not set which is bad for SEO and bookmarking...
> 
> I have no experience with this. Do you mean something like [this](https://stackoverflow.com/questions/413439/how-to-dynamically-change-a-web-pages-title)?

No. That should happen during the build automatically by pkgdown. At least it seems to work everywhere else. Just look at the Window or tab Title. I suspect the reason it is missing is, that you commented out the title in the yaml for many pages.

**Comment by pat-s** [comment]
> No. That should happen during the build automatically by pkgdown. At least it seems to work everywhere else. Just look at the Window or tab Title. I suspect the reason it is missing is, that you commented out the title in the yaml for many pages.

Ah I see now. Yes, I did so because only with h2 headers we get a proper formatted PDF output. `title` field in the metadata is always h1 and this is then problematic if we want to group all vignettes as level 2 entries in the Table of Contents of the PDF. 

But yeah, if the title field sets `<title>`, we should use it and account for the correct formatting otherwise.

**Comment by pat-s** [comment]
> <title> is not set which is bad for SEO and bookmarking...

Should be fixed now be re-enabling the title field. This causes a bad formatting of the PDF vignette due to falsely formatted header levels but I already asked a [question](https://stackoverflow.com/questions/48270931/increase-header-levels-of-child-documents) on this. 

> Output has a "box" for each line of output (e.g. https://pat-s.github.io/mlr/articles/tutorial/devel/parallelization.html)

Should also be fixed by implementing your proposed workaround in the knitr setup chunk of every file.

**Comment by pat-s** [comment]
> <title> is not set which is bad for SEO and bookmarking...
> search still does not work
> the conent nav on the right only displays h1 and h2(?) and is basically useless atm. So: Just rearrange the headlines in the source?
> Output has a "box" for each line of output (e.g. https://pat-s.github.io/mlr/articles/tutorial/devel/parallelization.html)

Everything fixed besides the search issue which is not something I can solve.
So should I start changing the .travis.yml and getting ready for merge @jakob-r?

**Comment by jakob-r** [comment]
Hmm... I would like to wait until the search function is fixed upstream. We also need the feedback of others.

**Comment by pat-s** [comment]
> Hmm... I would like to wait until the search function is fixed upstream. We also need the feedback of others.

Alright, who exactly? I fear if we do not tag explicitly, no one might feel addressed...
I'll see what I can do regarding the search function issue.

**Comment by SteveBronder** [comment]
If you are looking for an extra reviewer I should have time this weekend

**Comment by pat-s** [comment]
Sure @SteveBronder, every review is welcome and precious!

**Comment by larskotthoff** [comment]
Looks good to me.

@schiffner opinions?

**Comment by SteveBronder** [comment]
Notes:
Quick Notes:
- Search not working
- When clicking mlr-org packages can we have it open up a new tab?
- Can the contents of reference have subsections?
  - Mostly for the getters
- Is it possible to get rid of the `# NOT RUN {`in the examples?


Other notes on docs:
- We should expand the getting started section to be a bit longer, maybe explain what's going on more in the quickstart. Saying, "Here is what a task is, here the idea of a learner, etc. Have a graph that describes the pipeline of running an experiment.

**Comment by mb706** [comment]
Are the internal links supposed to be explicit (`vignette("...")`)? Fwiw, I found [this](https://mlr-org.github.io/mlr-tutorial/devel/html/performance/index.html) more readable than [this](https://pat-s.github.io/mlr/articles/tutorial/devel/performance.html) ([screenshots](https://imgur.com/a/Z9J4a)).

**Comment by pat-s** [comment]
> Are the internal links supposed to be explicit (vignette("..."))? Fwiw, I found this more readable than this (screenshots).

I share your opinion here, apparently we can also use `[parallelization](parallelization.html)` instead of `vignette("parallelization")` to have a simple link.

It works locally, I'll do a test commit to see if it works when deployed.

@SteveBronder I'll address your comment later.

**Comment by pat-s** [comment]
> Quick Notes:
> 
> Search not working

As said before, this depends on a [PR](https://github.com/r-lib/pkgdown/pull/426) from the pkgdown package using Java Script. It is currently broken and since I have no skills in JS we are dependent on @jayhesselberth to fix it. 

> When clicking mlr-org packages can we have it open up a new tab?

Idk if we can control this but I'll do some searching.

> Can the contents of reference have subsections?
> Mostly for the getters

I think we can only have one level of grouping (which is based on regex).
During deployment I noticed several warnings that some functions are missing, will take a closer look at it.

> Is it possible to get rid of the # NOT RUN {in the examples?

Idk, probably pkgdown just processes the help file without any modification options. 

> Other notes on docs:
> 
> We should expand the getting started section to be a bit longer, maybe explain what's going on more in the quickstart. Saying, "Here is what a task is, here the idea of a learner, etc. Have a graph that describes the pipeline of running an experiment.

Yes, most people will start reading this section so it maybe should be optimized. However, that is out of the scope of this PR as it only focuses on the pkgdown transition, not modifying any content.

**Comment by pat-s** [comment]
> I share your opinion here, apparently we can also use [parallelization](parallelization.html) instead of vignette("parallelization") to have a simple link.

Works, I'll change all the `vignette()` calls with simple hyperlinks.

**Comment by pat-s** [comment]
@mb706 changed it now, have a look: https://pat-s.github.io/mlr/articles/tutorial/devel/performance.html

**Comment by pat-s** [comment]
> When clicking mlr-org packages can we have it open up a new tab?

@SteveBronder: Did some research on this and it as easy like [this](https://stackoverflow.com/a/15551842/4185785).
While this works when inserted manually, getting markdown links converted with this option is somehow complicated.
As we rely on `pandoc`, [this answer ](https://stackoverflow.com/a/29767900/4185785) seemed promising.

Unfortunately, it does not work. I posted a [new question](https://stackoverflow.com/questions/48486920/pandoc-open-link-in-new-tab) whether its possible with `pandoc` as I could not find a topic in the github issues. 

An alternative would be to convert all markdown links to html links but that would make the writing of articles more inconvenient:

`<a target="_blank" href="http://your_url_here.html">Link</a>`

**Comment by pat-s** [comment]
@SteveBronder 
Got it working, the syntax from the last comment is valid and works with `pandoc` when leaving out the colon, e.g.

`[wrapper](wrapper.html){target="_blank"}`

**Comment by mb706** [comment]
If it turns out that many crutches and workarounds need to be added due to the inflexibility (or immaturity, or unfitness to this purpose) of pkgdown, wouldn't it be more prudent to just use the mlr-tutorial we already have and add features there? Someone writing a new tutorial page with pkgdown would need to keep in mind quite a lot about how to link to stuff, apparently. On the other hand, considering the benefits of pkgdown: things like "link to slack" should be trivial to add in mlr-tutorial. One nice feature of pkgdown seems to be that help files for individual functions are included (although rdocumentation.org appears to work well), but it should be relatively easy to include that in mlr-tutorial, too (using things like `git clone --depth 1`). If you don't like the mlr-tutorial design, there are probably some other themes available (I don't know, but assume this is so?), and the CSS should be editable, as well. In return, the mlr-tutorial features a build script that makes it possible to change things like `target="_blank"` from a central location without the need to search-and-replace (and keeping the convention in mind when writing new pages ever after).

I don't know how happy people would be to see the old mlr-tutorial go, maybe it causes considerable maintenance overhead (that I wouldn't be aware of because I'm not much involved with it). If the tutorial needed to be written from scratch, pkgdown would probably be the easier route today, but to me (as a mostly outsider) it seems like most problems that pkgdown solves were already solved in mlr-tutorial.

Note that I'm just a bystander and have no say whatsoever in where the tutorial / vignette stuff is headed, but this was my observation.

**Comment by pat-s** [comment]
Thanks @mb706 for writing down your concerns. I assume you are not the only one so thanks for taking the time.

I am well aware that this PR does not add huge improvements to the tutorial approach.
It is mainly a design change for most people. However, while you state the someone writing a new page has to consider many (new) things: I think that the current approach is way more "unkown" to a regular R user than the `pkgdown` style.

For example, R users are used to write things like `function()` to link to a function (e.g. using `roxygen2` when documenting functions). Using `[%function]` is something that R users are not familiar with.
Regarding the writing conventions, everything else basically stays the same. The idea of @SteveBronder to open all links in tabs by using `[link](url){target="_blank"}` can actually be seen as a feature request that could of course also be implemented in `mkdocs`.
However, I think, in the long run `pkgdown` will be easier to maintain and use because more people have at least some basic knowledge in it. However, only few R users are familiar with `mkdocs`. This could also help @jakob-r in the future maintaining all this because he can get more help than with all the `mkdocs` stuff.

> Someone writing a new tutorial page with pkgdown would need to keep in mind quite a lot about how to link to stuff, apparently.

If I forgot something, please just mention it again. I did not want to leave something undiscussed.

> In return, the mlr-tutorial features a build script that makes it possible to change things like target="_blank" from a central location without the need to search-and-replace (and keeping the convention in mind when writing new pages ever after).

This is of course a advantage in simplicity for post-processing on the one hand, on the other the [build script](https://github.com/mlr-org/mlr-tutorial/blob/gh-pages/build) is somewhat complicated and not needed in the `pkgdown` approach. Users can build it locally by just using `pkgdown::build_site()` which seems easier than the current build process. 
We could also agree to use such a post-processing script for the `pkgdown` approach. 
However, a simple `sed -i --/s/g *.Rmd` does most of the magic here when working with replacements in multiple files.

> I don't know how happy people would be to see the old mlr-tutorial go, maybe it causes considerable maintenance overhead (that I wouldn't be aware of because I'm not much involved with it).

TBH I don't know, I asked @jakob-r before because to my knowledge he is mainly responsible for the tutorial section? There is also @schiffner but since I contribute to `mlr` (Jun 2017) I rarely saw her being active.

> Note that I'm just a bystander and have no say whatsoever in where the tutorial / vignette stuff is headed, but this was my observation.

That's the same for me. I just asked whether the guys would be up for it and then put work in. In this manner also I would be somehow disappointed to have put 50+ h into this and then being told that we do not use it although I got everything working that was requested (besides a functional search bar so far).

Imho I think the having everything in one place (the README, the function references, the vignettes, the cheatsheet and link to other mlr-packages and the Slack group, the Blog) is a major advantage to the current `mkdocs` approach. This fact together with the more familiar R approach of building the site than using python makes the small difference to move to `pkgdown`. Themeing is opinionated but here I like also the overall look of the `pkgdown` approach more although I haven't checked on other `mkdocs` themes.

**Comment by schiffner** [comment]
Hi,

thank you very much for this PR and all the work you put into this. From my side it is very much appreciated!!! Particularly having everything (infos from mlr github page, tutorial, documentation etc.) in one place is something we have discussed several times.

I only had time for a superficial look.

* Looks great overall. I personally like our custom mkdocs theme a little better than the current look of the pkgdown tutorial w.r.t. the colors, but that's just an opinion.
One thing I would change in the pkgdown tutorial is the font for the headings: At the moment it's easy to overlook headings because the font looks "thinner" than the font used for the running text.
* The table on the Visualization page (https://pat-s.github.io/mlr/articles/tutorial/devel/visualization.html#available-generation-and-plotting-functions) seems to be broken.

Sorry for my continued absence. I'm reading most of the github notification emails, but at the moment rarely have time to contribute.

Thanks again,
Julia

**Comment by jakob-r** [comment]
I also think that having everything in one place and having a build process that is not unique to us is a big advantage. Especially as I think pkgdown will improve in the feature.
I just hope that the search will be fixed upstream sometimes soon. 

Also (i can make those changes myself but I want a short feedback) 

* I would put Reference as "Function Reference" in Appendix and News as well. 

Another small bug

* The table for the classification learners seems to be unnecessarily wide. (Noe soft wrap in Note column)

**Comment by pat-s** [comment]
Hi @schiffner,

thanks for your feedback!

> Looks great overall. I personally like our custom mkdocs theme a little better than the current look of the pkgdown tutorial w.r.t. the colors, but that's just an opinion.

Theming is always opinionated and maybe it would be best to first agree on a basic [theme](https://gallery.shinyapps.io/117-shinythemes/) and then adjust it.
I personally like the `Fira Code` font because its nice to read and has ligature support.
I will post a poll in the slack group that should decide which theme to go with.

> One thing I would change in the pkgdown tutorial is the font for the headings: At the moment it's easy to overlook headings because the font looks "thinner" than the font used for the running text.

Thanks, I overlooked this. I set the `font-weight` to 700 for headers and it looks much better now. 

> I would put Reference as "Function Reference" in Appendix and News as well.

@jakob-r Sure, go ahead. Makes the navbar a little lighter :+1:

**Comment by pat-s** [comment]
Btw another point that speaks in favor of the `pkgdown` implementation: We directly see if a commit to `mlr` also affects `mlr-tutorial` (because we have travis builds for both triggered by one commit). Currently this is again the case for the recent commit related to partial dependence that broke the tutorial..

**Comment by pat-s** [comment]
> The table for the classification learners seems to be unnecessarily wide. (Noe soft wrap in Note column)

when building locally with a font size of 12 for tables, the classification table misalignment problem vanished :thinking:. Soft wrapping applies now correctly.

**Comment by pat-s** [comment]
Build is passing again.

@schiffner 
Headers are not displayed with `font-weight: 600`. Themeing poll only received 4 votes in the Slack group so maybe we should create one as an issue on Github? (open for better ideas).

I removed the search completely as it is not working right now so that no one is confused.

@jakob-r I tried to rearrange the widths of the text area (75%) and the sidebar (25%) to 85/15 which mostly solves the arrangement problem of the integrated learner table. I hopefully fixed it again in the last commit tonight so don't be confused if it is still 75/25 tomorrow when you take a look.

* I integrated the new logo and set is as the replacement for the index link that previously was just the text "mlr". 
* Updates the `.travis.yml`: We now build with `pandoc` v2.1.1 as the default on travis (1.15 from 2014?) triggered some problems.



I would suggest to include all further changes to the tutorial into this PR so that we do not have to maintain two tutorials at the same time? Its quite exhausting duplicating things.. ;)

I think we can get this approach merged before v2.12 is released if we push it a bit, which would also make it a nice NEWS item.

**Comment by pat-s** [comment]
@jakob-r  @larskotthoff 

Is there anything still missing / open to discuss before it would be ready to merge?

Small adjustments (themeing, logo changes) could of course also be applied after merge. 
Imo its stable and is at the most recent state of `mlr-tutorial`, so we could implement all further additions here after merge. 
This would prevent us from having to maintain two repos at the same time. 
I will of course also maintain it and push it further / clean up issues, so my work is not done after the merge ;)

**Comment by jakob-r** [comment]
Found one weirdo in the preview: https://pat-s.github.io/mlr/articles/tutorial/devel/create_measure.html#constructing-a-performance-measure
`error mmce{target=“_blank“}`

**Comment by pat-s** [comment]
Thanks. These commands make sure that hyperlinks are opened in a new tab. 

It worked already and I assume it got broken after using `pandoc` v2.1.1 for building recently. Syntax might have changed. Will take a look. 

(I used v2.1.1 because it fixed some problem in the PDF build process).

Whats your opinion on merging before v2.12? @larskotthoff suggested to wait

**Comment by jakob-r** [comment]
> Whats your opinion on merging before v2.12?

I am okay with whatever happens first

**Comment by pat-s** [comment]
@larskotthoff The merging should not affect `mlr` per se at all. All additions just tackle the tutorial.
Also the adjustment of the .travis.yml just creates a build matrix without modifying the build of `mlr`.

I would also vote for doing the integration now so that we can have an easier life implementing future changes than having to integrate them via this PR.
Furthermore, we could then also discuss further actions at the meeting in March with a working integration rather than discussing about a PR.

I'll tackle the recent issue metnioned by Jakob again and unless you are completely against it Lars, I would start the integration.

**Comment by larskotthoff** [comment]
Ok, fine.

**Comment by pat-s** [comment]
> Found one weirdo in the preview: https://pat-s.github.io/mlr/articles/tutorial/devel/create_measure.html#constructing-a-performance-measure
> error mmce{target=“_blank“}

Fixed by using `pandoc` v2.1.1

Learner `mxff` from the `mxnet` package screws up the table for classification learners: https://pat-s.github.io/mlr/articles/tutorial/devel/integrated_learners.html

All follow up learners are incorrectly formatted.
Is this due to a missing installation of `mxnet`? Installation on Linux is not trivial: http://mxnet.incubator.apache.org/install/index.html
Without, I cannot build the table locally either so wondering how `mlr-tutorial` currently does it?  Looking fine [there](https://mlr-org.github.io/mlr-tutorial/devel/html/integrated_learners/index.html).

**Comment by pat-s** [comment]
The root of all evil was a missing closing "`" sign in the "note" section of the "classif.mxff" learner that caused all further code to be mistakenly interpreted as code and therefore messed up the rest of the classif.* table :duck:

`mlr-tutorial  does apparently not interpret it directly as markdown code and is therefore unaffected.

**Comment by jayhesselberth** [comment]
@pat-s pkgdown now has integrated search capability. See instructions here:

http://pkgdown.r-lib.org/articles/pkgdown.html#search

**Pull request merged**
