### PR TITLE
wrapper that adds support for one-class problems to learners (#587)

### PR DESCRIPTION
**Pull request by larskotthoff**

### CODE REVIEW

**Comment by berndbischl** [comment]
Hi, first of all thx.

But like I said in the issue, we should discuss this....

1) The name: "OneClass Problems"  and so on is actually a terminus technicus for something else.
So we cannot use this.

2) I am REALLY unsure whether this is should be a wrapper. It is more or less a really "technical" problem. And I guess it should be handled seamlessly by mlr by default. So IMHO it should be somehow an option. 

Can we please define first what we do, textually?

**Comment by berndbischl** [comment]
And the correct place might be in the issue.

**Comment by larskotthoff** [comment]
The issue seems broader -- in particular it's about *sparse* labels.

Any suggestions for a better name? I've modelled this on the "oneclass" property of learners.

Regarding the wrapper approach. The alternative would be to modify train and predict to do this transparently. The problem I see with that approach is that the model returned by train would be different depending on the data. In particular we can't really make the model behave the same in every case.

We've taken the same wrapper approach in other cases, e.g. imputing missing values for learners that don't support missing values. This isn't done transparently either but you have to explicitly wrap the learner.

**Comment by berndbischl** [comment]
> The issue seems broader -- in particular it's about sparse labels.

Not really. It is the same thing. It is purely technical, if a learner sees to few different labels, it breaks. It shouldnt, at least if all labels are the same, IMHO, also without a wrapper. We also have other options for
problems with factor levels.

> Any suggestions for a better name? I've modelled this on the "oneclass" property of learners.

The oneclass property of a learner means whether a learner supports "true" oneclass classification
(which we then did not cover in mlr...., still an open todo)
https://en.wikipedia.org/wiki/One-class_classification

Like I said, I am also unsure where to put this code, so lets discuss this.

**Comment by berndbischl** [comment]
We hangouted and agreed:

1) the wrapper is probably a good idea, also it should only be seldomly needed by users.

2) it is more flexible if we allow the class to be nearly constant. we need an arg for this. the behavior should be similar as in removeNearlyConstantFeatures.

3) A good name might be NearlyConstantClassWrapper.

4) Remove the "oneclass" property stuff

5) Inherit from basewrapper, like in filterwrapper and so on

**Comment by larskotthoff** [comment]
Done all of that, pushed.

We seriously need some documentation for the internals though, figuring this out was extremely frustrating and in the end I just copied the code that does the same thing from the cost-sensitive wrapper. I have no idea why it works now; it certainly breaks if I change even minor details that as far as I can see shouldn't have any effect.

**Comment by berndbischl** [comment]
1) The sentence in NEWS needs to be adapted

2) I can try to extends the docs a bit if I merge

3) Can we try to get closer with the names to removeConstantFeatures? 
There the "nearly" is not in the name, and we have "perc" as an argument.

I know this is nitpicking, but we really have to reduce inconsistencies.

Regarding the API docs: I 100% agree, but we have to plan this.
We can add a issue to the tracker, but it will rot there. 
I mean you opened one just for the names of the test files, it is still there.

Can you also ask already 2-3 questions which came up when you tried to solve this?

**Comment by larskotthoff** [comment]
Regarding the name of the argument: I think `perc` is actually misleading in removeConstantFeatures as it is not a percentage but a fraction.

**Comment by larskotthoff** [comment]
I'm going to call this `frac`.

**Comment by berndbischl** [comment]
its too late here to get worked up about this 
http://cdn.meme.am/instances/60981391.jpg

**Comment by larskotthoff** [comment]
I think we should change this in removeConstantFeatures actually. But that would be an API change.

Ceterum censeo `=` is ad reponi cum `<-`.

**Comment by larskotthoff** [comment]
Travis failure seems to be unrelated, cannot reproduce locally.

**Comment by berndbischl** [comment]
Logs indicate that there seems to be a dim drop going on 

```

4: apply(mod$predicted, MARGIN = 1L, which.max) at test_classif_randomForestSRCSyn.R:21
5: stop("dim(X) must have a positive length")

```

Has the RFSRCSyn package been updated?

**Comment by larskotthoff** [comment]
Yep. Master build fails as well now. I'm just opening another issue for this.

**Comment by larskotthoff** [comment]
This is ready to be merged now I think.

**Comment by catastrophic-failure** [comment]
I see this was resolved way back, but I saw you were in trouble regarding the choice of name for this wrapper function. Elsewhere I saw this kind of functionality being refered to as _novelty detection_. NoveltyDetectionWrapper perhaps?

**Comment by berndbischl** [comment]
> I see this was resolved way back, but I saw you were in trouble regarding the choice of name for this wrapper function. Elsewhere I saw this kind of functionality being refered to as novelty detection. NoveltyDetectionWrapper perhaps?

hmm, this here is not really novelty detection. although mlr should soon support this.
and when we do i find "OneClassClassification" a good title. 
I will try to merge this at one point

**Comment by berndbischl** [comment]
@larskotthoff 
i guess i could merge this. a few comments:

- can you use prop.table to directly compute proportions / relative frequencies?

- instead of the complex S3 model can you simply create a list containing the most frequent class?

**Comment by larskotthoff** [comment]
- prop.table: Done.
- list instead of S3: This wouldn't work as nicely with the chained model though, would it? I'm checking the class of the model and it feels like changing that check to look for a list would be more brittle.

**Comment by berndbischl** [comment]
@larskotthoff 
ok lets merge this. please specify that the default of "frac" is 0, in the Param.
and add a sentence in the docs how probs are predicted here, pls

**Comment by larskotthoff** [comment]
Done.

**Pull request merged**
