### PR TITLE
Optional lintr

### LINKED ISSUE #1737: Cannot load mlr since lintr commit
This is the error I get:
```r
> library(devtools)
> load_all()
Loading mlr
Loading required package: ParamHelpers

Attaching package: ‘lintr’

The following object is masked from ‘package:devtools’:

    lint

Error in get(name, envir = asNamespace(pkg), inherits = FALSE) :
  object 'T_and_F_symbol_linter' not found
```

### PR DESCRIPTION
**Pull request by mb706**
See if this resolves #1737

### CODE REVIEW

**Comment by mb706** [comment]
For some reason, when I run `R --vanilla` and do
```R
library("BBmisc")
devtools::test(pkg = "mlr", filter = "lint")
devtools::test(pkg = "mlr", filter = "lint")
```
the first `devtools::test` fails because some functions from the "rex" library cannot be found. The second test succeeds (i.e. actually starts linting and therefore runs forever). Anyone have any idea why that is, and how to fix this?

This was already a problem before this PR, so the changes don't "break" this, but I'm still curious.

**Comment by berndbischl** [comment]
are you still working on this? it is hard for me to check the details while on holiday. @larskotthoff @mllg 
i also got another mail from CRAN about the kohonen bdk problem, and need to update on CRAN soon

**Comment by mb706** [comment]
Did Travis just randomly fail?
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

I'm done here as soon as Travis passes.

**Comment by mb706** [comment]
I guess it would be time to break up `run-base.R` into smaller components if it takes more than 10 minutes depending on Travis load? This [apparently makes Travis fail the build](https://travis-ci.org/mlr-org/mlr/builds/216287337).

**Comment by berndbischl** [comment]
> I guess it would be time to break up run-base.R into smaller components if it takes more than 10 minutes

since when has THAT happened? that CANNOT happen!
base also runs on cran. it must take much less than 10 min. maybe 5 in total. 

are you sure something else is not wrong here?

**Comment by berndbischl** [comment]
i could be that travis fails. if you think this should be merged, please ping again.

but also look here please #1745

**Comment by mb706** [comment]
I don't know why it failed, this was just my assumption. The fail seemed to happen randomly, my new commit (which was an empty commit!) passes on Travis.

On the passed build, it says `Running ‘run-base.R’ [370s/251s]`, seems to be far from 10m.

This can be merged. Whatever made Travis fail, it can hardly be the changes introduced here (since they don't touch `run-base.R`).

**Comment by berndbischl** [comment]
> I don't know why it failed, this was just my assumption. 

i am also guessing here

> The fail seemed to happen randomly, my new commit (which was an empty commit!) passes on Travis.

you do know that travis has a "restart build" button. if you need more right for this, please tell me.
 
> On the passed build, it says Running ‘run-base.R’ [370s/251s], seems to be far from 10m.

i tested run_base locally when you wrote here, today. when i created issue #1745.
locally it also needs 4-5 min, so thats ok.

> 
> This can be merged. Whatever made Travis fail, it can hardly be the changes introduced here (since they don't touch run-base.R).

ok, will merge

**Pull request merged**
