### PR TITLE
Add weights for regr.ranger

### PR DESCRIPTION
**Pull request by kysolvik**
- Allows ranger regression to accept weights for case.weights.

- Copied from RLearner_classif_ranger.R, #1409.

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks, looks like it should be fine apart from the lintr error.

**Comment by larskotthoff** [comment]
Thanks. Could you please add a unit test that checks the learner with weights?

**Comment by kysolvik** [comment]
From the discussion in #1409, it sounded like adding a specific unit test for ranger weights would be redundant because "testThatLearnerRespectsWeights" already checks this.

But I would be happy to work on adding a unit test if it's needed

**Comment by larskotthoff** [comment]
Ok thanks, merging.

**Pull request merged**
