### PR TITLE
ENH: hyperpar fuzzy matching suggestion (#1050)

### PR DESCRIPTION
**Pull request by MasonGallo**
If mlr can't find the hyperparameter, suggest the 3 closest matches to the user. Given that most learners probably don't have more than 10 hyperparameters that are frequently tuned, I figured 3 was a safe number here.

- [x] Fix tests
- [x] Convert suggestion to a message() instead?

### CODE REVIEW

**Comment by MasonGallo** [comment]
Here's an example:

```
lrn = makeLearner("classif.ksvm", Cc = 2L)
 Error in setHyperPars2.Learner(learner, insert(par.vals, args)) : 
  classif.ksvm: parameter Cc has no available description object!
Did you mean one of these: C nu tol
You can switch off this check by using configureMlr! 
```

**Comment by berndbischl** [comment]
@MasonGallo 
1) you cannot so easily call configureMlr in the tests. that will change the gobal state. you would need to save the old config options and reset them at the end
2) for your test, why dont you simply use the arg "config" of makeLearner? that seems much easier...?

**Comment by MasonGallo** [comment]
@berndbischl Should be fixed now. Thanks!

**Comment by berndbischl** [comment]
> classif.ksvm: couldn't find Cc!

i would probably make the err msg a bit more specfic, so like 
"could find hyperparam 'CC'" 
(and the name in quotes)

also @larskotthoff @jakob-r @ja-thomas 
what do you think? done?

any downside to always select the 3 best nearest neighbors?

**Comment by larskotthoff** [comment]
Sounds like a great idea and I think we should have this.

**Comment by berndbischl** [comment]
> Sounds like a great idea and I think we should have this.

any comment on my question whether always the 3 best options should be display? ok?

**Comment by larskotthoff** [comment]
Sounds good to me. 

Lars

**Comment by jakobbossek** [comment]
Three seems to be a good choice. Why not make add an mlr option with default set to 3?

**Comment by berndbischl** [comment]
> Three seems to be a good choice. Why not make add an mlr option with default set to 3?

beacause we dont want feature creep and option overload :)
thx, if you like this, too, like me, we can merge this soon

**Comment by jakobbossek** [comment]
> beacause we dont want feature creep and option overload :)
Ok :-)

However, we could outsource the helper function to BBmisc/HELL. I would like to make use of it in other packages as well.

**Comment by berndbischl** [comment]
> However, we could outsource the helper function to BBmisc/HELL. I would like to make use of it in other packages as well. Sure, I can write this quite fast by myself, but we have even shorter functions in BBmisc ;-)

ok i see your point. but maybe more for PH? or do you really want this independent  of a paramset? 
also pls propose a signature then.

**Comment by jakobbossek** [comment]
This would be helpful in non-PH context as well. E.g., fuzzy checking of passed EA algorithm parameters in ecr. A S3 method would be nice. Maybe 

```splus
proposeParams.character = function(x, input.pars) {...}
proposeParams.Param = function(x, input.pars) {...}
proposeParams.ParamSet = function(x, input.pars) {...}
```

**Comment by MasonGallo** [comment]
I see your point @jakobbossek but I am slightly weary of "over-generalizing" this. IMO this works in this particular instance because the set hyperparameters for a given learner tend to have a very small number of elements.

**Comment by MasonGallo** [comment]
> i would probably make the err msg a bit more specfic, so like 
"could find hyperparam 'CC'" 
(and the name in quotes)

@berndbischl I agree I'll change to that shortly

**Comment by berndbischl** [comment]
> This would be helpful in non-PH context as well. E.g., fuzzy checking of passed EA algorithm parameters in ecr. A S3 method would be nice. Maybe

@jakobbossek 
thought about this:
a) i will simply merge this in mlr now, when mason is done here. 
b) i dont want s3 dependencies over multiple packages again. that sucked donkeys balls last time... i can see the point of having a helper in PH. do a PR if you want that. or best open an issue up now, and do  the PR later.

**Pull request merged**
