### PR TITLE
add multilabel measures (subset01, f1mult, jaccard)

### PR DESCRIPTION
**Pull request by QuayAu**
measures taken from http://www.sciencedirect.com/science/article/pii/S0031320313004019

subset01: prediction is right only if all labels are predicted right
f1mult: multilabel version of f1 score https://en.wikipedia.org/wiki/F1_score
jaccard index: https://en.wikipedia.org/wiki/Jaccard_index

### CODE REVIEW

**Comment by berndbischl** [comment]
This can be reviewed now, but should be merged later when mlr 2.8 is on CRAN.

**Comment by larskotthoff** [comment]
Could you please include some unit tests for the new measures? And mention in NEWS.

**Comment by QuayAu** [comment]
I just realized I made a mistake with the F1 and Jaccard measures. I misinterpreted the formulas, I will update this later.

**Comment by QuayAu** [comment]
I corrected the formulas for F1 and Jaccard measures.
0/0 is defined as 1 in this context (see page 2 in http://jmlr.org/proceedings/papers/v28/dembczynski13.pdf)

**Pull request closed without merging**
