### PR TITLE
CI: Fix appveyor, test PDF manual

### PR DESCRIPTION
**Pull request by pat-s**
* Bernd is the maintainer ;) (this happened accidentally while I tried to test sth on win-builder)
* use latex to check PDF manual (at least on appveyor, I don't know why this step is not performed on Travis)
* test on 64 bit on Appveyor
* use `remotes` instead of `devtools`
* use temporary workaround to install mlr on windows with C99 standard

### CODE REVIEW

**Comment by larskotthoff** [comment]
Why is the travis build not running?

**Comment by pat-s** [comment]
Both are running, seems to be a GH display issue? https://travis-ci.org/mlr-org/mlr/builds/433011446

**Comment by larskotthoff** [comment]
Looks like the builds are failing now.

**Comment by pat-s** [comment]
@larskotthoff same problem with GH, builds passing now.

**Comment by larskotthoff** [comment]
Thanks, I still don't see the Travis status, but will merge this now.

**Pull request merged**
