### PR TITLE
fix bug with multiple factor levels in multiclass wrapper (closes #620)

### LINKED ISSUE #620: Wrong class level names in MulticlassWrapper
Hi,

I think that the buildCMatrix function in MulticlassWrapper.R has a bug in the line 111: 

levs = getTaskFactorLevels(.task)[[1]]

It assumes either that the class is the first feature or that only the class is a factor. If a dataset has more than one discrete feature, it crashes. 

I replaced by:

levs = .task$task.desc$class.levels

### PR DESCRIPTION
**Pull request by larskotthoff**

### CODE REVIEW

**Comment by larskotthoff** [comment]
@berndbischl @mllg Could somebody please have a quick look at this? It's a small change and fixes a bug, so I'd like to merge as soon as possible.

**Comment by berndbischl** [comment]
Pls use the proper getter for this: getTaskClassLevels?

**Comment by berndbischl** [comment]
except for that your change looks trivial and good and thx for the reproducing test

**Comment by larskotthoff** [comment]
Ok, I've fixed the getter in the other places where it wasn't used as well.

**Comment by berndbischl** [comment]
thx. we should take more care about this in the future to scale better in terms of extensibility.

Good OO with proper names.

**Comment by berndbischl** [comment]
i guess i will wait for travis

**Comment by larskotthoff** [comment]
I can merge this when Travis is done.

**Comment by berndbischl** [comment]
dont merge your own PRs!!!!!

**Comment by berndbischl** [comment]
jk, thx for taking care of all of this

**Pull request merged**
