### PR TITLE
cleans up assert and adds test for measures arg in plotThreshVsPerf

### LINKED ISSUE #1164: mini fixes for PR #1157
see my last post in the PR thread

### PR DESCRIPTION
**Pull request by zmjones**
should close #1164

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks. Looks like you have another change in there as well?

**Comment by zmjones** [comment]
yea i found an edge case that the new test would have failed. the pretty.names arg would have messed things up if you use the measures arg to the plot function to subset the measures used in the generation function.

**Comment by larskotthoff** [comment]
Ok, thanks. Will merge when travis etc are done.

**Comment by larskotthoff** [comment]
Looks like the examples are failing now.

**Comment by zmjones** [comment]
thanks. should be good now. i had messed up (by renaming) the measures list, thinking that checkMeasures stripped the names.

**Comment by larskotthoff** [comment]
Sorry, looks like the tests are failing now.

**Comment by zmjones** [comment]
yep i am monitoring it too! sorry i am very tired and am not being very reliable apparently.

**Comment by berndbischl** [comment]
so it seems like forcing the addition of a unit test helped to improve the code base ;-)

**Pull request merged**
