### PR TITLE
improve classification randomForestSRCSyn (fixes #602, tests need to …

### LINKED ISSUE #602: randomForestSRCSyn learners are broken
Tests fail:

    1. Error: classif_randomForestSRCSyn -------------------------------------------
     dim(X) must have a positive length
     1: withCallingHandlers(eval(code, new_test_environment), error = capture_calls, message = function(c) invokeRestart("muffleMessage"))
    2: eval(code, new_test_environment)
    3: eval(expr, envir, enclos)
    4: apply(mod$predicted, MARGIN = 1L, which.max) at test_classif_randomForestSRCSyn.R:21
    5: stop("dim(X) must have a positive length")

etc.

randomForestSRC package got updated, not obvious to me what changed.

### PR DESCRIPTION
**Pull request by schiffner**
…be reenabled, see #831)

The same as for regression in #827:
* extend/correct par.set
* train the forest in trainLearner

### CODE REVIEW

**Comment by schiffner** [comment]
randomForestSRC 2.2.0 is on CRAN since yesterday.

I reenabled the multiclass tests for the synthetic random forest (see #831 ).

Moreover, I had to change all randomForestSRC interfaces because of some changes in `rfsrc`:
* option `na.random` was removed
* new learner params: `sampsize`, `samptype`, `tree.error`
* removed learner params: `fast.restore`
* supports now observation weights `case.wt` and thus has property `"weights"`

**Comment by larskotthoff** [comment]
Looks good. Can this be merged now?

**Comment by schiffner** [comment]
I think yes.

**Comment by larskotthoff** [comment]
Great, thanks.

**Comment by MasonGallo** [comment]
FYI tests are failing for regr.randomForestSRC on my local machine after rebasing this:

1. Failure: learners work: regr  (@test_learners_all_regr.R#63) ----------------
any(get.pred.fun(p1) != get.pred.fun(p3)) isn't true.
regr.randomForestSRC

2. Failure: learners work: regr  (@test_learners_all_regr.R#63) ----------------
any(get.pred.fun(p1) != get.pred.fun(p3)) isn't true.
regr.randomForestSRCSyn

**Comment by larskotthoff** [comment]
Did you update the randomForestSRC package?

**Comment by MasonGallo** [comment]
Ah, I think I see what happened. The description file should probably be updated to >= 2.2+ for the randomForestSRC package?

**Comment by schiffner** [comment]
Yep, thanks. That's something I always forget. Just did this.

**Pull request merged**
