### PR TITLE
Fix partial dep range grid for integer features (#1287)

### PR DESCRIPTION
**Pull request by MasonGallo**
See #1287 

- [x] Integer features now correctly create a sequential scale from min to max in partial dependence
- [x] Warning if numerical feature has small num unique obs (I don't love this so lmk)

### CODE REVIEW

**Comment by MasonGallo** [comment]
@zmjones is this alright? I'm not sure of the wider impact from this change

**Comment by larskotthoff** [comment]
Thanks, merging. In the medium term we should think about how to test this better (but AFAIK you're working on a PR for that?).

**Comment by zmjones** [comment]
hmmm i am not sure why i did the whole `rep(low:high)` thing. the actual bug was truncation?

i don't think the warning is appropriate here. there is nothing wrong with doing partial dependence on an integer feature with only a few unique values. Take for example any ordered factor encoded as an integer. For learners which don't directly handle ordered factors you'd have to do this. And of course you can encode any binary feature this way without any consequences. 

I also don't think this has anything to do with the amount of data you have. In general, just because I observe that there are few unique values for feature x, does not mean that I cannot estimate f_x(x) from f(x, y). I may simply have many repeated values of x. The variability in this estimate comes from the amount of training data, the complexity of the underlying function, and the rate at which the learner you use converges to this function or an approximation thereof.

I can see how this would be less likely in your functions @MasonGallo, but it would occur if you had a higher resolution grid for some parameters and a smaller one for others, no?

**Comment by MasonGallo** [comment]
> hmmm i am not sure why i did the whole rep(low:high) thing. the actual bug was truncation?

Yes it seemed that integer features were not correctly drawing a grid. Basically only the `fmin` to `gridsize`  were drawn.

> I can see how this would be less likely in your functions @MasonGallo, but it would occur if you had a higher resolution grid for some parameters and a smaller one for others, no?

I agree, which is why I said I didn't love it. I had left it in for us to discuss. I am a fan of warnings of a similar nature to protect users from "black boxing", but prob elsewhere is a better place.

**Comment by zmjones** [comment]
I am rewriting the prediction grid function now and will issue a pr shortly. I think we can better handle ordered factors and some other things too.

**Pull request merged**
