### PR TITLE
mlrMBO on cran: Integration

### PR DESCRIPTION
**Pull request by jakob-r**
export all tune functions.
adapt test to cran
forward resample.fun

### CODE REVIEW

**Comment by berndbischl** [comment]
pls use code-link in the docs. not just code (eg see OptPath) 

*i* will do this now, step away pls

**Comment by berndbischl** [comment]
you guys also forgot to doc the method. that it exists. in TuneParams.

*always* ask yourself: "is the API i am doing here documented?"

**Comment by berndbischl** [comment]
#'    Should the \code{MBOResult} be stored in the result.

please ALWAYS state the default in docs as last line!

**Comment by berndbischl** [comment]
and dont approve if you dont check this in reading.....

**Comment by berndbischl** [comment]
and why do you simply INGORE the fixme?

  # FIXME: threshold

**Comment by mb706** [comment]
If `resample.fun` now works in mbo, don't forget that `tuneParams` currently forbids it (somewhere around line 115). Also the doc of the `resample.fun` param of `tuneParams` mentions that mbo only works with `resample.fun` == `resample`. Both can be removed now.

**Comment by berndbischl** [comment]
> If resample.fun now works in mbo, don't forget that tuneParams currently forbids it (somewhere around line 115). Also the doc of the resample.fun param of tuneParams mentions that mbo only works with resample.fun == resample. Both can be removed now.

create clean new issue pls

**Comment by berndbischl** [comment]
@jakob-r can you fix rdocs? breaks on travis

i will then merge, so we have it on cran

**Comment by berndbischl** [comment]
@jakob-r 
please dont fix 5 different things in one PR anymore. especially distributing the docs to different files is really othogonal.

**Pull request merged**
