### PR TITLE
Support for functional data through matrix columns 

### PR DESCRIPTION
**Pull request by pfistfl**
After talking to Bernd, we decided to go with the "functional matrix" column idea for the data. frame.

# What are functional Data? 
Functional features are measurements taken over a continuum (such as time).
Thus an observation of a functional feature is not a single scalar value but a vector of scalars (like a time-series).
In a data.frame, such a feature can be represented as a matrix of dimensions
 _number-of-observations_ *X* _time-series-length_.
(Note, that for now we assume for all time-series to be of equal length and measured at equal time-points).

ecg

# How do we want to support it in mlr?
In mlr, functional data are **matrix-columns**, i.e. columns of a data.frame of class matrix.
The function ```makeFunctionalData()``` allows for the transformation of numeric columns to 
such matrix columns. 
Supplying a data.frame with matrix columns to make...Task creates a task with functional features:

## Create a (Classification) Task
```R
# Measurements of the features "fd1" and "fd2" are contained in columns
# 1:6 and 8:10 of the data.frame
# Column 7 is a scalar numeric feature
df = data.frame(matrix(rnorm(10), nrow = 1), "target" = sample(letters[1:2], 10, replace = TRUE))
# Transform to functional data (fd.features indicate column names or indices)
fdf = makeFunctionalData(df, fd.features = list("fd1" = 1:6, "fd2" = 8:10))
# Create a classification task
tsk = makeClassifTask(data = fdf, target = "target")
tsk
```
>_Supervised task: fdf
Type: classif
Target: target
Observations: 10
Features:
   numerics     factors     ordered functionals 
                   1                    0                    0                    2 
Missings: FALSE
Has weights: FALSE
Has blocking: FALSE
Classes: 2
a b 
6 4 
Positive class: a_

## Train on a Task
These Tasks can now be used in conjunction either with a fda-learner, e.g. *classif.fdaknn* or standard learners like *classif.rpart*, in which case the functional features are treated as standard numeric features. 

**New learners**:  _classif.fdaknn, classif.fdakernel, classif.fdanp, classif.fdaglm, regr.fdafgam, regr_fdaFDboost_
```R
# Either use a fda learner
# In this case we have to subset the 3rd (functional) feature
lrn = makeLearner("classif.fdaknn", predict.type = "prob")
resample(lrn, subsetTask(tsk, features = 3), cv2)

# Or a classic learner for numerics
lrn = makeLearner("classif.rpart")
resample(lrn, tsk, cv2)
```

## Extract non-functional Features from a Task 
Additionally, we can now extract non-functional features from a Task in order to apply classic ML-Algorithms to the transformed features.

**New Methods**: _extractFDAMean, extractFDAMinMax, ..., extractFDAFourier, extractFDAWavelets, extractFDAFpca, extractFDAMultiResFeatures_

```R
# feat.methods specifies what to extract from which functional
# from the first functional we extract the mean, from the second the fpca scores
feat.methods = list("fd1" = extractFDAMean(), "fd2" = extractFDAFourier())

# Either create a new task from an existing task
extractFDAFeatures(tsk, feat.methods = feat.methods)

# Or use a FDAFeatExtractWrapper
makeExtractFDAFeatsWrapper("classif.rpart",  feat.methods = feat.methods)
```

## Misc
Some helpers have been added:
```R 
# Get only functional features from either a Task or a data.frame
getFunctionalFeatures(obj)

# Does the Task/data.frame/TaskDesc contain functional features?
hasFunctionalFeatures(obj)

# getTaskData got a new parameter, that lets you return the functional features 
# either as a matrix or converted to numerics
getTaskData(tsk, functionals.as = "matrix" | "dfCols")
```

**New learner properties**: "single.functional", "functionals"

# Todo's
In the coming days I will add support for:

- [x] Learners ( also those from #1517 )
  - [x] FDAClassif.knn
  - [x] FDAClassif.np
  - [x] FDAClassif.glm
  - [x] FDAClassif.kernel
  - ~[ ] FDAClassif.shapelet~ (Not on Cran)
  - ~[ ] regr.fdafgam (Xudong?)~ (Moved to todo-files for now, will be added later)
  - [x] regr.fdaFDboost (Xudong?)
  - ~[ ] Learners from *maierhofert/classiFunc* (optional, PR already exists)~ (Wait for merge)
  
- [x] Throw error when applying fdalrn to non-fda task

- [x] Feature  Extraction #1774 
  - [x] Wavelets
  - [x] Fpca
  - [x] Fourier
  - [x] Generics (Min, Max, Mean, ...)
  
- [x] Multiresolution Features #1517 
- [x] documentation 
- [x] unit tests for fda.tasks subsetting ( = subsetTask )
- [x] update tutorial
- [x] tests for benchmarking fda.lrns + standard ML lrns
- [x] Functions produce valid errors for wrong / suboptimal inputs
- [x] fix lintr
- [x] fix listLearnerProperties 
- ~[ ] If a data.frame that already contains a matrix is supplied to makeFunctionalData, the colum names 
contain the feature name twice (e.g. NIR.NIR.1)~ (Purely cosmetic)
- [x] Fix testThatLearnerRespectsWeights (see #1897)
- [x] ~Unit tests for filter values + tuning filters~ Delayed for now
- [x] Add phoneme data as a multiclass classif task

# Open Questions:
- Should we throw out functional as class for the matricies in the data.frame ? * -> Yes*
- ~How should filtering work on FDATasks? (As we do not have one feature but each feature is a matrix)~ * -> Not for now* 
- Add a new learner property "functionals"? * Yes,  see question below*
- What do we do if learner can only deal with a single functional (Example: fda.usc::classif.knn) but multiple functionals are present? * -> have learner property single.functional, multiple.functionals*
- What do we want to do in case non-functional features are present in a data.frame. * -> error* 

@smilesun @lbeggel @berndbischl 
Anything to add? Any comments?

### CODE REVIEW

**Comment by smilesun** [comment]
1. LSTM data are usually non-equal length, when we decide to support the non-equal length data,  we have to think how to deal with that
2. Currently, we use the functional features as column names, how about functional grids?
3. Of course we could switch matrix df into a normal df while stil keep the functional.features somewhere else, but generally, from a design point of view, I am not really convinced by any approach that trying to change the behavior of a tire of a car instead of having a new tire for the car which inherits the tire behavior.

**Comment by pfistfl** [comment]
> 1. I think for now we will have to go with NA padding or something. Unequal length is a problem for any data.frame approach I think.
> 2. If we want to support ``fd.grids`` we have to think of something.

**Comment by pfistfl** [comment]
@berndbischl 
Should we throw out functional as class ?
```
  df = data.frame(matrix(rnorm(10^2), nrow = 10))
  df$fct = as.factor(letters[1:10])
  df$ord = as.ordered(1:10)
  fdf = makeFunctionalData(df, fd.features = list("fd1" = 1:5, "fd2" = 6:9))

  # Subset rows
  fdf2 = fdf[1:5, , drop = FALSE]
  expect_equal(sapply(fdf2, class)[[1]], "numeric")
  expect_equal(sapply(fdf2, class)[[2]], "factor")
  expect_equal(sapply(fdf2, class)[[3]], c("ordered", "factor"))
  # FAILS:
  # expect_equal(sapply(fdf2, class)[[4]], c("functional", "matrix"))
  # expect_equal(sapply(fdf2, class)[[5]], c("functional", "matrix"))
  # REASON: "functional" class is dropped, only "matrix" is kept
```

**Comment by pfistfl** [comment]
@berndbischl 
2) Do we want to keep the learner types "fdaregr"? 
   Issue: What do we want to do for fdalrn's on tasks that have no functional features
   Should we maybe specify that a learner can deal with "fda" somewhere  (As a property?)

**Comment by pfistfl** [comment]
3) Gerneral Question: 
What do we do if learner can only deal with a single functional (Example: fda.usc::classif.knn) but multiple functionals are present?
- Warn and use only first functional ? 
- Error
- Concat all present functionals

**Comment by smilesun** [comment]
@pfistfl , hi , when I run the FDboost, it seems to have some other errors? Error: Can not find template arg_fdatask_pars.

**Comment by pfistfl** [comment]
@smilesun 
This seems to be something I oversaw in the documentation of the feature extractors. 
I will fix that asap

**Comment by pfistfl** [comment]
So @smilesun 
The error should be fixed now. This was just a documentation artifact from porting the files from other branches.

I have two further things:
- Can you also add regr_fdafgam as well as regr_fdaFDboost? I have a hard time grasping what it does. The files are already ported and just need to be adapted. 
- What about the twoStepAIC Learner from #1517? I have no idea what we were using it for.

**Comment by smilesun** [comment]
@pfistfl ,   I could add fgam and others, but not before Tuesday.

**Comment by berndbischl** [comment]
Noch offene Sachen:

- geht ein featureless learner, wenn wir functionals haben? mal testen. unit test.

- getFunctionalFeatures: export, doc, unit test. schön machen. 

- bei makeFunctionalData und getFunctionalFeatures alle args sinnvoll asserten

- BB: am ende NEWS überprüfen. 

- für fd.grids eine issue aufmachen

- was passiert hier: ich benutzte nicht makeFunctionalData sondern geb dem task gleich einen df wo matrizen drin sind
-- ist das format dokumentiert?
-- wir überprüft dass es nur  numerische / int mats sind?
-- gibt es einen unit test

**Comment by pfistfl** [comment]
The extractFDAFeatures stuff is done. Are you gonna ask Martin?

**Comment by pfistfl** [comment]
I pushed the other files aswell, Im not done with the makeFunctionalData stuff, only extractFDAFeatures is done.

**Comment by pfistfl** [comment]
Done, summoning the mighty @berndbischl

**Comment by pfistfl** [comment]
Ping @berndbischl

**Pull request merged**
