### PR TITLE
getFeatureImportance function added

### PR DESCRIPTION
**Pull request by ljudt**
getFeatureImportance function added to attain importance values for certain learners. These learners are:

- boosting
- gbm
- cforest
- randomForest
- rpart

New property 'featimp' for learners and small unit test also included.

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks. Two small comments: First, could you update NEWS please, and second, could you check the return values in the unit tests as well please rather than just that the function runs without error?

**Comment by larskotthoff** [comment]
@ljudt ping

**Comment by berndbischl** [comment]
i guess @ljudt is gone here and dropped out. if we want this, we need to take care of this.

**Comment by jakob-r** [comment]
More learners could be:
* ranger

**Comment by zmjones** [comment]
also randomForestSRC. probably others as well. i would very much like to have this so i will try to work on cleaning it up and adding some missing things.

**Comment by florianfendt** [comment]
@berndbischl 
I pushed a PR on this. Can we close here, or leave it open until the new one is merged?

**Comment by berndbischl** [comment]
continued in #667

**Comment by larskotthoff** [comment]
Obsolete, closing.

**Pull request closed without merging**
