### PR TITLE
Enable batchmark and tuneParams tests

### PR DESCRIPTION
**Pull request by mb706**
idk if they were disabled for a reason
See #1839

### CODE REVIEW

**Comment by berndbischl** [comment]
dont merge, i dont want too many "run" files

**Comment by berndbischl** [comment]
1) test_tuneParams: this should be merged with test_base_tuning. proper name would be
test_base_tunePatrams

2) test_batchmark. should be called test_base_batchmark

**Comment by mb706** [comment]
Someone who knows what the batchmark test is supposed to be doing can take over.

**Comment by pat-s** [comment]
the batchmark test now lives in `test_baseoncran` and runs on Travis. Can we close here and the related issue?

**Comment by pat-s** [comment]
Closing for now as it is very unclear if this PR is still valid right now.

**Pull request closed without merging**
