### PR TITLE
Exclude NAs when number of unique levels is lower than grid size

### PR DESCRIPTION
**Pull request by HarikaMGR**
Exclude NAs when number of unique levels is lower than grid size

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks. I assume that this replaces your other pull request? Could you add a unit test please?

**Comment by larskotthoff** [comment]
ping @HarikaMGR

**Comment by berndbischl** [comment]
also very important point: 
this changes behavior corrrect? 
PLEASE NEVER merge this, if this is not properly documented.

**Comment by berndbischl** [comment]
so in this case there should be a comment in code, and a sentence in the roxygen docs

**Comment by larskotthoff** [comment]
ping @HarikaMGR

**Comment by pat-s** [comment]
`generateFeatureGrid()` does not exist anymore since f09ee72135ef6618bbdb4eaab1b8e979f71fb65b, closing.

**Pull request closed without merging**
