### PR TITLE
Enhancement of learners from penalized package (Issue #612)

### PR DESCRIPTION
**Pull request by florianfendt**
Ok, got a bit of a bigger project than I expected.
What I did:
1) got the parameters right (hopefully ;) )
2) added the classification learners
3) To have the survival learner consistent with the above I split up the learner into the 3 learners ridge, lasso, fusedlasso

Update for NEWS:
````
- Added the missing learner parameters for regr.penalized.lasso and regr.penalized.ridge

new learners
-- regr.penalized.fusedlasso
-- classif.penalized.ridge
-- classif.penalized.lasso
-- classif.penalized.fusedlasso
-- surv.penalized.ridge
-- surv.penalized.lasso
-- surv.penalized.fusedlasso

removed learners
-- surv.penalized
````

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks! I'm not sure how I feel about the hardcoded 0.5 threshold for converting the probabilities to class labels though. I would make this another parameter for the learner (with a default of 0.5) so that the user can adjust this easily.

Opinions?

**Comment by berndbischl** [comment]
> Thanks! I'm not sure how I feel about the hardcoded 0.5 threshold for converting the probabilities to class labels though. I would make this another parameter for the learner (with a default of 0.5) so that the user can adjust this easily.

No, that is standard for all learners. mlr allow predict.type = "prob" to handle that specfically, then you have setThreshold and tuneThreshold and so on

**Comment by larskotthoff** [comment]
Ok, fair enough.

Looks like some tests are failing though. Could you please have a look @florianfendt ?

**Comment by florianfendt** [comment]
Fixed now.
I had a typo in the survival learners,
and the class labels for the classification learners were switched, as penalized predicts probabilities on
second level of target apparently.

**Comment by berndbischl** [comment]
So the label switching unit test actually did something good and detected that?

**Comment by florianfendt** [comment]
yep.
Btw:
While trying to figure this out I switched the predict type in the label switching test to "response".
Thereby, I found some other learners that might cause problems. I will look into this in more detail,
so we can talk about it on Tuesday and open a new issue for that.

**Comment by berndbischl** [comment]
new PR is #850

**Pull request closed without merging**
