### PR TITLE
closes #1492 fix classif.binomial

### LINKED ISSUE #1492: merged PR for classif.binomial was wrong!
see my comments here

https://github.com/mlr-org/mlr/pull/1479

```
this code change seems incorrect?

the default in ?glm is "model =TRUE"
so this is the info that needs to be in the param set

if you want to override this, set
par.values =list(model = FALSE)

let us PLEASE not get this policy muddled up.

now @Coorsaa did this wrong and @larskotthoff did not see this in review. this is a problem
we need to eliminate that general problem, otherwise i have to go back to fine-review every merge, which we know will not scale....

```

### PR DESCRIPTION
**Pull request by Coorsaa**
I fixed the default of param 'model' and set it to FALSE in the par.vals.
See #1492 and #1479

### CODE REVIEW

**Comment by berndbischl** [comment]
looks good but i would like issues not to be closed by "programming" in the copmmit msg

**Comment by berndbischl** [comment]
can be merged if travis green

**Comment by larskotthoff** [comment]
Re closing issues through commit messages, I'm in favour of that and have been asking people to do it. Otherwise we end up with "orphaned" issues.

**Comment by berndbischl** [comment]
> Re closing issues through commit messages, I'm in favour of that and have been asking people to do it. Otherwise we end up with "orphaned" issues.

ok, noted. and i can understand. but then the "merger" needs to take responsibility by checking that there is nothing of "value" anymore in the issue, and that the PR deals really with 100% of what was discussed there

**Comment by berndbischl** [comment]
(which you kinda need to do anyhow in the review)

**Comment by larskotthoff** [comment]
Yep.

**Pull request merged**
