### PR TITLE
add generic clustering as classification wrapper

### PR DESCRIPTION
**Pull request by larskotthoff**
Not sure about the name, it's a bit clunky. Suggestions appreciated.

### CODE REVIEW

**Comment by jakob-r** [comment]
I think this is more some kind of preprocessing and it should be completely possible to do it with `makePreprocWrapper`. But I have to admit that I only hat a quick glimpse at your code.

**Comment by larskotthoff** [comment]
Hmm, not sure that this could be done entirely in preprocessing -- during the prediction phase I also need to determine the class distribution for the assigned cluster and then determine the label based on that for response.

This can also be extended to support fuzzy clustering and then the determination of the label during prediction becomes even more complex.

**Comment by berndbischl** [comment]
@jakob-r 
You misunderstand. Lars simply wants to allow the usage of a clustering algorithm as a classifier.
(He also documented this kinda nicely?)
I am not a big fan of this approach, but some people do this and having this in mlr would allow easy comparisons.

**Comment by berndbischl** [comment]
NB: I did NOT review this properly yet

**Comment by larskotthoff** [comment]
This could probably also be extended to allow stacking on top of it, e.g. build a separate classification model for each cluster.

**Comment by zmjones** [comment]
I have nothing to add but this is cool.

**Comment by larskotthoff** [comment]
I've renamed this to `ClassificationViaClustering` to be less confusing.

**Comment by berndbischl** [comment]
Lars, can you pls convince me again we should put that into the package?

**Comment by larskotthoff** [comment]
Talked about this, I'll try to find some concrete examples where this helps.

Also Weka has it, see http://weka.sourceforge.net/doc.stable/weka/classifiers/meta/ClassificationViaClustering.html and also http://weka.sourceforge.net/doc.dev/weka/classifiers/meta/ClassificationViaRegression.html

**Comment by berndbischl** [comment]
the docs say you dont support probs, but the code does.
also apparently you do at least some kind of normalization.

please precisely say what happens here in docs.

**Pull request closed without merging**
