### PR TITLE
fix weights 

### PR DESCRIPTION
**Pull request by berndbischl**
fix weights tags for learners and make sure that weights are indeed passed down correctly, and add a general unit test for this

please read issue #857 

can somebody pls review this when travis is finished?
@studerus @larskotthoff @schiffner  @mllg

### CODE REVIEW

**Comment by berndbischl** [comment]
for NEWS:
-- fixed weight handling and weight tag for some learners

**Comment by berndbischl** [comment]
actually, we should probably also now add tests for clustering and surv

**Comment by studerus** [comment]
Thanks. Looks good, but why did you take out the weights from `classif.ada`? Weighting seems to have an effect on this learner.

**Comment by berndbischl** [comment]
can you pls post your example for this? i thought they did not, maybe i made mistake

**Comment by studerus** [comment]
I just replaced the learner in my original example and increased the weight a little bit:

      lrn <- makeLearner('classif.ada', predict.type = 'prob')
      lrn.w <- makeWeightedClassesWrapper(lrn, wcw.weight = 5)
      benchmark(list(lrn, lrn.w), pid.task, cv10, list(bac, auc, tpr, tnr))

You can see that the true positive rate increases as it should

**Comment by berndbischl** [comment]
but like I posted in the issue thread:
>>> classif.ada had the weights tag, but "weights" isnt even supported in its API

???

**Comment by studerus** [comment]
Strange. It also does not seem to make a difference whether I set the weights to 10 or 5. I agree do take it out.

**Comment by berndbischl** [comment]
erich, i also just ran your benchmark code in the master branch. i am getting exactly the same results for both learners.

**Comment by berndbischl** [comment]
can you please post your output? because i am getting confused now

**Comment by berndbischl** [comment]
> It also does not seem to make a difference whether I set the weights to 10 or 5. I agree do take it out.

also note in general that this is not enough for some learners. i had to set very extreme weights like 100 or 1000 in some cases to see an effect

**Comment by studerus** [comment]
task.id                  learner.id bac.test.mean auc.test.mean tpr.test.mean tnr.test.mean
    1 PimaIndiansDiabetes-example                 classif.ada     0.7187919     0.8200593     0.6019030     0.8356809
    2 PimaIndiansDiabetes-example weightedclasses.classif.ada     0.7218202     0.8242875     0.6078131     0.8358272

**Comment by studerus** [comment]
with set.seed(1)

**Comment by berndbischl** [comment]
ok erich just saw random noise. ada does not support weights at the moment

**Comment by jakob-r** [comment]
I checked carefully and it looks good. Only thing which bothered me was this unnamed argument [here](https://github.com/mlr-org/mlr/pull/865/commits/d4b327bac49a2a254d09e598d284baadf3b5e5f3#diff-ef2cc592db5a22d79a152642ab415a79R68) :wink:

**Comment by jakob-r** [comment]
my mistake

**Pull request merged**
