### PR TITLE
allow getCaretParamSet to use tasks

### PR DESCRIPTION
**Pull request by kerschke**
This PR is just a minor fix of `getCaretParamSet`, allowing to use `task` instead of `x` and `y`.

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks. Looks like you forgot to update the examples -- could you fix that please?

**Comment by kerschke** [comment]
The R-file contains the updated examples. I just didn't add the updated Rd-file (on purpose, because I was told I should not always update the Rd-files)..
Or do you see any other missing updates?

**Comment by larskotthoff** [comment]
If you change the documentation, you should regenerate it and commit the changes to the Rd files :) The Travis build is failing because of this.

**Comment by kerschke** [comment]
Ok, I can do that. However, that was exactly what I was told in the past ;-)

**Comment by berndbischl** [comment]
Why does travis break if RDs are not regenerated?

**Comment by kerschke** [comment]
Why doesn't travis actually generate the RDs on its own?

**Comment by berndbischl** [comment]
I told Pascal not to commit them as diffs are otherwise harder to read. I never saw an error on travis due to this

**Comment by berndbischl** [comment]
Am I wrong? If so sorry, but I though this is auto-generated on travis anyway?

**Comment by larskotthoff** [comment]
No, Travis doesn't regenerate the documentation. This could be set up, but then we'd need Travis to commit that back to the repo as well (again can be set up, but a little bit more work).

Not regenerating the documentation won't break Travis unless the old examples don't work anymore like in this case.

**Comment by kerschke** [comment]
Ah ok.. So this means it used to work in the past, because I didn't break the previous examples with my previous commits?

**Comment by larskotthoff** [comment]
Yep.

**Comment by larskotthoff** [comment]
Thanks, merging.

**Pull request merged**
