### PR TITLE
revert resample extract to 2.4 behaviour

### PR DESCRIPTION
**Pull request by jakob-r**
.
.
.
never change the NEWS file

### CODE REVIEW

**Comment by berndbischl** [comment]
travis fails, pls repair.
in such cases, run a full local rtest with all groups locally. 
always at least "base" (but here it might be in the featsel test group)

**Comment by jakob-r** [comment]
ready now. ping @berndbischl

**Comment by berndbischl** [comment]
Why is this removed from the last 2 tests in the diff:

-  expect_class(r$extract[[1L]], "FeatSelResult")
-  expect_class(r$extract[[1L]], "TuneResult")

both seem reasonable?

**Comment by jakob-r** [comment]
The manually created extracts are touched.
See highlighted lines:
FeatSelResult: https://github.com/mlr-org/mlr/pull/506/files#diff-71aef02af78b342e61e5720504bfa5fbL13
TuneResult:https://github.com/mlr-org/mlr/pull/506/files#diff-938e266729055cbcf9af27a3c686f56bR78

**Comment by berndbischl** [comment]
ok thx.

**Pull request merged**
